Repository 3scale/porta, pull requests merged in 2018-11, with the labels that each got.

#283 [billing] Prevent non-positive invoices from being charged
  app/models/account/billing.rb
  app/models/invoice.rb
  config/locales/en.yml
  test/integration/finance/api/invoices_controller_test.rb
  test/unit/finance/charging_test.rb
  test/unit/invoice_test.rb
Labels: jenkins

#278 UI enhancements for New API form
  app/assets/stylesheets/provider/_forms.scss
  app/views/api/services/forms/_naming.html.slim
  app/views/api/services/forms/_service_discovery.html.slim
  app/views/api/services/new.html.slim
  features/old/services/multiservice.feature
  features/old/services/switch.feature
Labels: jenkins

#275 Prevent Vertical Navigation items from scrolling up to the top when being clicked
  app/views/shared/provider/navigation/_secondary_nav.html.slim
Labels: jenkins

#267 Improvements in TIME_TO_DELETE_ACCOUNT
  app/helpers/account_helper.rb
  app/models/account/states.rb
  app/workers/find_and_delete_scheduled_accounts_worker.rb
  test/unit/account/states_test.rb
  test/unit/helpers/account_helper_test.rb
  test/unit/helpers/api/account_plans_helper_test.rb
  test/workers/find_and_delete_accounts_scheduled_worker_test.rb
Labels: jenkins

#286 Buyer is not a term we want to use in the UI
  app/views/buyers/users/edit.html.erb
  app/views/buyers/users/show.html.erb
  features/old/buyers/users.feature
Labels: jenkins

#292 Alias Account attribute state_changed_at as the new deleted_at
  app/models/account.rb
Labels: jenkins

#268 Icons for spaces
  app/assets/stylesheets/provider/_menu.scss
  app/assets/stylesheets/provider/_vertical_nav.scss
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/javascript/src/Navigation/components/ActiveMenuTitle.jsx
  app/javascript/src/Navigation/components/ActiveMenuTitle.spec.jsx
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/javascript/src/Navigation/components/ContextSelector.spec.jsx
  app/javascript/src/Navigation/styles/ActiveMenuTitle.scss
  app/javascript/src/Navigation/styles/ContextSelector.scss
  app/javascript/src/Navigation/utils/getActiveMenuTitle.jsx
  app/javascript/src/Navigation/utils/getActiveMenuTitle.spec.jsx
  app/views/provider/admin/dashboards/_service.html.slim
  app/views/provider/admin/dashboards/show.html.slim
  public/packs/dashboard-86117603365e13a08dda.js
  public/packs/dashboard-86117603365e13a08dda.js.gz
  public/packs/dashboard-86117603365e13a08dda.js.map
  public/packs/dashboard-bf5a87fcb060e76c9b61.js
  public/packs/dashboard-bf5a87fcb060e76c9b61.js.gz
  public/packs/dashboard-bf5a87fcb060e76c9b61.js.map
  public/packs/manifest.json
  public/packs/manifest.json.gz
  public/packs/navigation-c4c6613e2ce14fb63092.js
  public/packs/navigation-c4c6613e2ce14fb63092.js.gz
  public/packs/navigation-c4c6613e2ce14fb63092.js.map
  public/packs/navigation-f677a665c697929ee4e7.js
  public/packs/navigation-f677a665c697929ee4e7.js.gz
  public/packs/navigation-f677a665c697929ee4e7.js.map
  public/packs/policies-221156de03fef790b50b.js
  public/packs/policies-221156de03fef790b50b.js.gz
  public/packs/policies-221156de03fef790b50b.js.map
  public/packs/policies-2ee63d40bbeb2d7617c7.js
  public/packs/policies-2ee63d40bbeb2d7617c7.js.gz
  public/packs/policies-2ee63d40bbeb2d7617c7.js.map
Labels: doc-req, jenkins

#260 Fix wrapping version number in footer
  app/assets/stylesheets/provider/_footer.scss
Labels: jenkins

#285 [Service Discovery] Generic error on cluster resource fetch
  app/models/service_discovery/cluster_client.rb
  test/unit/service_discovery/cluster_client_test.rb
Labels: jenkins

#291 [cron] Commands are now properly generated
  Gemfile.base
  Gemfile.lock
  Gemfile.prod.lock
  config/schedule.rb
Labels: jenkins

#297 Aligning login page menu
  app/assets/stylesheets/provider/_menu.scss
  app/views/layouts/provider/login.html.slim
Labels: jenkins

#282 THREESCALE-1471 Using Flex to align menu items
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/views/provider/admin/dashboards/_service.html.slim
  app/views/provider/admin/dashboards/show.html.slim
Labels: jenkins

#299 Remove links to plans from dashboard
  app/views/provider/admin/dashboards/_developers_navigation.html.slim
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  features/old/menu/dashboard.feature
Labels: jenkins

#300 Quick Fix: Aligning items to the left
  app/assets/stylesheets/provider/admin/_dashboard.scss
Labels: jenkins

#303 Master dashboard shows the right number of tenants
  app/views/provider/admin/dashboards/show.html.slim
Labels: jenkins

#304 Prevent user without permissions from seeing service as a clickable in context selector
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/javascript/src/Navigation/components/ContextSelector.spec.jsx
  app/javascript/src/Navigation/styles/ContextSelector.scss
  public/packs/dashboard-86117603365e13a08dda.js
  public/packs/dashboard-86117603365e13a08dda.js.gz
  public/packs/dashboard-86117603365e13a08dda.js.map
  public/packs/dashboard-a2a5eb3eb48bf6d8aeb9.js
  public/packs/dashboard-a2a5eb3eb48bf6d8aeb9.js.gz
  public/packs/dashboard-a2a5eb3eb48bf6d8aeb9.js.map
  public/packs/manifest.json
  public/packs/manifest.json.gz
  public/packs/navigation-7cdccc13141616d66596.js
  public/packs/navigation-7cdccc13141616d66596.js.gz
  public/packs/navigation-7cdccc13141616d66596.js.map
  public/packs/navigation-f677a665c697929ee4e7.js
  public/packs/navigation-f677a665c697929ee4e7.js.gz
  public/packs/navigation-f677a665c697929ee4e7.js.map
  public/packs/policies-2ee63d40bbeb2d7617c7.js
  public/packs/policies-2ee63d40bbeb2d7617c7.js.gz
  public/packs/policies-2ee63d40bbeb2d7617c7.js.map
  public/packs/policies-c40172680fcd63c10cf8.js
  public/packs/policies-c40172680fcd63c10cf8.js.gz
  public/packs/policies-c40172680fcd63c10cf8.js.map
Labels: jenkins

#305 various permission fixes for master on prem
  app/views/shared/provider/navigation/audience/_messages.html.slim
  app/views/shared/provider/navigation/audience/_nav.html.slim
  app/views/shared/provider/navigation/audience/_portal.html.slim
  app/views/shared/provider/navigation/service/_analytics.html.slim
  app/views/shared/provider/navigation/service/_applications.html.slim
  app/views/shared/provider/navigation/service/_end_users.html.slim
  app/views/shared/provider/navigation/service/_nav.html.slim
  config/abilities/switches.rb
  features/old/menu/api_menu.feature
Labels: jenkins

#301 Removes traces of custom logo
  app/views/provider/_logo.html.slim
Labels: jenkins

#306 no forum if account cannot use forum or user cannot manage forum
  app/views/shared/provider/navigation/audience/_nav.html.slim
  app/views/shared/provider/navigation/audience/_portal.html.slim
Labels: jenkins

#309 THREESCALE-1472-Api-Selector-Overlapped
  app/assets/stylesheets/provider/_header.scss
Labels: jenkins

#274 [gem] Expose sidekiq metrics to prometheus
  .gitignore
  .rubocop.yml
  Gemfile.base
  Gemfile.lock
  Gemfile.prod.lock
  config/application.rb
  config/docker/prometheus.yml
  config/examples/prometheus.yml
  config/initializers/bugfix_rails_18666.rb
  config/routes.rb
  lib/routing_constraints.rb
  test/integration/prometheus_test.rb
Labels: jenkins

#311 fix botched 3scale icon
  app/assets/stylesheets/provider/_header.scss
Labels: jenkins, percy

#310 THREESCALE-1382 Adding word-break to metric names in Current Utilization
  app/assets/stylesheets/provider/_tables.scss
  app/views/buyers/applications/_utilization.html.erb
Labels: jenkins

#296 Fix Oracle tests
  features/step_definitions/metric_steps.rb
  test/unit/liquid/drops/application_drop_test.rb
  test/unit/tasks/impersonation_admin_user_test.rb
Labels: jenkins, oracle

#312 THREESCALE-1471 Fix Aligning list items using flex
  app/assets/stylesheets/provider/admin/_dashboard.scss
Labels: jenkins

#307 Master bought cinstance should not appear as a provided cinstance
  app/controllers/api/applications_controller.rb
  app/models/cinstance.rb
  test/integration/api/applications_controller_test.rb
  test/unit/cinstance_test.rb
Labels: jenkins

#317 integration icon is a wrench
  app/views/provider/admin/dashboards/_service_navigation.html.slim
Labels: jenkins, percy

#298 [config] Correct docker config of memcached
  config/docker/cache_store.yml
Labels: jenkins

#320 API Endpoint for Authentication Provider Developer Portal Update also updates site
  app/controllers/admin/api/authentication_providers_controller.rb
  test/integration/admin/api/authentication_providers_controller_test.rb
Labels: jenkins

#314 THREESCALE-1470 Highlights more visible
  app/assets/stylesheets/provider/_colors.scss
  app/assets/stylesheets/provider/admin/cms/_cms_intro.scss
Labels: jenkins

#318 use paperclip for subscriptions icon
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  app/views/shared/provider/navigation/service/_nav.html.slim
Labels: jenkins, percy

#316 Fix paths to Service->Analytics->Usage
  app/views/api/integrations/apicast/shared/_client_feedback.html.slim
  app/views/api/integrations/plugin/_plugin.html.slim
  app/views/stats/_sparklines.html.erb
Labels: jenkins

#321 Cucumber Feature Multiservice: Remove JS when it is not used
  features/old/services/multiservice.feature
Labels: jenkins

#261 Service Mesh on the Integraton page [THREESCALE-1426]
  app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
  app/lib/logic/rolling_updates.rb
  app/models/proxy.rb
  app/models/service.rb
  app/services/proxy_test_service.rb
  app/views/api/integrations/edit.html.slim
  app/views/api/integrations/service_mesh/_form.html.slim
  app/views/api/integrations/show.html.slim
  app/views/api/services/forms/_integration_settings.html.slim
  config/examples/rolling_updates.yml
  config/locales/en.yml
  openshift/system/config/rolling_updates.yml
  test/unit/proxy_test.rb
  test/unit/service_test.rb
Labels: jenkins

#313 PatternFly/Middleware look & feel for sign-in page.
  app/assets/stylesheets/provider/_menu.scss
  app/assets/stylesheets/provider/layouts/_login.scss
  app/views/layouts/provider/login.html.slim
  app/views/provider/sessions/_request_password_reset_form.html.slim
  app/views/provider/sessions/new.html.slim
Labels: jenkins

#326 style text beneath authorize link
  app/assets/stylesheets/provider/layouts/_login.scss
  app/views/provider/sessions/new.html.slim
Labels: jenkins

#324 moved from own repo (@gsaslis) to 3scale repo
  .circleci/config.yml
Labels: jenkins

#327 THREESCALE-1523 Adding required attribute to selects
  app/views/api/services/forms/_service_discovery.html.slim
Labels: jenkins

#330 [hotfix] Service discovery should not be accessible if not enabled in the config
  app/lib/service_discovery/oauth_configuration.rb
  test/unit/service_discovery/oauth_configuration_test.rb
Labels: jenkins

#332 Add upload/delete logo to audience > dev portal
  app/controllers/provider/admin/account/logos_controller.rb
  app/views/provider/admin/account/logos/_logo.html.slim
  app/views/provider/admin/account/logos/edit.html.slim
  app/views/provider/admin/account/logos/update.js.erb
  app/views/shared/provider/navigation/audience/_portal.html.slim
  config/routes.rb
  features/old/site/logo.feature
  features/support/paths.rb
Labels: jenkins

#319 Fixes CSV download in IE11
  app/assets/stylesheets/provider/stats/_base.scss
  assets/bundles/all.js
  assets/stats/lib/csv_link.es6
Labels: jenkins

#335 fix error message positioning
  app/assets/stylesheets/provider/layouts/_login.scss
Labels: jenkins

#336 Don't shorten long API names as customers depend on them
  app/assets/stylesheets/provider/admin/_dashboard.scss
Labels: jenkins

#334 scope number of applications by developer account
  app/views/buyers/accounts/_menu.html.slim
  app/views/buyers/accounts/_search_results.html.slim
  test/integration/buyers/accounts_controller_test.rb
Labels: jenkins

#7 fix broken links
  CONTRIBUTING.md
  INSTALL.md
Labels: jenkins

#339 Master bought cinstance should not appear as a provided cinstance [Part 2]
  app/controllers/buyers/applications_controller.rb
  test/integration/buyers/applications_controller_test.rb
Labels: jenkins

#323 Cucumber feature for link from integration/edit to analytics usage
  features/provider/integration/edit.feature
  features/step_definitions/plans/application_plans_steps.rb
  features/step_definitions/service_steps.rb
Labels: jenkins, oracle

#343 DeletePlainObjectWorker ignores errors when the object has been destroyed
  app/workers/delete_plain_object_worker.rb
Labels: jenkins, oracle

#344 Fix failures on Cinstance Tests
  test/unit/cinstance_test.rb
Labels: jenkins

#345 Fixes small warning when running Cucumbers
  app/views/payment_gateways/_stripe.html.erb
Labels: jenkins

#342 count total apps in dashboard visible to current user.
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  app/views/provider/admin/dashboards/show.html.slim
Labels: jenkins

#346 Fix navigation hint for dev portal access code
  lib/developer_portal/app/views/developer_portal/access_codes/show.html.erb
Labels: jenkins

#347 Removes deprecation warnings for "equal_to nil"
  test/functional/admin/api/services/mapping_rules_controller_test.rb
  test/functional/provider/admin/messages/trash_controller_test.rb
  test/integration/payment_gateways/braintree_blue_test.rb
  test/integration/sessions_test.rb
  test/unit/account_test.rb
  test/unit/api_authentication/http_authentication_test.rb
  test/unit/cms/template_test.rb
  test/unit/deploy/basic_info_test.rb
  test/unit/developer_portal/controller_methods/plan_changes_methods_test.rb
  test/unit/forms/onboarding/api_form_test.rb
  test/unit/forms/onboarding/request_form_test.rb
  test/unit/helpers/application_helper_test.rb
  test/unit/liquid/drops/invoice_drop_test.rb
  test/unit/liquid/drops/pagination_test.rb
  test/unit/liquid/filters/form_helpers_test.rb
  test/unit/presenters/dashboard/top_traffic_presenter_test.rb
  test/unit/service_discovery/well_known_fetcher_test.rb
  test/unit/services/messages/destroy_all_service_test.rb
  test/unit/three_scale/oauth2/keycloak_client_test.rb
  test/unit/three_scale/oauth2/redhat_customer_portal_client_test.rb
  test/unit/user_session_test.rb
Labels: jenkins

#348 Remove empty helpers' classes/modules and tests
  app/helpers/admin/cinstances/invoices_helper.rb
  app/helpers/admin/cinstances/messages_helper.rb
  app/helpers/admin/contracts_helper.rb
  app/helpers/admin/finance/dashboards_helper.rb
  app/helpers/admin/finance/line_items_helper.rb
  app/helpers/admin/sessions_helper.rb
  app/helpers/analytics/dashboards_helper.rb
  app/helpers/analytics/traffic_helper.rb
  app/helpers/analytics/users_helper.rb
  app/helpers/api/account_plans_helper.rb
  app/helpers/api/application_plans_helper.rb
  app/helpers/api/service_plans_helper.rb
  app/helpers/api/supports_helper.rb
  app/helpers/cross_domain_sessions_helper.rb
  app/helpers/dashboards_helper.rb
  app/helpers/fields_definitions_helper.rb
  app/helpers/finance/provider/settings_helper.rb
  app/helpers/provider_sessions_helper.rb
  test/unit/helpers/api/application_plans_helper_test.rb
  test/unit/helpers/api/service_plans_helper_test.rb
  test/unit/helpers/api/supports_helper_test.rb
  test/unit/helpers/buyers/service_contracts_helper_test.rb
  test/unit/helpers/finance/provider/settings_helper_test.rb
  test/unit/helpers/reports_helper_test.rb
Labels: jenkins

#349 Configure the Github app to prevent us for merging PRs to check for certain words in the title
  .github/wip.yml
Labels: jenkins

#351 Revert "Configure the Github app to prevent us for merging PRs to check for certain words in the title"
  .github/wip.yml
Labels: jenkins

#350 THREESCALE-1382 Adding word break to first child of td's in table.data
  app/assets/stylesheets/provider/_tables.scss
  app/views/buyers/applications/_utilization.html.erb
Labels: jenkins

#352 Nudge users to un-attached api docs when it might make sense.
  app/models/api_docs/service.rb
  app/views/admin/api_docs/base/index.html.slim
  test/unit/api_docs/service_test.rb
Labels: jenkins

#359 fixes minitest random error
  test/unit/tasks/forum/migrate_forum_test.rb
Labels: jenkins

#354 Oracle build running on circleci
  .circleci/config.yml
  features/step_definitions/api_docs_step.rb
  features/support/thread_safety.rb
  lib/tasks/ci/db.rake
  lib/tasks/integration.rake
Labels: jenkins, oracle

#357 [Service Discovery] Fix API endpoint without path
  app/models/service_discovery/cluster_service.rb
  test/unit/service_discovery/cluster_service_test.rb
Labels: bug, jenkins

#356 NotificationDeliveryService nil value invalid event. Blank valid
  app/services/notification_delivery_service.rb
  test/unit/services/notification_delivery_service_test.rb
Labels: jenkins

#322 Refactor dashboard_collection_link method
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/helpers/provider/admin/dashboards_helper.rb
  app/views/provider/admin/dashboards/_developers_navigation.html.slim
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  app/views/provider/admin/dashboards/widgets/_service_integration_errors.html.slim
  test/unit/helpers/provider/admin/dashboards_helper_test.rb
Labels: jenkins

#294 [Part 1] Change Accounts column name deleted_at -> state_changed_at
  app/helpers/account_helper.rb
  app/models/account.rb
  app/models/account/states.rb
  db/migrate/20181105203727_add_accounts_state_changed_at.rb
  db/migrate/20181105212016_duplicate_deleted_at_state_changed_at.rb
  db/oracle_schema.rb
  db/schema.rb
  spec/acceptance/api/account_spec.rb
  test/integration/master/api/providers_controller_test.rb
  test/unit/account/states_test.rb
Labels: jenkins, oracle

#244 ApiDocs Xpath tests as a Cucumber feature
  features/provider/active_docs.feature
  features/services/active_docs.feature
  features/step_definitions/active_docs_steps.rb
  features/support/paths.rb
  features/support/selectors.rb
  test/integration/admin/api_docs/account_api_docs_controller_test.rb
  test/integration/admin/api_docs/service_api_docs_controller_test.rb
Labels: jenkins
