Repository 3scale/porta, pull requests merged in 2018-10, with the labels that each got.

#65 Fix N+1 Query on ProviderData#application_plan_ids for service of application_plans
  lib/api_docs/provider_data.rb
Labels: jenkins

#70 [billing] Tests for the invoice friendly id workers
  test/workers/invoice_friendly_id_sanitization_worker_test.rb
  test/workers/invoice_friendly_id_worker_test.rb
Labels: jenkins

#76 [Bugfix] ActiveRecord::StatementInvalid: OCIError: ORA-04043: object SP_INVOICES_FRIENDLY_ID does not exist
  lib/system/database.rb
Labels: jenkins, oracle

#79 [Hotfix] Fix redirect_url update link
  app/views/buyers/applications/edit_redirect_url.html.erb
Labels: jenkins

#86 ActiveDocs' account is required now
  app/models/api_docs/service.rb
  lib/tasks/swagger.rake
  test/unit/api_docs/service_test.rb
  test/unit/tasks/swagger_test.rb
Labels: jenkins

#77 [navigation] Fixing cukes due to new navigation features
  app/javascript/packs/navigation.js
  app/javascript/src/Navigation/api_selector.jsx
  app/javascript/src/Policies/index.jsx
  app/views/shared/_api_selector.html.slim
  app/views/shared/provider/_user_widget.html.slim
  features/buyers/accounts/managing.feature
  features/buyers/applications/managing.feature
  features/old/api/settings.feature
  features/old/proxy.feature
  lib/tasks/integration.rake
  package.json
  public/packs/manifest.json
  public/packs/manifest.json.gz
  public/packs/navigation-41476c9094239bbda6e5.js
  public/packs/navigation-41476c9094239bbda6e5.js.gz
  public/packs/navigation-41476c9094239bbda6e5.js.map
  public/packs/navigation-fdc3ba76387ab5f1794d.js
  public/packs/navigation-fdc3ba76387ab5f1794d.js.gz
  public/packs/navigation-fdc3ba76387ab5f1794d.js.map
  public/packs/policies-2722b72012c3b3bc8836.js
  public/packs/policies-2722b72012c3b3bc8836.js.gz
  public/packs/policies-2722b72012c3b3bc8836.js.map
  public/packs/policies-83840248f9eaee44e8bb.js
  public/packs/policies-83840248f9eaee44e8bb.js.gz
  public/packs/policies-83840248f9eaee44e8bb.js.map
Labels: jenkins

#87 Permissions in a service-driven navigation context
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/views/layouts/api/_service.html.slim
  app/views/provider/admin/dashboards/_service.html.slim
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  app/views/provider/admin/dashboards/show.html.slim
  app/views/shared/provider/_submenu.html.slim
Labels: jenkins

#88 [2.4 Feature][Navigation] Move account plans to settings
  app/controllers/buyers/account_plans_controller.rb
  app/views/shared/provider/_submenu.html.slim
  features/old/api/plans/account_plans.feature
  features/old/menu/provider.feature
Labels: enhancement, jenkins

#62 [Service - ApiDocs relationship] Create relationship and adapt endpoints for Create and Update (UI & API)
  app/controllers/admin/api/api_docs_services_controller.rb
  app/controllers/admin/api_docs/services_controller.rb
  app/models/api_docs/service.rb
  app/models/service.rb
  app/representers/api_docs/service_representer.rb
  app/views/admin/api_docs/services/_form.html.slim
  config/locales/en.yml
  db/migrate/20180928114956_add_service_to_api_docs.rb
  db/oracle_schema.rb
  db/schema.rb
  doc/active_docs/Account Management API.json
  lib/developer_portal/lib/liquid/drops/provider.rb
  test/integration/admin/api/api_docs_services_controller_test.rb
  test/integration/admin/api_docs/services_controller_test.rb
  test/unit/api_docs/service_test.rb
  test/unit/liquid/drops/provider_drop_test.rb
Labels: jenkins

#89 Adds Redis step to Install.md
  INSTALL.md
Labels: jenkins

#92 Improve Test efficiency in ApiDocs::ServiceTest & test `accessible` by its IDs and not by name
  test/unit/api_docs/service_test.rb
Labels: jenkins

#95 Fix Applications Show path in ProviderClicking
  script/stress-test/provider_clicking.rb
Labels: jenkins

#97 [Bugfix] Application url in PlanChanged NotificationMailer
  app/views/notification_mailer/cinstance_plan_changed.html.slim
  app/views/notification_mailer/cinstance_plan_changed.text.erb
  test/mailers/notification_mailer_test.rb
Labels: jenkins

#69 adds verification steps to pr template
  .github/pull_request_template.md
Labels: enhancement

#99 [Bugfix] Change paths/url Application from under buyer to be under service
  app/views/api/alerts/index.html.erb
  app/views/notification_mailer/application_created.html.slim
  app/views/notification_mailer/application_created.text.erb
  app/views/notification_mailer/limit_alert_reached_provider.html.slim
  app/views/notification_mailer/limit_alert_reached_provider.text.erb
  app/views/notification_mailer/limit_violation_reached_provider.html.slim
  app/views/notification_mailer/limit_violation_reached_provider.text.erb
  test/integration/api/alerts_controller_test.rb
  test/mailers/notification_mailer_test.rb
Labels: jenkins

#94 [Bugfix] Stats JS links pointing to old applications show path
  app/lib/stats/service.rb
  app/lib/stats/views/usage.rb
  assets/bundles/all.js
  assets/stats/lib/application_details.es6
  spec/javascripts/stats/lib/applications_table.spec.js
  test/integration/stats/clients_test.rb
  test/integration/stats/services_test.rb
  yarn.lock
Labels: jenkins

#83 [oracle] Fix invoice procedure for friendly_id
  config/examples/database.yml
  docker-compose.test-oracle.yml
  lib/system/database.rb
  lib/system/database/oracle_trigger_with_variables.rb
  lib/system/database/procedures.rb
  lib/system/database/triggers.rb
  lib/tasks/boot.rake
  lib/tasks/db/procedures.rake
  lib/tasks/multitenant/triggers.rake
  script/jenkins.sh
Labels: jenkins, oracle

#98 [rubocop] Configuration fix
  .rubocop.yml
Labels: jenkins

#100 Implements API Search Box in Dashboard
  __mocks__/fileMocks.js
  __mocks__/styleMock.js
  app/javascript/packs/dashboard.js
  app/javascript/src/Dashboard/components/ApiFilter.jsx
  app/javascript/src/Dashboard/components/ApiFilter.spec.jsx
  app/javascript/src/Dashboard/styles/dashboard.scss
  app/views/provider/admin/dashboards/_services_filter.html.slim
  app/views/provider/admin/dashboards/show.html.slim
  jest.config.js
Labels: jenkins

#78 Dashboard links & service filter
  __mocks__/fileMocks.js
  __mocks__/styleMock.js
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/helpers/provider/admin/dashboards_helper.rb
  app/javascript/packs/dashboard.js
  app/javascript/src/Dashboard/components/ApiFilter.jsx
  app/javascript/src/Dashboard/components/ApiFilter.spec.jsx
  app/javascript/src/Dashboard/styles/dashboard.scss
  app/models/user.rb
  app/views/provider/admin/dashboards/_developers_navigation.html.slim
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  app/views/provider/admin/dashboards/_services_filter.html.slim
  app/views/provider/admin/dashboards/_services_navigation.html.slim
  app/views/provider/admin/dashboards/show.html.slim
  jest.config.js
  public/packs/dashboard-dea2c6f3d821230b4acc.js
  public/packs/dashboard-dea2c6f3d821230b4acc.js.gz
  public/packs/dashboard-dea2c6f3d821230b4acc.js.map
  public/packs/dashboard-f6b92c397ee772140a11.js
  public/packs/dashboard-f6b92c397ee772140a11.js.map
  public/packs/manifest.json
  public/packs/manifest.json.gz
  public/packs/navigation-af71cc460a286165a8b0.js
  public/packs/navigation-af71cc460a286165a8b0.js.gz
  public/packs/navigation-af71cc460a286165a8b0.js.map
  public/packs/navigation-b28fbeecb31dc288296e.js
  public/packs/navigation-b28fbeecb31dc288296e.js.map
  public/packs/navigation-fdc3ba76387ab5f1794d.js
  public/packs/navigation-fdc3ba76387ab5f1794d.js.gz
  public/packs/navigation-fdc3ba76387ab5f1794d.js.map
  public/packs/policies-2cc3b0535e0a368d721e.js
  public/packs/policies-2cc3b0535e0a368d721e.js.gz
  public/packs/policies-2cc3b0535e0a368d721e.js.map
  public/packs/policies-2efba67b33799fc9c2b6.js
  public/packs/policies-2efba67b33799fc9c2b6.js.map
  public/packs/policies-5681decf246bdcf80be3.js
  public/packs/policies-5681decf246bdcf80be3.js.gz
  public/packs/policies-5681decf246bdcf80be3.js.map
Labels: jenkins, percy

#3 Support to paths in the Private URL of the APIs
  app/lib/logic/rolling_updates.rb
  app/lib/three_scale/localhost_validator.rb
  app/models/api_docs/service.rb
  app/models/proxy.rb
  app/validators/non_localhost_validator.rb
  app/validators/uri_validator.rb
  config/docker/rolling_updates.yml
  config/examples/rolling_updates.yml
  config/locales/en.yml
  openshift/system/config/rolling_updates.yml
  test/integration/proxy_example_test.rb
  test/unit/proxy_test.rb
  test/unit/validators/non_localhost_validator_test.rb
  test/unit/validators/uri_validator_test.rb
Labels: jenkins

#51 reCAPTCHA doesn't work in on-premises
  app/lib/three_scale/spam_protection/protector.rb
  app/views/sites/spam_protections/edit.html.erb
  config/initializers/captchas.rb
  config/locales/en.yml
  lib/forum_support/posts.rb
  test/integration/sites/spam_protection_test.rb
  test/unit/three_scale/spam_protection_test.rb
Labels: jenkins

#35 Kubernetes/Openshift Service Discovery feature
  .gitignore
  Gemfile.base
  Gemfile.lock
  Gemfile.on_prem.lock
  app/assets/javascripts/provider/admin/apiconfig/services/service_discovery.js.coffee
  app/assets/javascripts/provider/layout/provider.js
  app/controllers/api/services_controller.rb
  app/controllers/provider/admin/service_discovery/cluster_base_controller.rb
  app/controllers/provider/admin/service_discovery/cluster_namespaces_controller.rb
  app/controllers/provider/admin/service_discovery/cluster_projects_controller.rb
  app/controllers/provider/admin/service_discovery/cluster_services_controller.rb
  app/models/service.rb
  app/models/service_discovery/cluster_client.rb
  app/models/service_discovery/cluster_namespace.rb
  app/models/service_discovery/cluster_project.rb
  app/models/service_discovery/cluster_resource.rb
  app/models/service_discovery/cluster_route.rb
  app/models/service_discovery/cluster_service.rb
  app/models/service_discovery/model_extensions.rb
  app/models/service_discovery/namespaced_cluster_resource.rb
  app/services/service_creation_service.rb
  app/views/api/services/forms/_naming.html.slim
  app/views/api/services/forms/_service_discovery.html.slim
  app/views/api/services/new.html.slim
  app/workers/service_discovery/import_cluster_service_definitions_worker.rb
  config/application.rb
  config/docker/service_discovery.yml
  config/examples/service_discovery.yml
  config/routes.rb
  features/old/services/multiservice.feature
  features/step_definitions/service_discovery_steps.rb
  openshift/system/config/service_discovery.yml
  test/functional/api/services_controller_test.rb
  test/test_helpers/service_discovery.rb
  test/unit/service_discovery/cluster_client_test.rb
  test/unit/service_discovery/cluster_service_test.rb
Labels: jenkins

#104 [fix] rake boot:database should only exit when db is not ready
  lib/tasks/boot.rake
Labels: jenkins

#105 Fix service discovery config loading
  config/application.rb
  config/docker/service_discovery.yml
  config/examples/service_discovery.yml
  openshift/system/config/service_discovery.yml
Labels: jenkins

#106 Fix service_discovery.enabled config
  openshift/system/config/service_discovery.yml
Labels: jenkins

#111 Fix service discovery openshift config file
  openshift/system/config/service_discovery.yml
Labels: jenkins

#114 Better logging for Service Discovery import methods
  app/models/service_discovery/model_extensions.rb
  test/unit/service_discovery/model_extensions_test.rb
Labels: jenkins

#103 [db] Migration to prepare service resync for Kubernetes service discovery
  db/migrate/20181008065816_add_kubernetes_service_link_to_service.rb
  db/oracle_schema.rb
  db/schema.rb
Labels: jenkins, oracle

#117 [Service Discovery] Fill lookup column services.kubernetes_service_link
  app/services/service_creation_service.rb
  app/workers/service_discovery/import_cluster_service_definitions_worker.rb
  test/unit/services/service_creation_service_test.rb
Labels: jenkins

#119 [Service Discovery] Fill api_docs_services.service_id
  app/models/api_docs/service.rb
  app/models/service_discovery/model_extensions.rb
  test/unit/service_discovery/model_extensions_test.rb
Labels: jenkins

#118 [Refactor] FrontendController#all_services for api_selector_services helper
  app/controllers/frontend_controller.rb
  app/helpers/menu_helper.rb
  app/views/shared/_api_selector.html.slim
  app/views/shared/provider/_user_widget.html.slim
Labels: jenkins

#112 [cron] Sidekiq Cron weekly should equal to whenever weekly
  config/schedule.rb
  openshift/system/config/sidekiq_schedule.yml
Labels: jenkins

#122 Dashboard improvements for 1 service accounts
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/views/provider/admin/dashboards/_service.html.slim
  app/views/provider/admin/dashboards/_services_filter.html.slim
  app/views/provider/admin/dashboards/_services_navigation.html.slim
  app/views/provider/admin/dashboards/show.html.slim
Labels: jenkins

#113 [webpack] Precompile assets on test env
  Dockerfile
  config/webpacker.ci.yml
  script/jenkins.sh
Labels: jenkins

#124 Fixing overlapping of metric names
  app/assets/stylesheets/provider/_tables.scss
  app/views/api/metrics/_metric.html.erb
Labels: jenkins

#130 Revert "[webpack] Precompile assets on test env"
  Dockerfile
  config/webpacker.ci.yml
  script/jenkins.sh
Labels: jenkins

#131 [ci] Precompile assets before testing
  Dockerfile
  config/webpacker.ci.yml
  lib/tasks/webpacker.rake
  script/jenkins.sh
Labels: jenkins, oracle

#127 Refactor User and Account multiservice?
  app/lib/logic/provider_settings.rb
  app/models/service.rb
  app/models/user.rb
  app/models/user/permissions.rb
  app/views/provider/admin/dashboards/_services_filter.html.slim
  app/views/provider/admin/dashboards/_services_navigation.html.slim
  test/unit/logic/provider_settings_test.rb
  test/unit/service_test.rb
  test/unit/user/permissions_test.rb
  test/unit/user_test.rb
Labels: jenkins

#135 THREESCALE-1382 Long metric names - Applications page
  app/assets/stylesheets/provider/_tables.scss
  app/helpers/usage_limits_helper.rb
Labels: jenkins

#134 [webpack] Do not precompile webpack assets
  Dockerfile
  config/webpacker.ci.yml
  script/jenkins.sh
Labels: jenkins

#128 Fix webpack stale assets on test env
  bin/webpack
  bin/webpack-dev-server
  package.json
  yarn.lock
Labels: jenkins

#137 Extend API Switcher to Context Selector
  app/javascript/packs/navigation.js
  app/javascript/src/Navigation/api_selector.jsx
  app/javascript/src/Navigation/components/ApiSearch.jsx
  app/javascript/src/Navigation/components/ApiSearch.spec.jsx
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/javascript/src/Navigation/components/ContextSelector.spec.jsx
  app/javascript/src/Navigation/utils/getActiveMenuTitle.jsx
  app/javascript/src/Navigation/utils/getActiveMenuTitle.spec.jsx
  app/javascript/src/Navigation/utils/toggle_navigation.jsx
  app/views/shared/_api_selector.html.slim
  jest.config.js
  package.json
  yarn.lock
Labels: jenkins

#129 [Service Discovery] Update/resync
  app/controllers/api/services_controller.rb
  app/controllers/provider/admin/service_discovery/services_controller.rb
  app/helpers/api/services_helper.rb
  app/models/api_docs/service.rb
  app/models/service_discovery/cluster_service.rb
  app/models/service_discovery/cluster_service_specification.rb
  app/models/service_discovery/model_extensions.rb
  app/services/service_creation_service.rb
  app/services/service_discovery/import_cluster_definitions_service.rb
  app/views/api/metrics/index.html.slim
  app/views/api/services/forms/_service_discovery.html.slim
  app/workers/service_discovery/create_service_worker.rb
  app/workers/service_discovery/import_cluster_service_definitions_worker.rb
  app/workers/service_discovery/refresh_service_worker.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20181011104937_add_discovered_to_api_docs_services.rb
  db/oracle_schema.rb
  db/schema.rb
  test/unit/service_discovery/cluster_service_specification_test.rb
  test/unit/service_discovery/cluster_service_test.rb
  test/unit/service_discovery/model_extensions_test.rb
  test/unit/services/service_creation_service_test.rb
  test/unit/services/service_discovery/import_cluster_definitions_service_test.rb
  test/workers/service_discovery/create_service_worker_test.rb
  test/workers/service_discovery/refresh_service_worker_test.rb
Labels: jenkins

#110 Threescale 1379 coffescript to js
  app/assets/javascripts/provider/admin/apiconfig/services/service_discovery.js
  app/assets/javascripts/provider/admin/apiconfig/services/service_discovery.js.coffee
Labels: jenkins

#140 CircleCI workflow
  .circleci/config.yml
  Gemfile
  Gemfile.base
  Gemfile.lock
  Rakefile
  config/cucumber.yml
  config/examples/core.yml
  features/step_definitions/api_docs_step.rb
  features/step_definitions/applications/referrer_filters_steps.rb
  features/step_definitions/rolling_updates_steps.rb
  features/step_definitions/web_steps.rb
  features/support/capybara.rb
  features/support/ci.rb
  features/support/env.rb
  features/support/hooks.rb
  features/support/paths.rb
  features/support/percy.rb
  features/support/sphinx.rb
  features/support/test_helpers.rb
  features/support/timecop_helpers.rb
  lib/tasks/ci/licenses.rake
  spec/spec_helper.rb
  test/controllers/buyers/accounts_controller_test.rb
  test/controllers/developer_portal/admin/messages/inbox_controller_test.rb
  test/controllers/developer_portal/admin/messages/outbox_controller_test.rb
  test/controllers/developer_portal/admin/messages/trash_controller_test.rb
  test/functional/api_docs/proxy_controller_test.rb
  test/functional/developer_portal/admin/messages/inbox_controller_test.rb
  test/functional/developer_portal/admin/messages/outbox_controller_test.rb
  test/functional/developer_portal/admin/messages/trash_controller_test.rb
  test/functional/master/providers/switches_controller_test.rb
  test/functional/provider/admin/accounts_controller_test.rb
  test/functional/provider/admin/api_docs_controller_test.rb
  test/functional/provider/admin/cms/switches_controller_test.rb
  test/functional/provider/admin/dashboard/new_accounts_controller_test.rb
  test/functional/provider/admin/dashboard/potential_upgrades_controller_test.rb
  test/functional/provider/admin/dashboard/service/hits_controller_test.rb
  test/functional/provider/admin/dashboard/service/integration_errors_controller_test.rb
  test/functional/provider/admin/dashboard/service/top_traffic_controller_test.rb
  test/functional/provider/admin/liquid_docs_controller_test.rb
  test/functional/provider/admin/user/notification_preferences_controller_test.rb
  test/integration/admin/api/heroku_proxy_controller_test.rb
  test/integration/admin/cms/switches_controller_test.rb
  test/integration/buyers/accounts_controller_test.rb
  test/integration/provider/admin/account/payment_gateways/braintree_blue_controller_test.rb
  test/integration/provider/admin/accounts_controller_test.rb
  test/integration/proxy_example_test.rb
  test/test_helpers/rolling_updates.rb
  test/test_helpers/transactional_fixtures.rb
  test/unit/date_parsing_test.rb
  test/unit/factories_test.rb
Labels: jenkins

#146 Highlight active context / menu in ContextSelector
  app/javascript/src/Navigation/components/ApiSearch.jsx
  app/javascript/src/Navigation/components/ApiSearch.spec.jsx
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/javascript/src/Navigation/components/ContextSelector.spec.jsx
  app/javascript/src/Navigation/styles/ContextSelector.scss
  app/views/shared/provider/_header.html.slim
Labels: jenkins

#148 [services#show] attributes should mirror post attributes
  app/models/service.rb
  app/representers/service_representer.rb
  test/integration/admin/api/services_controller_test.rb
Labels: jenkins

#164 Provider stats feature
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  features/old/authorization/provider_stats.feature
Labels: jenkins

#149 Switched to codecov from codeclimate for test coverage
  .circleci/config.yml
  Gemfile.base
  Gemfile.lock
  Makefile
  README.md
  docker-compose.mk
  features/support/env.rb
  spec/spec_helper.rb
  test/minitest_helper.rb
  test/test_helper.rb
Labels: jenkins

#6 [service] service is not being deleted measures
  app/events/services/service_scheduled_for_deletion_event.rb
  app/lib/event_store/repository.rb
  app/models/service.rb
  app/subscribers/service_deletion_subscriber.rb
  test/events/services/service_scheduled_for_deletion_event_test.rb
  test/subscribers/service_deletion_subscriber_test.rb
  test/unit/service_test.rb
Labels: jenkins

#178 Fix bundler version for On-premises
  openshift/system/Dockerfile.on_prem
Labels: jenkins

#184 authorization features
  features/old/authorization/provider_accounts.feature
  features/old/authorization/provider_finance.feature
  features/old/authorization/provider_plans_section.feature
  features/old/authorization/provider_settings.feature
  features/old/authorization/provider_stats.feature
  features/support/paths.rb
Labels: jenkins

#219 [boot] Make redis check independent of environment
  lib/tasks/boot.rake
Labels: jenkins

#224 Do not index master account + master account cannot be suspended
  app/controllers/buyers/accounts_controller.rb
  app/indices/account_index.rb
  app/models/account.rb
  app/models/account/states.rb
  test/unit/account/states_test.rb
  test/unit/account_test.rb
Labels: oracle

#238 Reduce loops in Api Filter
  app/views/provider/admin/dashboards/_services_filter.html.slim
Labels: jenkins

#183 [circleci] docker build
  .circleci/config.yml
  Gemfile.prod.lock
  Makefile
  openshift/system/Dockerfile
  openshift/system/Dockerfile.on_prem
Labels: jenkins

#193 [Service Discovery] Implement SSO authentication
  Gemfile.base
  Gemfile.lock
  Gemfile.prod.lock
  app/controllers/api/metrics_controller.rb
  app/controllers/api/services_controller.rb
  app/controllers/master/service_discovery/auth_controller.rb
  app/controllers/provider/admin/service_discovery/auth_controller.rb
  app/controllers/provider/admin/service_discovery/cluster_base_controller.rb
  app/controllers/provider/admin/service_discovery/services_controller.rb
  app/helpers/api/services_helper.rb
  app/lib/service_discovery/authentication_provider_support.rb
  app/lib/service_discovery/config.rb
  app/lib/service_discovery/controller_methods.rb
  app/lib/service_discovery/oauth_configuration.rb
  app/lib/service_discovery/oauth_manager.rb
  app/lib/service_discovery/well_known_fetcher.rb
  app/lib/three_scale/oauth2/client.rb
  app/lib/three_scale/oauth2/client_base.rb
  app/lib/three_scale/oauth2/service_discovery_client.rb
  app/models/account.rb
  app/models/authentication_provider.rb
  app/models/authentication_provider/service_discovery_provider.rb
  app/models/provided_access_token.rb
  app/models/service_discovery/cluster_service.rb
  app/models/service_discovery/cluster_service_specification.rb
  app/models/user.rb
  app/models/user/provided_access_tokens.rb
  app/presenters/provider_oauth_flow_presenter.rb
  app/presenters/service_discovery_oauth_flow_presenter.rb
  app/services/service_discovery/import_cluster_definitions_service.rb
  app/views/api/services/forms/_service_discovery.html.slim
  app/views/api/services/new.html.slim
  app/views/api/services/show.html.slim
  app/workers/service_discovery/create_service_worker.rb
  app/workers/service_discovery/refresh_service_worker.rb
  config/docker/service_discovery.yml
  config/examples/service_discovery.yml
  config/routes.rb
  db/migrate/20181018082620_create_provided_access_tokens.rb
  db/oracle_schema.rb
  db/schema.rb
  lib/api_docs/provider_data.rb
  lib/tasks/multitenant/triggers.rake
  openshift/system/config/service_discovery.yml
  test/unit/service_discovery/cluster_service_specification_test.rb
  test/unit/service_discovery/config_test.rb
  test/unit/service_discovery/oauth_configuration_test.rb
  test/unit/service_discovery/oauth_manager_test.rb
  test/unit/service_discovery/well_known_fetcher_test.rb
  test/unit/services/service_discovery/import_cluster_definitions_service_test.rb
  test/workers/service_discovery/create_service_worker_test.rb
  test/workers/service_discovery/refresh_service_worker_test.rb
Labels: jenkins

#250 [cron] Whenever should pass the BUNDLE_GEMFILE to all tasks
  config/schedule.rb
Labels: jenkins

#252 [Bugfix] Invitation does not require uniqueness emails including its buyers
  app/models/invitation.rb
  test/unit/invitation_test.rb
Labels: jenkins

#264 [drops] Liquid::Drops::Application#alerts is a Drops::Alert collection
  doc/liquid/drops.md
  lib/developer_portal/lib/liquid/drops/application.rb
  test/unit/liquid/drops/application_drop_test.rb
Labels: jenkins

#269 [Refactor] Rename #provider_but_not_master? -> #tenant?
  app/models/account.rb
  app/models/account/states.rb
  test/unit/account_test.rb
Labels: jenkins

#257 AuthorizationProvider bounce redirects to the authorize_url
  app/controllers/provider/sessions_controller.rb
  config/routes.rb
  test/integration/provider/sessions_controller_test.rb
Labels: jenkins

#263 Master sudomains generated without '-admin'
  app/lib/signup/master_domains_builder.rb
  test/unit/account/domains_test.rb
  test/unit/signup/master_domains_builder_test.rb
Labels: jenkins

#273 Merge saas branch to master
  app/lib/signup/master_domains_builder.rb
  doc/liquid/drops.md
  features/support/capybara.rb
  lib/developer_portal/lib/liquid/drops/application.rb
  test/unit/account/domains_test.rb
  test/unit/liquid/drops/application_drop_test.rb
  test/unit/signup/master_domains_builder_test.rb
Labels: jenkins

#266 [alerts] alert without cinstance
  app/models/cinstance.rb
Labels: jenkins
