Repository 3scale/porta, pull requests merged in 2019-03, with the labels that each got.

#654 Removes the “Latest transactions” page for good
  app/assets/javascripts/transaction_feed.js
  app/controllers/api/transactions_controller.rb
  app/lib/backend_client/provider.rb
  app/lib/backend_client/provider/transactions.rb
  app/views/api/integrations/plugin/_plugin.html.slim
  app/views/api/transactions/_table_body.html.erb
  app/views/api/transactions/index.html.erb
  app/views/shared/provider/navigation/_vertical_nav.html.slim
  config/routes.rb
  features/old/api/latest_transactions.feature
  features/step_definitions/latest_transactions_steps.rb
  features/support/paths.rb
  test/functional/api/transactions_controller_test.rb
  test/unit/backend_client/provider/transactions_test.rb
Labels: jenkins

#699 Bumps react-jsonschema-form version to 1.3
  package-lock.json
  package.json
  spec/javascripts/Policies/components/PolicyConfig.spec.jsx
Labels: javascript

#674 Removes flow-typed install from standard install
  .circleci/config.yml
  package.json
Labels: javascript

#705 [Bugfix] CreateServiceTokenWorker rescue ActiveRecord::RecordNotFound & ActiveJob::DeserializationError
  app/workers/create_service_token_worker.rb
  test/workers/create_service_token_worker_test.rb
Labels: bug, ruby

#720 Adds warning styling & info for catch-all mapping rules
  app/assets/javascripts/provider/admin/apiconfig/services/integration.js.coffee
  app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
  app/views/api/integrations/apicast/shared/_mapping_rule.html.erb
  app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
  config/locales/en.yml
Labels: javascript, ruby
