Repository 3scale/porta, pull requests merged in 2019-11, with the labels that each got.

#1347 Refactor types in module Policies
  app/javascript/src/Policies/actions/OriginalPolicyChain.jsx
  app/javascript/src/Policies/actions/PolicyChain.jsx
  app/javascript/src/Policies/actions/PolicyConfig.jsx
  app/javascript/src/Policies/actions/PolicyRegistry.jsx
  app/javascript/src/Policies/actions/index.jsx
  app/javascript/src/Policies/components/CustomPolicies.jsx
  app/javascript/src/Policies/components/CustomPolicy.jsx
  app/javascript/src/Policies/components/PoliciesForm.jsx
  app/javascript/src/Policies/components/PoliciesWidget.jsx
  app/javascript/src/Policies/components/PolicyChain.jsx
  app/javascript/src/Policies/components/PolicyChainHiddenInput.jsx
  app/javascript/src/Policies/components/PolicyConfig.jsx
  app/javascript/src/Policies/components/PolicyList.jsx
  app/javascript/src/Policies/components/PolicyRegistry.jsx
  app/javascript/src/Policies/components/PolicyTile.jsx
  app/javascript/src/Policies/components/Root.jsx
  app/javascript/src/Policies/components/SchemaEditor.jsx
  app/javascript/src/Policies/components/util.jsx
  app/javascript/src/Policies/index.jsx
  app/javascript/src/Policies/middleware/PolicyChain.jsx
  app/javascript/src/Policies/reducers/OriginalPolicyChain.jsx
  app/javascript/src/Policies/reducers/PolicyChain.jsx
  app/javascript/src/Policies/reducers/PolicyConfig.jsx
  app/javascript/src/Policies/reducers/PolicyRegistry.jsx
  app/javascript/src/Policies/reducers/UISettings.jsx
  app/javascript/src/Policies/reducers/index.jsx
  app/javascript/src/Policies/reducers/initialState.jsx
  app/javascript/src/Policies/store/configureStore.jsx
  app/javascript/src/Policies/types/Actions.jsx
  app/javascript/src/Policies/types/Policies.jsx
  app/javascript/src/Policies/types/State.jsx
  app/javascript/src/Policies/types/index.jsx
  app/javascript/src/Policies/util.jsx
  app/javascript/src/Types/libs/libdefs.js
Labels: javascript

#1393 Don't display backends in master account
  app/lib/logic/rolling_updates.rb
Labels: APIAP

#1385 Nullify api_backend when APIAP routing policy is used
  app/services/apicast_v2_deployment_service.rb
  test/unit/services/apicast_v2_deployment_service_test.rb
Labels: APIAP

#1394 Prevent trailing slash in patterns of proxy rules of backend api configs with a path
  app/decorators/proxy_rule_decorator.rb
  test/decorators/proxy_rule_decorator_test.rb
Labels: APIAP

#1401 APIAP check returns false in the Wizard
  app/controllers/provider/admin/onboarding/wizard/base_controller.rb
Labels: APIAP

#1405 Revert Prevent trailing slash in patterns of proxy rules of backend api configs with a path
  app/decorators/proxy_rule_decorator.rb
  test/decorators/proxy_rule_decorator_test.rb
Labels: APIAP

#1409 Fix Stats::Base metrics
  app/lib/stats/base.rb
  test/unit/stats/base_test.rb
Labels: APIAP

#1310 [CircleCI] Do not run nightly 2.4 tests twice
  .circleci/config.yml
Labels: Priority: High

#1410 Simplify policy lists header and its styles
  app/javascript/src/Policies/components/HeaderButton.jsx
  app/javascript/src/Policies/components/PoliciesForm.jsx
  app/javascript/src/Policies/components/PolicyChain.jsx
  app/javascript/src/Policies/components/PolicyRegistry.jsx
  app/javascript/src/Policies/styles/policies.scss
  spec/javascripts/Policies/components/HeaderButton.spec.jsx
  spec/javascripts/Policies/components/PolicyConfig.spec.jsx
  spec/javascripts/Policies/components/PolicyRegistry.spec.jsx
  spec/javascripts/Policies/components/__snapshots__/HeaderButton.spec.jsx.snap
Labels: javascript

#1386 Segment REST + Bugfix of number of requests
  app/events/users/user_deleted_event.rb
  app/lib/event_store/repository.rb
  app/models/deleted_object.rb
  app/models/user.rb
  app/services/segment/authenticator_service.rb
  app/services/segment/delete_user_service.rb
  app/services/segment/delete_users_service.rb
  app/services/segment/gbpr_api_request.rb
  app/subscribers/user_event_subscriber.rb
  app/workers/segment_delete_user_worker.rb
  app/workers/segment_delete_users_worker.rb
  config/examples/features.yml
  config/jobs.rb
  lib/tasks/segment/segment.rake
  test/events/users/user_deleted_event_test.rb
  test/subscribers/user_event_subscriber_test.rb
  test/unit/deleted_object_test.rb
  test/unit/services/segment/authenticator_service_test.rb
  test/unit/services/segment/delete_user_service_test.rb
  test/unit/services/segment/delete_users_service_test.rb
  test/unit/tasks/segment/segment_test.rb
  test/unit/user_test.rb
  test/workers/segment_delete_user_worker_test.rb
  test/workers/segment_delete_users_worker_test.rb
Labels: bug, enhancement, ruby

#1434 Enable Policies update button after rearranging chain
  app/javascript/src/Policies/util.jsx
  spec/javascripts/Policies/util.spec.jsx
Labels: javascript

#1419 Redefine Policies types
  app/javascript/src/Policies/actions/PolicyChain.jsx
  app/javascript/src/Policies/actions/PolicyConfig.jsx
  app/javascript/src/Policies/actions/index.jsx
  app/javascript/src/Policies/components/PoliciesWidget.jsx
  app/javascript/src/Policies/components/PolicyTile.jsx
  app/javascript/src/Policies/index.jsx
  app/javascript/src/Policies/middleware/PolicyChain.jsx
  app/javascript/src/Policies/reducers/OriginalPolicyChain.jsx
  app/javascript/src/Policies/reducers/PolicyChain.jsx
  app/javascript/src/Policies/reducers/PolicyConfig.jsx
  app/javascript/src/Policies/reducers/PolicyRegistry.jsx
  app/javascript/src/Policies/reducers/initialState.jsx
  app/javascript/src/Policies/types/Actions.jsx
  app/javascript/src/Policies/types/Policies.jsx
  app/javascript/src/Policies/types/State.jsx
  app/javascript/src/Policies/util.jsx
  spec/javascripts/Policies/components/PolicyChainHiddenInput.spec.jsx
  spec/javascripts/Policies/middleware/PolicyChain.spec.jsx
  spec/javascripts/Policies/reducers/PolicyChain.spec.jsx
  spec/javascripts/Policies/reducers/PolicyConfig.spec.jsx
  spec/javascripts/Policies/reducers/PolicyRegistry.spec.jsx
  spec/javascripts/Policies/reducers/UISettings.spec.jsx
Labels: javascript

#1438 Policies/parse registry in rails
  app/controllers/api/integrations_controller.rb
  app/controllers/api/policies_controller.rb
  app/javascript/src/Policies/actions/PolicyRegistry.jsx
  app/javascript/src/Policies/actions/index.jsx
  app/javascript/src/Policies/index.jsx
  app/javascript/src/Policies/reducers/PolicyRegistry.jsx
  app/javascript/src/Policies/types/Actions.jsx
  app/javascript/src/Policies/types/Policies.jsx
  app/javascript/src/Policies/util.jsx
  app/presenters/policies_list_presenter.rb
  spec/javascripts/Policies/reducers/PolicyRegistry.spec.jsx
  test/integration/api/policies_controller_test.rb
Labels: javascript, ruby

#1315 [settings] New integration settings component
  .flowconfig
  app/javascript/packs/settingsPageStyles.js
  app/javascript/src/Form/FormFieldset.jsx
  app/javascript/src/Form/index.jsx
  app/javascript/src/Settings/components/AuthenticationSettingsFieldset.jsx
  app/javascript/src/Settings/components/Common/FormCollection.jsx
  app/javascript/src/Settings/components/Common/RadioFieldset.jsx
  app/javascript/src/Settings/components/Common/SelectGroup.jsx
  app/javascript/src/Settings/components/Common/TextInputGroup.jsx
  app/javascript/src/Settings/components/Common/TypeItemCombo.jsx
  app/javascript/src/Settings/components/Common/index.jsx
  app/javascript/src/Settings/components/Form.jsx
  app/javascript/src/Settings/components/OidcFieldset.jsx
  app/javascript/src/Settings/defaults.jsx
  app/javascript/src/Settings/index.jsx
  app/javascript/src/Settings/types/index.jsx
  app/javascript/src/patternflyStyles/settingsPage.css
  app/views/layouts/provider.html.slim
  spec/javascripts/Form/FormFieldset.spec.jsx
  spec/javascripts/Form/__snapshots__/FormFieldset.spec.jsx.snap
  spec/javascripts/Settings/components/AuthenticationSettingsFieldset.spec.jsx
  spec/javascripts/Settings/components/Common/FormCollection.spec.jsx
  spec/javascripts/Settings/components/Common/RadioFieldset.spec.jsx
  spec/javascripts/Settings/components/Common/SelectGroup.spec.jsx
  spec/javascripts/Settings/components/Common/TextInputGroup.spec.jsx
  spec/javascripts/Settings/components/Common/TypeItemCombo.spec.jsx
  spec/javascripts/Settings/components/Common/__snapshots__/FormCollection.spec.jsx.snap
  spec/javascripts/Settings/components/Common/__snapshots__/RadioFieldset.spec.jsx.snap
  spec/javascripts/Settings/components/Common/__snapshots__/SelectGroup.spec.jsx.snap
  spec/javascripts/Settings/components/Common/__snapshots__/TextInputGroup.spec.jsx.snap
  spec/javascripts/Settings/components/Common/__snapshots__/TypeItemCombo.spec.jsx.snap
  spec/javascripts/Settings/components/Form.spec.jsx
  spec/javascripts/Settings/components/OidcFieldset.spec.jsx
  spec/javascripts/Settings/components/__snapshots__/AuthenticationSettingsFieldset.spec.jsx.snap
  spec/javascripts/Settings/components/__snapshots__/Form.spec.jsx.snap
  spec/javascripts/Settings/components/__snapshots__/OidcFieldset.spec.jsx.snap
Labels: APIAP, enhancement

#1459 Fix BackendApiConfig issuing ProxyConfigs::AffectingObjectChangedEvent on proxy update
  app/lib/proxy_config_affecting_changes.rb
  test/models/backend_api_config_test.rb
Labels: APIAP

#1460 Fix invisible policy when re-ordering Policy Chain
  app/javascript/src/Policies/components/PolicyChain.jsx
  app/javascript/src/Policies/styles/policies.scss
Labels: javascript

#1457 Refactor redux actions in Policies widget
  app/javascript/src/Policies/actions/ThunkActions.jsx
  app/javascript/src/Policies/actions/UISettings.jsx
  app/javascript/src/Policies/actions/index.jsx
  app/javascript/src/Policies/components/PoliciesWidget.jsx
  app/javascript/src/Policies/index.jsx
  app/javascript/src/Policies/types/Actions.jsx
Labels: javascript

#1462 Remove Airbrake from codebase
  .rubocop_todo.yml
  Capfile
  app/controllers/frontend_controller.rb
  app/lib/api_support/params.rb
  app/lib/backend_client/request.rb
  app/lib/system/error_reporting.rb
  app/lib/three_scale/message_bus_config.rb
  app/lib/three_scale/warnings.rb
  app/mailers/post_office.rb
  app/models/finance/billing_strategy.rb
  app/views/layouts/error.html.erb
  app/workers/web_hook_worker.rb
  config/docker/settings.yml
  config/examples/settings.yml
  config/initializers/airbrake.rb
  features/old/proxy.feature
  features/old/services/subscriptions/provider.feature
  features/support/capybara.rb
  gemfiles/prod/Gemfile
  gemfiles/prod/Gemfile.lock
  lib/developer_portal/app/controllers/developer_portal/signup_controller.rb
  lib/developer_portal/lib/liquid/drops/deprecated.rb
  lib/exception_reporting.rb
  lib/tasks/airbrake_tasks.rake
  public/404.html
  public/500.html
  public/502.html
  test/functional/api/plans_controller_test.rb
  test/functional/api/services_controller_test.rb
  test/integration/provider/admin/referrer_filters_controller_test.rb
  test/integration/provider_account_test.rb
  test/integration/user-management-api/messages_test.rb
  test/integration/user-management-api/signup_test.rb
  test/unit/cms/section_test.rb
  test/unit/exception_reporting_test.rb
  test/unit/finance/billing_strategy_test.rb
  test/unit/pdf/data_test.rb
  test/unit/service_plan_test.rb
  test/unit/settings_test.rb
  test/unit/three_scale/warnings_test.rb
Labels: ruby
