Repository 3scale/porta, pull requests merged in 2019-12, with the labels that each got.

#1463 Cleanup and refactor Policies
  app/javascript/src/Policies/components/PolicyChain.jsx
  app/javascript/src/Policies/components/PolicyConfig.jsx
  app/javascript/src/Policies/components/PolicyRegistry.jsx
  app/javascript/src/Policies/components/PolicyTile.jsx
  app/javascript/src/Policies/components/util.jsx
  app/javascript/src/Policies/middleware/PolicyChain.jsx
  app/javascript/src/Policies/reducers/OriginalPolicyChain.jsx
  app/javascript/src/Policies/reducers/PolicyChain.jsx
  app/javascript/src/Policies/reducers/PolicyRegistry.jsx
  app/javascript/src/Policies/reducers/UISettings.jsx
  app/javascript/src/Policies/styles/policies.scss
  app/javascript/src/Policies/util.jsx
  app/javascript/src/utilities/json-utils.jsx
  spec/javascripts/Policies/components/PolicyChain.spec.jsx
  spec/javascripts/Policies/components/PolicyConfig.spec.jsx
  spec/javascripts/Policies/components/PolicyRegistry.spec.jsx
  spec/javascripts/Policies/middleware/PolicyChain.spec.jsx
  spec/javascripts/Policies/reducers/PolicyChain.spec.jsx
  spec/javascripts/Policies/reducers/PolicyConfig.spec.jsx
  spec/javascripts/Policies/util.spec.jsx
Labels: javascript

#1469 Rename proxy deployment service to v1
  app/models/proxy.rb
  app/services/proxy_deployment_v1_service.rb
  app/workers/proxy_deployment_worker.rb
  test/functional/provider/admin/onboarding/wizard/request_controller_test.rb
  test/unit/proxy_test.rb
  test/unit/services/proxy_deployment_v1_service_test.rb
Labels: ruby

#1474 [Refactor] Use require for CSV instead of require_dependency
  app/lib/stats/views/csv/top_applications.rb
  app/lib/stats/views/csv/usage.rb
  app/workers/data_exports_worker.rb
  lib/tasks/provider_stats.rb
  lib/tasks/segment/segment.rake
Labels: cleanup, ruby

#1435 Move all pdf generation to 'app'
  app/lib/pdf/data.rb
  app/lib/pdf/dispatch.rb
  app/lib/pdf/finance/invoice_attachment.rb
  app/lib/pdf/finance/invoice_generator.rb
  app/lib/pdf/finance/invoice_report_data.rb
  app/lib/pdf/fonts/arial.ttf
  app/lib/pdf/format.rb
  app/lib/pdf/images/logo.png
  app/lib/pdf/printer.rb
  app/lib/pdf/report.rb
  app/lib/pdf/styles/base.rb
  app/lib/pdf/styles/black_and_white.rb
  app/lib/pdf/styles/colored.rb
  lib/pdf/images/logo.png
  lib/pdf/styles/black_and_white.rb
  test/unit/pdf/finance/invoice_generator_test.rb
Labels: cleanup, ruby

#1476 Move menu system
  app/lib/menu_system.rb
Labels: cleanup, ruby

#1478 [lib] Move lib/error_handling.rb to app/controllers/concerns
  app/controllers/concerns/error_handling.rb
Labels: cleanup, ruby

#1477 Remove lib/color.rb
  Gemfile.base
  Gemfile.lock
  features/support/hooks.rb
  lib/color.rb
Labels: cleanup, ruby

#1442 Move lib/liquid to app/lib
  app/lib/liquid/template_support.rb
Labels: cleanup, ruby

#1479 Move lib/numeric_hacks to app/lib
  app/lib/numeric_hacks.rb
Labels: cleanup, ruby

#1480 Move lib/filters to app/lib
  app/lib/filters/provider_required.rb
Labels: cleanup, ruby

#1482 [lib] Move lib/active_merchant_hacks to app/lib
  app/lib/active_merchant_hacks.rb
Labels: cleanup, ruby

#1481 [lib] Move lib/time_zone_hacks to app/lib
  app/lib/time_zone_hacks.rb
Labels: cleanup, ruby

#1428 Remove Heroku integration from code
  app/assets/stylesheets/provider/heroku.css
  app/assets/stylesheets/provider/themes/main.scss
  app/controllers/admin/api/heroku_proxy_controller.rb
  app/controllers/heroku/base_controller.rb
  app/controllers/heroku/resources_controller.rb
  app/controllers/heroku/sessions_controller.rb
  app/controllers/master/api/providers_controller.rb
  app/mailers/go_live_notification.rb
  app/models/account.rb
  app/models/partner.rb
  app/models/settings.rb
  app/presenters/provider/admin/accounts_show_presenter.rb
  app/presenters/provider/sessions_presenter.rb
  app/views/admin/upgrade_notices/feature_not_available.html.erb
  app/views/go_live_notification/notice.text.erb
  app/views/provider/admin/accounts/show.html.slim
  app/views/provider/admin/go_live_states/show.js.slim
  app/workers/heroku_worker.rb
  config/heroku-addon.yml
  config/locales/en.yml
  config/routes.rb
  features/step_definitions/go_live_state_steps.rb
  lib/heroku.rb
  test/functional/heroku/resources_controller_test.rb
  test/functional/heroku/sessions_controller_test.rb
  test/integration/admin/api/heroku_proxy_controller_test.rb
  test/test_helpers/heroku.rb
  test/unit/abilities/provider_admin_test.rb
  test/unit/heroku_test.rb
  test/unit/mailers/go_live_notification_test.rb
  test/unit/partner_test.rb
  test/unit/user/signup_type_test.rb
  test/workers/heroku_worker_test.rb
Labels: cleanup, ruby

#1468 Moving assets from CDN's to our codebase in developer portal
  cdn/font-awesome/4.3.0/css/font-awesome.css
  cdn/font-awesome/4.3.0/css/font-awesome.css.map
  cdn/font-awesome/4.3.0/css/font-awesome.min.css
  cdn/font-awesome/4.3.0/fonts/FontAwesome.otf
  cdn/font-awesome/4.3.0/fonts/fontawesome-webfont.eot
  cdn/font-awesome/4.3.0/fonts/fontawesome-webfont.svg
  cdn/font-awesome/4.3.0/fonts/fontawesome-webfont.ttf
  cdn/font-awesome/4.3.0/fonts/fontawesome-webfont.woff
  cdn/font-awesome/4.3.0/fonts/fontawesome-webfont.woff2
  cdn/jquery-ui/1.11.4/images/ui-bg_diagonals-thick_18_b81900_40x40.png
  cdn/jquery-ui/1.11.4/images/ui-bg_diagonals-thick_20_666666_40x40.png
  cdn/jquery-ui/1.11.4/images/ui-bg_flat_10_000000_40x100.png
  cdn/jquery-ui/1.11.4/images/ui-bg_glass_100_f6f6f6_1x400.png
  cdn/jquery-ui/1.11.4/images/ui-bg_glass_100_fdf5ce_1x400.png
  cdn/jquery-ui/1.11.4/images/ui-bg_glass_65_ffffff_1x400.png
  cdn/jquery-ui/1.11.4/images/ui-bg_gloss-wave_35_f6a828_500x100.png
  cdn/jquery-ui/1.11.4/images/ui-bg_highlight-soft_100_eeeeee_1x100.png
  cdn/jquery-ui/1.11.4/images/ui-bg_highlight-soft_75_ffe45c_1x100.png
  cdn/jquery-ui/1.11.4/images/ui-icons_222222_256x240.png
  cdn/jquery-ui/1.11.4/images/ui-icons_228ef1_256x240.png
  cdn/jquery-ui/1.11.4/images/ui-icons_ef8c08_256x240.png
  cdn/jquery-ui/1.11.4/images/ui-icons_ffd27a_256x240.png
  cdn/jquery-ui/1.11.4/images/ui-icons_ffffff_256x240.png
  cdn/jquery-ui/1.11.4/jquery-ui.css
  cdn/jquery-ui/1.11.4/jquery-ui.min.js
  cdn/jquery/1.7.1/jquery.min.js
  doc/liquid/tags.md
  lib/developer_portal/app/assets/stylesheets/plans_widget.scss
  lib/developer_portal/app/views/developer_portal/css/bootstrap.css.old
  lib/developer_portal/app/views/developer_portal/main_layout.html.liquid
  lib/developer_portal/app/views/developer_portal/stats/_chart.html.liquid
  lib/developer_portal/app/views/developer_portal/stats/_selector_widgets.html.liquid
  lib/developer_portal/lib/liquid/tags/cdn_asset.rb
Labels: cleanup

#1483 [lib] Remove lib/range_hacks
  config/initializers/range_hacks.rb
  lib/range_hacks.rb
  test/unit/range_hacks_test.rb
Labels: cleanup, ruby

#1493 Add tests for deployment settings
  features/api/services/settings.feature
  features/step_definitions/settings_steps.rb
Labels: ruby

#1486 [lib] Move lib/layoutless_ajax_rendering to app/lib
  app/lib/layoutless_ajax_rendering.rb
Labels: cleanup, ruby

#1503 Move lib/provider_requirements into app/lib
  app/lib/provider_requirements.rb
Labels: cleanup, ruby

#1502 Move lib/pagination_helper into app/lib
  app/lib/pagination_helper.rb
Labels: cleanup, ruby

#1501 Move lib/normalize_path_attribute into app/lib
  app/lib/normalize_path_attribute.rb
Labels: cleanup, ruby

#1506 Move lib/redhat_customer_portal_support into app/lib
  app/lib/redhat_customer_portal_support.rb
Labels: cleanup, ruby

#1507 Move lib/search_support into app/lib
  app/lib/search_support.rb
Labels: cleanup, ruby

#1512 Remove permission_system
  lib/permission_system.rb
Labels: cleanup, ruby

#1510 Move lib/web_hooks_helper into app/lib
  app/lib/web_hooks_helpers.rb
Labels: cleanup, ruby

#1508 Move lib/system_name into app/lib
  app/lib/system_name.rb
  lib/system_name.rb
Labels: cleanup, ruby

#1511 Move lib/previously_changed into app/lib
  app/lib/previously_changed.rb
Labels: cleanup, ruby

#1509 Move unrequired files from lib/three_scale into app/lib
  app/lib/three_scale/filter_arguments.rb
  app/lib/three_scale/rake/remove_dup_usage_limits.rb
Labels: cleanup, ruby

#1498 Replace our sidekiq log for sidekiq throttled
  Gemfile.base
  Gemfile.lock
  app/lib/backend/model_extensions/metric.rb
  app/workers/backend_metric_worker.rb
  config/initializers/sidekiq.rb
  gemfiles/prod/Gemfile.lock
  lib/three_scale/sidekiq_lock_worker.rb
  test/unit/backend/model_extensions/metric_test.rb
  test/workers/backend_metric_worker_test.rb
Labels: enhancement, ruby
