Repository 3scale/porta, pull requests merged in 2019-01, with the labels that each got.

#469 [gem] Update newrelic_rpm gem to 5.6
  gemfiles/prod/Gemfile
  gemfiles/prod/Gemfile.lock
Labels: dependencies, ruby

#459 Fixes in package.json: repo and license
  package.json
Labels: jenkins

#383 [db] Allow up to 2MB for proxy_configs content
  app/models/proxy_config.rb
  db/migrate/20181205131457_extend_proxy_content_size.rb
  db/schema.rb
  test/unit/proxy_config_test.rb
Labels: oracle

#479 Replace audited-activerecord by audited
  Gemfile.base
  Gemfile.lock
  app/models/contract.rb
  config/initializers/audited_hacks.rb
  config/jobs.rb
  gemfiles/prod/Gemfile.lock
  lib/tasks/audit_logs.rake
  test/unit/logic/provider_upgrade_test.rb
  test/unit/validate_model_validations_test.rb
Labels: dependencies, ruby

#471 Upgrade jquery-rails to 4.3.1
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
  test/mailers/notification_mailer_test.rb
Labels: dependencies, ruby

#484 [rails-5.0] Update dotenv-rails
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: dependencies, ruby

#485 [rails-5.0] Update state_machines
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: dependencies, ruby

#486 Quieting natively in 4.2
  Gemfile.base
  Gemfile.lock
  config/application.rb
  gemfiles/prod/Gemfile.lock
Labels: dependencies, ruby

#488 Update non-stupid-digest-assets
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: dependencies, ruby

#435 Removes Babel duplication in Webpack configs
  .babelrc
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/test.js
Labels: jenkins

#454 Applies a workaround to fix package-lock.json generation
  .gitignore
  package-lock.json
  package.json
Labels: jenkins

#460 Better Flow support for React files
  .circleci/config.yml
  .flowconfig
  .gitignore
  app/javascript/src/Dashboard/components/ApiFilter.jsx
  app/javascript/src/Navigation/components/ActiveMenuTitle.jsx
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/javascript/src/Policies/actions/PolicyConfig.jsx
  app/javascript/src/Policies/actions/PolicyRegistry.jsx
  app/javascript/src/Policies/actions/index.jsx
  app/javascript/src/Policies/components/App.jsx
  app/javascript/src/Policies/components/PoliciesForm.jsx
  app/javascript/src/Policies/components/PoliciesWidget.jsx
  app/javascript/src/Policies/components/PolicyConfig.jsx
  app/javascript/src/Policies/components/Root.jsx
  app/javascript/src/Policies/index.jsx
  app/javascript/src/Policies/reducers/PolicyChain.jsx
  app/javascript/src/Policies/reducers/PolicyConfig.jsx
  app/javascript/src/Policies/reducers/PolicyRegistry.jsx
  app/javascript/src/Policies/reducers/UISettings.jsx
  app/javascript/src/Policies/reducers/index.jsx
  app/javascript/src/Policies/reducers/util.jsx
  app/javascript/src/Policies/store/configureStore.jsx
  app/javascript/src/Policies/types/Policies.jsx
  app/javascript/src/Policies/types/index.jsx
  app/javascript/src/Stats/inlinechart/index.jsx
  app/javascript/src/Types/Api.jsx
  app/javascript/src/Types/NavigationTypes.jsx
  app/javascript/src/Types/ReactWrapper.jsx
  app/javascript/src/Types/Service.jsx
  app/javascript/src/Types/index.js
  app/javascript/src/Types/libs/libdefs.js
  app/javascript/src/services/index.jsx
  app/javascript/src/services/migrate.jsx
  app/javascript/src/utilities/toggle.jsx
  package-lock.json
  package.json
  spec/javascripts/Policies/components/PolicyConfig.spec.jsx
Labels: jenkins
