Repository 3scale/porta, pull requests merged in 2019-08, with the labels that each got.

#1046 :bug: Hides radio buttons when Service Discovery not accesible
  app/javascript/src/NewService/components/NewServiceForm.jsx
  app/views/api/services/new.html.slim
  spec/javascripts/NewService/NewServiceForm.spec.jsx
Labels: Priority: Blocker, javascript

#680 Fix warning in eslint
  app/javascript/src/Types/libs/libdefs.js
  package.json
Labels: Priority: Low, javascript

#1060 Remove comment about proxy association in Service Factory
  test/factories/other.rb
Labels: Priority: Low

#1052 [apiap] Polymorphic owner for ProxyRule
  app/models/backend_api.rb
  app/models/proxy_rule.rb
  db/migrate/20190801143026_add_owner_to_proxy_rules.rb
  db/migrate/20190801143259_backfill_proxy_rules_owners.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
  test/unit/proxy_rule_test.rb
Labels: APIAP

#1071 Remove all Jenkins-related code
  Makefile
  features/support/launchy.rb
  script/docker_bash
  script/jenkins.sh
  test/test_helper.rb
Labels: Priority: Low, enhancement, good first issue

#1053 [apiap] Polymorphic owner for Metric
  app/lib/backend/model_extensions/metric.rb
  app/models/backend_api.rb
  app/models/metric.rb
  db/migrate/20190805135730_add_owner_to_metrics.rb
  db/migrate/20190805135829_backfill_metric_owners.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
  test/unit/backend/model_extensions/metric_test.rb
  test/unit/metric_test.rb
Labels: APIAP

#1078 [Migrate] Service with field to act as product
  db/migrate/20190731092006_add_acts_as_product_to_service.rb
  db/migrate/20190731092338_backfill_add_acts_as_product_to_service.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
Labels: APIAP

#1068 API Service Update/Create with Strong Params
  app/controllers/admin/api/services_controller.rb
  app/controllers/master/api/base_controller.rb
  test/integration/admin/api/services_controller_test.rb
  test/integration/user-management-api/services_test.rb
Labels: Priority: Blocker, ruby, security

#1008 [apiap] UI base
  app/assets/javascripts/mapping_rules.js
  app/assets/javascripts/provider/admin/apiconfig/services/integration.js.coffee
  app/assets/stylesheets/provider/_services.scss
  app/assets/stylesheets/provider/_tables.scss
  app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
  app/controllers/api/integrations_controller.rb
  app/controllers/provider/admin/backend_apis/base_controller.rb
  app/controllers/provider/admin/backend_apis/mapping_rules_controller.rb
  app/controllers/provider/admin/backend_apis/metrics_controller.rb
  app/controllers/provider/admin/backend_apis_controller.rb
  app/helpers/api/integrations_helper.rb
  app/helpers/vertical_nav_helper.rb
  app/lib/backend_api_logic/proxy_extension.rb
  app/lib/backend_api_logic/service_extension.rb
  app/models/account/provider_methods.rb
  app/models/backend_api.rb
  app/models/backend_api_config.rb
  app/models/proxy_rule.rb
  app/models/service.rb
  app/views/api/application_plans/edit.html.erb
  app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
  app/views/api/integrations/apicast/script_driven/_staging.html.slim
  app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
  app/views/api/metrics/_backend_api.erb
  app/views/api/metrics/_top_level.html.erb
  app/views/api/plans/_metrics.html.erb
  app/views/api/services/show.html.slim
  app/views/provider/admin/backend_apis/index.html.slim
  app/views/provider/admin/backend_apis/mapping_rules/index.html.slim
  app/views/provider/admin/backend_apis/metrics/_form.html.slim
  app/views/provider/admin/backend_apis/metrics/_link_to_mapping_rules.slim
  app/views/provider/admin/backend_apis/metrics/index.html.slim
  app/views/provider/admin/backend_apis/show.html.slim
  app/views/shared/provider/navigation/service/_integration.html.slim
  config/abilities/provider_admin.rb
  config/routes.rb
  features/old/menu/api_menu.feature
  features/old/menu/backend_api_menu.feature
  features/step_definitions/service_steps.rb
  features/support/paths.rb
  test/factories/backend_api.rb
  test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb
  test/integration/provider/admin/backend_apis/metrics_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/test_helpers/rolling_updates.rb
Labels: APIAP

#1072 Share logic between the 2 pages to manage Mapping Rules
  app/controllers/api/proxy_rules_controller.rb
  app/controllers/provider/admin/backend_apis/mapping_rules_controller.rb
  app/controllers/proxy_rule_shared_controller.rb
  app/helpers/proxy_rules_helper.rb
  app/views/api/proxy_rules/edit.html.slim
  app/views/api/proxy_rules/index.html.slim
  app/views/api/proxy_rules/new.html.slim
  app/views/provider/admin/backend_apis/mapping_rules/edit.html.slim
  app/views/provider/admin/backend_apis/mapping_rules/index.html.slim
  app/views/provider/admin/backend_apis/mapping_rules/new.html.slim
  app/views/shared/proxy_rules/_form.html.slim
  app/views/shared/proxy_rules/_table.html.slim
  config/routes.rb
  test/helpers/proxy_rules_helper_test.rb
Labels: APIAP

#1015 Improve Service Discovery Errors (AKA improve New API form)
  .flowconfig
  app/assets/stylesheets/provider/_forms.scss
  app/controllers/provider/admin/service_discovery/cluster_projects_controller.rb
  app/controllers/provider/admin/service_discovery/cluster_services_controller.rb
  app/javascript/src/NewService/components/FormElements/ErrorMessage.jsx
  app/javascript/src/NewService/components/FormElements/Select.jsx
  app/javascript/src/NewService/components/FormElements/ServiceDiscoveryListItems.jsx
  app/javascript/src/NewService/components/FormElements/index.jsx
  app/javascript/src/NewService/components/NewServiceForm.jsx
  app/javascript/src/NewService/components/ServiceDiscoveryForm.jsx
  app/javascript/src/NewService/components/ServiceSourceForm.jsx
  app/javascript/src/NewService/index.jsx
  app/javascript/src/Types/libs/libdefs.js
  app/javascript/src/utilities/utils.js
  app/views/api/services/new.html.slim
  spec/javascripts/NewService/NewServiceForm.spec.jsx
  spec/javascripts/NewService/ServiceDiscoveryForm.spec.jsx
  spec/javascripts/NewService/ServiceManualForm.spec.jsx
  spec/javascripts/NewService/ServiceSourceForm.spec.jsx
  spec/javascripts/NewService/formElements/FormWrapper.spec.jsx
  spec/javascripts/NewService/formElements/Select.spec.jsx
  spec/javascripts/NewService/formElements/ServiceDiscoveryListItems.spec.jsx
  spec/javascripts/NewService/formElements/ServiceManualListItems.spec.jsx
  spec/javascripts/Policies/components/PolicyList.spec.jsx
Labels: Priority: High, javascript

#1077 Apiap context selector
  app/decorators/application_decorator.rb
  app/decorators/backend_api_decorator.rb
  app/decorators/service_decorator.rb
  app/helpers/menu_helper.rb
  app/javascript/src/Dashboard/components/ApiFilter.jsx
  app/javascript/src/Navigation/components/ActiveMenuTitle.jsx
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/javascript/src/Types/Api.jsx
  app/javascript/src/Types/NavigationTypes.jsx
  app/javascript/src/Types/Service.jsx
  app/javascript/src/Types/index.js
  app/javascript/src/Users/components/PermissionsForm.jsx
  app/javascript/src/Users/components/ServicesFieldset.jsx
  app/views/shared/_api_selector.html.slim
  spec/javascripts/Dashboard/ApiFilter.spec.jsx
  spec/javascripts/Navigation/ActiveMenuTitle.spec.jsx
  spec/javascripts/Navigation/ContextSelector.spec.jsx
Labels: APIAP

#1058 Dashboard for APIAP
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/helpers/provider/admin/dashboards_helper.rb
  app/javascript/packs/api_as_product.js
  app/javascript/packs/dashboard.js
  app/javascript/src/Dashboard/components/ApiFilter.jsx
  app/javascript/src/Dashboard/tabs-widget.jsx
  app/views/provider/admin/dashboards/_apiap_navigation.html.slim
  app/views/provider/admin/dashboards/_apiap_search_bar.html.slim
  app/views/provider/admin/dashboards/_list_backends.html.slim
  app/views/provider/admin/dashboards/_new_api_button.html.slim
  app/views/provider/admin/dashboards/_section_products_and_backends.html.slim
  app/views/provider/admin/dashboards/_section_services.html.slim
  app/views/provider/admin/dashboards/_services_filter.html.slim
  app/views/provider/admin/dashboards/show.html.slim
  app/views/shared/_service_access.slim
  features/old/menu/dashboard.feature
  features/old/services/multiservice.feature
  features/old/services/switch.feature
  spec/javascripts/Dashboard/ApiFilter.spec.jsx
Labels: APIAP, Priority: High

#1111 Fixes API search in non-APIAP dashboards
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/javascript/packs/services_search_bar.js
  app/views/provider/admin/dashboards/_services_filter.html.slim
Labels: APIAP, Priority: Blocker

#1096 [apiap] Backend API edit page
  app/controllers/provider/admin/backend_apis_controller.rb
  app/views/provider/admin/backend_apis/edit.html.slim
  app/views/provider/admin/backend_apis/forms/_delete.html.slim
  app/views/provider/admin/backend_apis/forms/_naming.html.slim
  config/abilities/provider_admin.rb
  config/locales/en.yml
  test/integration/provider/admin/backend_apis_controller_test.rb
Labels: APIAP

#1107 Fixes used backends list at Service overview
  app/assets/stylesheets/provider/_services.scss
Labels: APIAP

#1108 List all backend API endpoints inside the APIcast config
  app/assets/stylesheets/provider/_commons.scss
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
Labels: APIAP

#1121 [Do Not Merge] Fixes Metrics table header in Application Plan page
  app/assets/stylesheets/provider/_commons.scss
  app/assets/stylesheets/provider/_metrics.scss
  app/javascript/packs/plans-metrics.js
  app/views/api/metrics/_backend_api.erb
  app/views/api/plans/_metrics.html.erb
Labels: APIAP

#1114 Remove associations from BackendApiConfig
  app/models/backend_api_config.rb
Labels: APIAP

#1125 HOTFIX reverts rogue commits
  app/assets/stylesheets/provider/_commons.scss
  app/assets/stylesheets/provider/_metrics.scss
  app/javascript/packs/plans-metrics.js
  app/views/api/metrics/_backend_api.erb
  app/views/api/plans/_metrics.html.erb
Labels: APIAP

#1113 Application Plan "Methods & Metrics" collapsible table
  app/assets/stylesheets/provider/_metrics.scss
  app/javascript/packs/plans-metrics.js
  app/views/api/metrics/_backend_api.erb
  app/views/api/plans/_metrics.html.erb
Labels: APIAP

#1126 New page for Backend APIs
  app/controllers/provider/admin/backend_apis_controller.rb
  app/views/provider/admin/backend_apis/new.html.slim
  test/integration/provider/admin/backend_apis_controller_test.rb
Labels: APIAP

#1128 Fixes index view '/backend_apis'
  app/controllers/provider/admin/backend_apis_controller.rb
Labels: APIAP

#1129 Fixes styles for "Metrics" tables
  app/assets/stylesheets/provider/_metrics.scss
Labels: APIAP

#1119 Add an option to mark that the Service acts as product
  app/controllers/api/services_controller.rb
  app/javascript/src/NewService/components/FormElements/BackendApiSelect.jsx
  app/javascript/src/NewService/components/FormElements/index.jsx
  app/javascript/src/NewService/components/NewServiceForm.jsx
  app/javascript/src/NewService/components/ServiceManualForm.jsx
  app/models/backend_api_config.rb
  app/views/api/services/new.html.slim
  spec/javascripts/NewService/NewServiceForm.spec.jsx
  spec/javascripts/NewService/formElements/BackendApiSelect.spec.jsx
  test/integration/api/services_controller_test.rb
Labels: APIAP

#1132 List products used by backend and disable delete link
  app/assets/stylesheets/provider/_commons.scss
  app/views/provider/admin/backend_apis/forms/_delete.html.slim
Labels: APIAP

#1135 show methods and metrics for both traditional services and products
  app/helpers/vertical_nav_helper.rb
  features/old/menu/api_menu.feature
Labels: APIAP
