Repository 3scale/porta, pull requests merged in 2019-09, with the labels that each got.

#1141 Fix ApplicationControllerTest: modern browser test do requests before asserting
  test/integration/application_controller_test.rb
Labels: Priority: Low, enhancement, ruby

#1083 [Refactor][Test] Remove redundant test login methods
  test/integration/admin/api/member_permissions_controller_test.rb
  test/integration/master/api/finance/accounts/billing_jobs_controller_test.rb
  test/integration/master/api/finance/billing_jobs_controller_test.rb
  test/integration/payment_gateways/braintree_blue_test.rb
  test/integration/provider/admin/keys_controller_test.rb
  test/integration/sites/settings_controller_test.rb
  test/integration/stats/clients_test.rb
  test/test_helpers/authentication.rb
Labels: Priority: Low, enhancement, ruby

#1142 [Refactor] InviteeSignups redirect if logged in flash message using i18n
  app/controllers/provider/invitee_signups_controller.rb
  config/locales/en.yml
  test/integration/provider/invitee_signups_controller_test.rb
Labels: Priority: Low, enhancement, ruby

#1067 [APIAP][API Endpoints] Set the flag of a service to 'act as product'
  app/controllers/admin/api/services_controller.rb
  test/integration/admin/api/services_controller_test.rb
Labels: APIAP, Priority: High, feature, ruby

#1140 Fixes tab highlighting in IE11
  app/javascript/src/Dashboard/tabs-widget.jsx
Labels: APIAP

#1131 Implements basic deletion of Backend APIs
  app/controllers/provider/admin/backend_apis_controller.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
Labels: APIAP

#1139 Remove white spaces when filtering backends in Safari
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/javascript/src/Dashboard/components/ApiFilter.jsx
Labels: APIAP

#1149 UI BackendAPI Controller allows system_name for create but not for update
  app/controllers/provider/admin/backend_apis_controller.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
Labels: APIAP

#1112 Inject Routing policy for Backend API upstreams (THREESCALE-3311)
  app/lib/backend_api_logic/routing_policy.rb
  app/lib/string_utils/strip_slash.rb
  app/models/backend_api_config.rb
  app/models/proxy.rb
  test/models/backend_api_config_test.rb
  test/unit/proxy_test.rb
Labels: APIAP

#1138 [Apicast::ProxySource] inject backend API proxy rules
  app/decorators/proxy_rule_decorator.rb
  app/models/proxy.rb
  app/services/apicast_v2_deployment_service.rb
  lib/apicast/proxy_rules_source.rb
  lib/apicast/proxy_source.rb
  test/unit/apicast/proxy_rules_source_test.rb
Labels: APIAP

#1103 Backend API metric UI pages
  app/controllers/provider/admin/backend_apis/metrics_controller.rb
  app/lib/backend/model_extensions/metric.rb
  app/lib/backend_api_logic/metric_extension.rb
  app/models/backend_api.rb
  app/models/metric.rb
  app/views/provider/admin/backend_apis/metrics/_form.html.slim
  app/views/provider/admin/backend_apis/metrics/edit.html.erb
  app/views/provider/admin/backend_apis/metrics/index.html.slim
  app/views/provider/admin/backend_apis/metrics/new.html.erb
  test/integration/provider/admin/backend_apis/metrics_controller_test.rb
  test/unit/backend_api_logic/metric_extension_test.rb
  test/unit/metric_test.rb
Labels: APIAP

#1120 Fix links to actions over backend API metrics on app plan page (THREESCALE-3348)
  app/controllers/api/metrics_controller.rb
  app/controllers/api/pricing_rules_controller.rb
  app/controllers/api/usage_limits_controller.rb
  app/lib/backend_api_logic/service_extension.rb
  app/models/application_plan.rb
  app/models/backend_api_config.rb
  app/models/end_user_plan.rb
  app/models/usage_limit.rb
  test/unit/backend_api_logic/service_extension_test.rb
Labels: APIAP

#1130 Removes 'index' of Backend APIs
  app/controllers/provider/admin/backend_apis_controller.rb
  app/views/provider/admin/backend_apis/index.html.slim
  config/routes.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
Labels: APIAP

#1170 Show all methods and metrics of a product in app plan edit page
  app/models/service.rb
  app/views/api/metrics/_backend_api.erb
  app/views/api/metrics/_top_level.html.erb
  app/views/api/plans/_metrics.html.erb
Labels: APIAP

#1050 Include JSX files under Eslint coverage
  app/javascript/src/Policies/types/index.jsx
  package.json
  spec/javascripts/LoginPage/SignupPageWrapper.spec.jsx
  spec/javascripts/Navigation/ContextSelector.spec.jsx
  spec/javascripts/Policies/components/PolicyChain.spec.jsx
  spec/javascripts/Policies/middleware/PolicyChain.spec.jsx
Labels: javascript

#1171 Create default 'hits' metric to backend API
  app/models/backend_api.rb
  test/integration/provider/admin/backend_apis/metrics_controller_test.rb
  test/models/backend_api_test.rb
  test/unit/backend_api_logic/service_extension_test.rb
  test/unit/metric_test.rb
Labels: APIAP

#1156 Remove column act_as_product
  app/controllers/admin/api/services_controller.rb
  app/controllers/api/integrations_controller.rb
  app/controllers/api/services_controller.rb
  app/javascript/src/NewService/components/FormElements/BackendApiSelect.jsx
  app/lib/backend_api_logic/routing_policy.rb
  app/lib/backend_api_logic/service_extension.rb
  app/lib/logic/rolling_updates.rb
  app/models/application_record.rb
  app/models/backend_api_config.rb
  app/models/service.rb
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
  app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
  app/views/api/plans/_metrics.html.erb
  app/views/api/services/show.html.slim
  app/views/shared/provider/navigation/service/_integration.html.slim
  db/migrate/20190731092338_backfill_add_acts_as_product_to_service.rb
  features/old/menu/api_menu.feature
  features/old/proxy.feature
  features/step_definitions/provider_steps.rb
  features/step_definitions/service_steps.rb
  lib/tasks/apiap.rake
  spec/javascripts/NewService/formElements/BackendApiSelect.spec.jsx
  test/integration/admin/api/services_controller_test.rb
  test/integration/api/services_controller_test.rb
  test/unit/proxy_test.rb
Labels: APIAP, Priority: Blocker

#986 Load widgets in Dashboard only when opening a Service
  app/javascript/packs/dashboard.js
  app/javascript/src/Dashboard/ajax-widget.jsx
  app/javascript/src/utilities/toggle.jsx
  app/presenters/dashboard_widget_presenter.rb
  app/views/provider/admin/dashboards/_ajax_load.html.slim
  features/old/accounts/bulk_operations.feature
  features/old/accounts/bulk_operations/change_plans.feature
  features/old/accounts/notifications.feature
  features/old/accounts/service_contracts.feature
  features/old/api/end_user_plans.feature
  features/old/api/metrics/visibility.feature
  features/old/api/plans/customize_application_plan.feature
  features/old/api/settings.feature
  features/old/api/usage_limits.feature
  features/old/applications/buyers/application_management.feature
  features/old/applications/providers/bulk_operations.feature
  features/old/applications/providers/keys.feature
  features/old/applications/providers/referrer_filters.feature
  features/old/cms/advanced/groups_and_sections.feature
  features/old/cms/changes.feature
  features/old/cms/email_templates.feature
  features/old/cms/layouts.feature
  features/old/cms/partials.feature
  features/old/cms/portlets.feature
  features/old/cms/redirects.feature
  features/old/cms/sections.feature
  features/old/dashboards.feature
  features/old/emails.feature
  features/old/liquid/active_docs.feature
  features/old/providers/active_docs.feature
  features/old/services/multiservice.feature
  features/old/services/subscriptions/bulk_operations.feature
  features/old/signup/account_activation_emails.feature
  features/percy/provider.feature
  features/provider/usage_limits/visibility.feature
  features/step_definitions/api/end_user_plan_steps.rb
  features/step_definitions/applications/keys_steps.rb
  features/step_definitions/cms/page_template_steps.rb
  features/step_definitions/confirm_dialog_steps.rb
  features/step_definitions/dashboard_steps.rb
  features/step_definitions/metric_steps.rb
  features/step_definitions/new_cms/changes_steps.rb
  features/step_definitions/notification_steps.rb
  features/step_definitions/percy_steps.rb
  features/step_definitions/plans/account_plans_steps.rb
  features/step_definitions/stats_steps.rb
  features/step_definitions/time_steps.rb
  features/step_definitions/usage_limit_steps.rb
  features/step_definitions/visibility_steps.rb
  features/support/ajax_wait.rb
  features/support/alerts.rb
  features/support/hooks.rb
Labels: Priority: High, javascript

#1180 Remove warnings, errors and improve Jest specs
  app/javascript/src/Policies/components/PoliciesForm.jsx
  app/javascript/src/Stats/inlinechart/index.jsx
  app/javascript/src/utilities/utils.js
  jest.config.js
  spec/javascripts/Dashboard/ApiFilter.spec.jsx
  spec/javascripts/LoginPage/AuthenticationProviders.spec.jsx
  spec/javascripts/LoginPage/FlashMessages.spec.jsx
  spec/javascripts/LoginPage/ForgotCredentials.spec.jsx
  spec/javascripts/LoginPage/FormGroup.spec.jsx
  spec/javascripts/LoginPage/HiddenInputs.spec.jsx
  spec/javascripts/LoginPage/Login3scaleForm.spec.jsx
  spec/javascripts/LoginPage/LoginPageWrapper.spec.jsx
  spec/javascripts/LoginPage/RequestPasswordForm.spec.jsx
  spec/javascripts/LoginPage/SignupForm.spec.jsx
  spec/javascripts/LoginPage/SignupPageWrapper.spec.jsx
  spec/javascripts/Navigation/ActiveMenuTitle.spec.jsx
  spec/javascripts/Navigation/ContextSelector.spec.jsx
  spec/javascripts/NewService/NewServiceForm.spec.jsx
  spec/javascripts/NewService/ServiceDiscoveryForm.spec.jsx
  spec/javascripts/NewService/ServiceManualForm.spec.jsx
  spec/javascripts/NewService/ServiceSourceForm.spec.jsx
  spec/javascripts/NewService/formElements/BackendApiSelect.spec.jsx
  spec/javascripts/NewService/formElements/ErrorMessage.spec.jsx
  spec/javascripts/NewService/formElements/FormWrapper.spec.jsx
  spec/javascripts/NewService/formElements/HiddenServiceDiscoveryInput.spec.jsx
  spec/javascripts/NewService/formElements/Label.spec.jsx
  spec/javascripts/NewService/formElements/Select.spec.jsx
  spec/javascripts/NewService/formElements/ServiceDiscoveryListItems.spec.jsx
  spec/javascripts/NewService/formElements/ServiceManualListItems.spec.jsx
  spec/javascripts/Policies/components/CustomPolicies.spec.jsx
  spec/javascripts/Policies/components/CustomPolicy.spec.jsx
  spec/javascripts/Policies/components/PolicyChain.spec.jsx
  spec/javascripts/Policies/components/PolicyChainHiddenInput.spec.jsx
  spec/javascripts/Policies/components/PolicyConfig.spec.jsx
  spec/javascripts/Policies/components/PolicyList.spec.jsx
  spec/javascripts/Policies/components/PolicyRegistry.spec.jsx
  spec/javascripts/Policies/components/PolicyTile.spec.jsx
  spec/javascripts/Policies/components/SchemaEditor.spec.jsx
  spec/javascripts/Stats/inlinechart/inlineChart.spec.jsx
  spec/javascripts/Users/components/FeaturesFieldset.spec.jsx
  spec/javascripts/Users/components/PermissionsForm.spec.jsx
  spec/javascripts/Users/components/RoleRadioGroup.spec.jsx
  spec/javascripts/Users/components/ServicesFieldset.spec.jsx
  spec/javascripts/__mocks__/c3.js
  spec/javascripts/setupTests.js
  spec/javascripts/utilities/json-utils.spec.jsx
  spec/javascripts/utilities/utils.spec.jsx
Labels: javascript

#1133 Make independent mapping rules always enabled when APIAP is on
  app/controllers/api/proxy_rules_controller.rb
  app/helpers/vertical_nav_helper.rb
  app/models/account.rb
  app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
  app/views/shared/provider/navigation/service/_integration.html.slim
  features/old/menu/api_menu.feature
  test/integration/api/proxy_rules_controller_test.rb
  test/unit/service_test.rb
Labels: APIAP

#1176 Sync backend API 'hits' metrics with apisonator as children of service 'hits'
  app/lib/backend/model_extensions/metric.rb
  app/lib/backend_api_logic/metric_extension.rb
  app/models/metric.rb
  app/workers/backend_metric_worker.rb
  test/unit/backend/model_extensions/metric_test.rb
  test/unit/backend_api_logic/metric_extension_test.rb
  test/unit/metric_test.rb
  test/workers/backend_metric_worker_test.rb
Labels: APIAP

#1186 Fix sync of backend api metrics on create BackendApiConfig
  app/lib/backend/model_extensions/backend_api_config.rb
  app/lib/backend/model_extensions/metric.rb
  app/lib/backend/storage_rewrite.rb
  app/models/backend_api_config.rb
  app/workers/backend_metric_worker.rb
  test/unit/backend/model_extensions/backend_api_config_test.rb
  test/unit/backend/model_extensions/metric_test.rb
  test/workers/backend_metric_worker_test.rb
Labels: APIAP

#1191 Fixes test by making assertion case insensitive
  features/step_definitions/dashboard_steps.rb
Labels: Priority: Blocker

#1194 Fix missing configs in Custom Policies
  package-lock.json
  package.json
Labels: Priority: Blocker

#1193 Fix Backend API mapping rules injected into the proxy config
  app/decorators/proxy_rule_decorator.rb
  test/unit/apicast/proxy_rules_source_test.rb
Labels: APIAP

#1197 Refactor Test ApiDocs only show APIAP with RU enabled (to be dynamic)
  test/integration/api_docs/services_controller_test.rb
Labels: APIAP, Priority: High, enhancement, ruby

#1198 [Refactor] is_a_method? -> method_metric?
  app/models/metric.rb
  app/representers/metric_links_representer.rb
  app/views/api/metrics/toggle_enabled.js.erb
  app/views/api/metrics/toggle_limits_only_text.js.erb
  app/views/api/metrics/toggle_visible.js.erb
Labels: Priority: Low, enhancement, ruby

#1200 Include Rake task to destroy orphans backend apis
  app/models/backend_api.rb
  lib/tasks/backend_api.rake
  test/models/backend_api_test.rb
  test/unit/tasks/backend_api_test.rb
Labels: Priority: High, bug

#1199 Move creation of metric.owner_(id|type) before migration of existing backend APIs
  db/migrate/20190716110000_add_owner_to_metrics.rb
Labels: APIAP

#1184 [API Endpoints] Metrics under Backend API
  app/controllers/admin/api/backend_apis/metrics_controller.rb
  app/controllers/admin/api/metrics_controller.rb
  app/representers/backend_api_representer.rb
  app/representers/metric_links_representer.rb
  app/representers/metric_representer.rb
  config/routes.rb
  doc/active_docs/Account Management API.json
  spec/acceptance/api/backend_api_spec.rb
  test/integration/admin/api/backend_apis/metrics_controller_test.rb
Labels: APIAP, Priority: High, feature, ruby

#1202 Integration Settings as Application Usage Rules
  app/controllers/api/services_controller.rb
  app/helpers/api/services_helper.rb
  app/helpers/vertical_nav_helper.rb
  app/views/api/services/settings.html.slim
  features/old/menu/api_menu.feature
  features/old/services/multiservice.feature
Labels: APIAP

#1190 Improve Tabs in Dashboard
  app/assets/stylesheets/provider/_patternfly_tabs_fake.scss
  app/assets/stylesheets/provider/_theme.scss
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/javascript/src/Dashboard/tabs-widget.jsx
  app/views/provider/admin/dashboards/_apiap_navigation.html.slim
  app/views/provider/admin/dashboards/_section_products_and_backends.html.slim
  features/old/authorization/provider_plans_section.feature
  features/old/menu/dashboard.feature
  features/step_definitions/custom_web_steps.rb
  features/support/selectors.rb
Labels: APIAP

#1201 [API Endpoints] Metric Methods under Backend API
  app/controllers/admin/api/backend_apis/metric_methods_controller.rb
  app/controllers/admin/api/backend_apis/metrics_controller.rb
  app/controllers/admin/api/base_controller.rb
  app/controllers/admin/api/metric_methods_controller.rb
  app/representers/method_representer.rb
  app/representers/metric_links_representer.rb
  config/routes.rb
  doc/active_docs/Account Management API.json
  test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
  test/integration/admin/api/backend_apis/metrics_controller_test.rb
Labels: APIAP, Priority: High, feature, ruby

#1216 Adding Settings subheader to Application menu when APIAP is on
  app/helpers/vertical_nav_helper.rb
Labels: APIAP

#1208 replace_path property in the routing policies injected for backend APIs
  app/lib/backend_api_logic/routing_policy.rb
  test/unit/backend_api_logic/routing_policy_test.rb
  test/unit/proxy_test.rb
Labels: APIAP

#1211 Do not create automatically create backend when creating a product
  app/controllers/admin/api/services_controller.rb
  app/controllers/api/integrations_controller.rb
  app/controllers/api/services_controller.rb
  app/forms/onboarding/request_form.rb
  app/lib/backend_api_logic/proxy_extension.rb
  app/lib/backend_api_logic/service_extension.rb
  app/lib/logic/provider_signup.rb
  app/models/account/provider_methods.rb
  app/models/backend_api.rb
  app/models/proxy.rb
  app/representers/proxy_representer.rb
  app/services/api_classification_service.rb
  app/services/service_creator.rb
  db/seeds.rb
  lib/signup/provider_account_manager.rb
  test/factories/account.rb
  test/factories/simple.rb
  test/functional/api/integrations_controller_test.rb
  test/integration/api/services_controller_test.rb
  test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb
  test/integration/provider/admin/backend_apis/metrics_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/models/backend_api_test.rb
  test/unit/account_test.rb
  test/unit/apicast/provider_nginx_generator_test.rb
  test/unit/backend/model_extensions/metric_test.rb
  test/unit/backend_api_logic/routing_policy_test.rb
  test/unit/backend_api_logic/service_extension_test.rb
  test/unit/metric_test.rb
  test/unit/models_test.rb
  test/unit/provider_test.rb
  test/unit/proxy_rule_test.rb
  test/unit/proxy_test.rb
  test/unit/service_test.rb
  test/unit/services/provider_proxy_deployment_service_test.rb
  test/unit/services/service_creator_test.rb
  test/unit/services/service_discovery/import_cluster_definitions_service_test.rb
  test/unit/signup/account_manager_test.rb
  test/workers/backend_metric_worker_test.rb
Labels: APIAP, Priority: Blocker

#1213 [API Endpoints] Mapping Rules under Backend API
  app/controllers/admin/api/backend_apis/base_controller.rb
  app/controllers/admin/api/backend_apis/mapping_rules_controller.rb
  app/controllers/admin/api/backend_apis/metric_methods_controller.rb
  app/controllers/admin/api/backend_apis/metrics_controller.rb
  app/controllers/admin/api/base_controller.rb
  app/controllers/admin/api/services/mapping_rules_controller.rb
  app/models/proxy_rule.rb
  app/representers/backend_api_representer.rb
  app/representers/proxy_rule_representer.rb
  config/routes.rb
  doc/active_docs/Account Management API.json
  spec/acceptance/api/backend_api_spec.rb
  test/integration/admin/api/backend_apis/mapping_rules_controller_test.rb
  test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
  test/integration/admin/api/backend_apis/metrics_controller_test.rb
Labels: APIAP, Priority: High, feature, ruby

#1223 Fix Cuke Master Step ensuring that master exists or creates it
  features/step_definitions/master_steps.rb
Labels: Priority: Low, bug, ruby

#1221 Fix Cuke Step: stub integration errors after signup and before login
  features/step_definitions/provider_steps.rb
Labels: Priority: Low, bug, ruby

#1144 Implement Mark as Deleted for Backend Api
  app/controllers/admin/api/backend_apis/base_controller.rb
  app/controllers/admin/api/backend_apis/mapping_rules_controller.rb
  app/controllers/admin/api/backend_apis_controller.rb
  app/controllers/provider/admin/backend_apis/base_controller.rb
  app/controllers/provider/admin/backend_apis_controller.rb
  app/models/backend_api.rb
  db/migrate/20190904144157_add_state_to_backend_apis.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
  test/integration/admin/api/backend_apis/mapping_rules_controller_test.rb
  test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
  test/integration/admin/api/backend_apis/metrics_controller_test.rb
  test/integration/admin/api/backend_apis_controller_test.rb
  test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb
  test/integration/provider/admin/backend_apis/metrics_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/models/backend_api_test.rb
Labels: APIAP, Priority: High

#1217 Fix redirect_url field in the proxy and backend_api/mapping rules
  app/views/api/proxy_rules/index.html.slim
  app/views/api/proxy_rules/new.html.slim
  app/views/shared/proxy_rules/_form.html.slim
  app/views/shared/proxy_rules/_table.html.slim
  test/integration/api/proxy_rules_controller_test.rb
  test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb
Labels: APIAP, Priority: Low, bug, enhancement, ruby

#1185 [Refactor] Rename cuke step for RU act_as_product + Improve scope BackendApiConfig.with_subpath
  app/models/backend_api_config.rb
  features/old/menu/api_menu.feature
  features/step_definitions/provider_steps.rb
  test/models/backend_api_config_test.rb
Labels: APIAP, Priority: Low, enhancement, ruby

#1224 Destroy Backend APIs for destroyed objects when RU api_as_product disabled
  app/subscribers/service_deletion_subscriber.rb
  app/workers/delete_object_hierarchy_worker.rb
  app/workers/delete_service_hierarchy_worker.rb
  test/subscribers/service_deletion_subscriber_test.rb
  test/workers/delete_object_hierarchy_worker_test.rb
  test/workers/delete_service_hierarcy_worker_test.rb
Labels: APIAP, Priority: High, enhancement, ruby

#1226 Add Backend API config to product
  app/controllers/api/backend_api_configs_controller.rb
  app/lib/backend_api_logic/service_extension.rb
  app/models/backend_api_config.rb
  app/views/api/backend_api_configs/new.html.slim
  app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
  config/abilities/provider_admin.rb
  config/routes.rb
  test/factories/account.rb
  test/factories/simple.rb
  test/integration/api/backend_api_configs_controller_test.rb
  test/models/backend_api_config_test.rb
  test/unit/abilities/provider_admin_test.rb
Labels: APIAP

#1227 THREESCALE-3476: Updating New API/Product page
  app/javascript/src/NewService/components/FormElements/BackendApiSelect.jsx
  app/javascript/src/NewService/components/FormElements/index.jsx
  app/javascript/src/NewService/components/NewServiceForm.jsx
  app/javascript/src/NewService/components/ServiceDiscoveryForm.jsx
  app/javascript/src/NewService/components/ServiceManualForm.jsx
  app/javascript/src/NewService/components/ServiceSourceForm.jsx
  features/old/services/multiservice.feature
  features/old/services/switch.feature
  spec/javascripts/NewService/NewServiceForm.spec.jsx
  spec/javascripts/NewService/ServiceDiscoveryForm.spec.jsx
  spec/javascripts/NewService/ServiceSourceForm.spec.jsx
  spec/javascripts/NewService/formElements/BackendApiSelect.spec.jsx
Labels: APIAP

#1230 CRUD for backend api configs detached from proxy config page
  app/assets/stylesheets/provider/_tables.scss
  app/controllers/api/backend_api_configs_controller.rb
  app/helpers/vertical_nav_helper.rb
  app/models/backend_api_config.rb
  app/views/api/backend_api_configs/_form.html.slim
  app/views/api/backend_api_configs/edit.html.slim
  app/views/api/backend_api_configs/index.html.slim
  app/views/api/backend_api_configs/new.html.slim
  app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
  config/routes.rb
  features/old/menu/api_menu.feature
  test/integration/api/backend_api_configs_controller_test.rb
Labels: APIAP

#1229 Integration Settings part 1
  app/controllers/api/services_controller.rb
  app/controllers/frontend_controller.rb
  app/helpers/services_helper.rb
  app/helpers/vertical_nav_helper.rb
  app/views/api/services/forms/_integration_settings_apiap.html.slim
  app/views/api/services/settings_apiap.html.slim
  config/locales/en.yml
  features/old/api/plans/service_plans.feature
  features/old/api/settings.feature
  features/step_definitions/rolling_updates_steps.rb
  test/functional/api/services_controller_test.rb
  test/integration/api/services_controller_test.rb
Labels: APIAP

#1238 Integration Settings part 2
  app/javascript/packs/settings.js
  app/javascript/src/Settings/authentication-widget.jsx
  app/javascript/src/Settings/styles/authentication.scss
  app/views/api/services/forms/_authentication_settings.html.slim
  app/views/api/services/forms/_integration_settings_apiap.html.slim
  app/views/api/services/forms/_oidc.html.slim
Labels: APIAP

#1242 Integration Settings part 3
  app/controllers/api/integrations_controller.rb
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
  app/views/api/integrations/apicast/shared/_deployment_options.html.slim
  features/old/api/settings.feature
Labels: APIAP

#1241 Ensure uniqueness of service_id + backend_api_id
  app/models/backend_api.rb
  app/models/backend_api_config.rb
  app/models/deleted_object.rb
  app/models/service.rb
  app/views/api/backend_api_configs/_form.html.slim
  db/migrate/20190925133159_enforce_uniqueness_association_service_backend_api.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/models/backend_api_config_test.rb
  test/models/backend_api_test.rb
Labels: APIAP, Priority: Blocker

#1247 Threescale 3451/integration settings 2
  app/javascript/packs/settings.js
  app/javascript/src/Settings/authentication-widget.jsx
  app/javascript/src/Settings/styles/authentication.scss
  app/views/api/services/forms/_authentication_settings.html.slim
  app/views/api/services/forms/_integration_settings_apiap.html.slim
  app/views/api/services/forms/_oidc.html.slim
Labels: APIAP

#1248 Threescale 3451/integration settings 3
  app/controllers/api/integrations_controller.rb
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
  app/views/api/integrations/apicast/shared/_deployment_options.html.slim
  features/old/api/settings.feature
Labels: APIAP

#1246 Links to backend api configs in the index
  app/views/api/backend_api_configs/index.html.slim
Labels: APIAP

#1253 [apiap] Proxy attributes should be updatable in services
  app/controllers/admin/api/services/proxies_controller.rb
  app/controllers/api/services_controller.rb
  app/models/application_record.rb
  app/models/proxy.rb
  app/models/service.rb
  test/functional/api/services_controller_test.rb
Labels: APIAP

#1254 Fix Backend API/Backend API Config naming, forms and links
  app/controllers/admin/api/backend_apis/mapping_rules_controller.rb
  app/controllers/admin/api/backend_apis/metric_methods_controller.rb
  app/controllers/admin/api/backend_apis/metrics_controller.rb
  app/controllers/admin/api/backend_apis_controller.rb
  app/controllers/admin/api/base_controller.rb
  app/controllers/api/backend_api_configs_controller.rb
  app/controllers/provider/admin/backend_apis_controller.rb
  app/javascript/src/NewService/components/ServiceSourceForm.jsx
  app/lib/backend_api_logic/service_extension.rb
  app/views/api/backend_api_configs/_form.html.slim
  app/views/api/backend_api_configs/edit.html.slim
  app/views/api/backend_api_configs/index.html.slim
  app/views/api/backend_api_configs/new.html.slim
  app/views/api/metrics/_backend_api.erb
  app/views/provider/admin/backend_apis/edit.html.slim
  app/views/provider/admin/backend_apis/forms/_delete.html.slim
  app/views/provider/admin/backend_apis/metrics/index.html.slim
  app/views/provider/admin/backend_apis/new.html.slim
  app/views/provider/admin/backend_apis/show.html.slim
  doc/active_docs/Account Management API.json
  features/old/menu/backend_api_menu.feature
  features/old/menu/dashboard.feature
  spec/javascripts/NewService/ServiceSourceForm.spec.jsx
  test/factories/account.rb
  test/factories/backend_api.rb
  test/integration/api/backend_api_configs_controller_test.rb
  test/integration/api/services_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/models/backend_api_test.rb
  test/unit/backend_api_logic/service_extension_test.rb
  test/unit/signup/account_manager_test.rb
Labels: APIAP

#1214 [API Endpoints] Backend API Configs
  app/controllers/admin/api/backend_apis_controller.rb
  app/controllers/admin/api/base_controller.rb
  app/controllers/admin/api/services/backend_api_configs_controller.rb
  app/controllers/admin/api/services/base_controller.rb
  app/models/backend_api_config.rb
  app/representers/backend_api_config_representer.rb
  app/representers/backend_api_configs_representer.rb
  config/routes.rb
  doc/active_docs/Account Management API.json
  test/integration/admin/api/services/backend_api_configs_controller_test.rb
  test/integration/api_docs/services_controller_test.rb
Labels: APIAP, Priority: High, feature, ruby

#1239 Implement search by pattern for Mapping Rules
  Gemfile.base
  Gemfile.lock
  app/controllers/api/proxy_rules_controller.rb
  app/controllers/provider/admin/backend_apis/mapping_rules_controller.rb
  app/controllers/proxy_rule_shared_controller.rb
  app/indices/proxy_rules_index.rb
  app/models/proxy_rule.rb
  app/queries/proxy_rule_query.rb
  app/views/shared/proxy_rules/_table.html.slim
  app/workers/application_job.rb
  app/workers/index_proxy_rule_worker.rb
  config/routes.rb
  features/support/env.rb
  gemfiles/prod/Gemfile.lock
  test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb
  test/integration/service_not_deleted_test.rb
  test/monkey_patches/active_job_test_helper.rb
  test/test_helper.rb
  test/unit/proxy_rule_test.rb
  test/unit/queries/proxy_rule_query_test.rb
Labels: APIAP

#1260 Promote to Staging button
  app/controllers/api/integrations_controller.rb
  app/presenters/api/integrations_show_presenter.rb
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
  test/unit/presenters/api/integrations_show_presenter_test.rb
Labels: APIAP

#1257 Extract apiap data migrations to rake tasks
  app/lib/backend_api_logic/service_extension.rb
  db/migrate/20190716110520_create_the_backend_apis_of_services.rb
  db/migrate/20190801143259_backfill_proxy_rules_owners.rb
  db/migrate/20190805135829_backfill_metric_owners.rb
  lib/tasks/proxy.rake
  lib/tasks/services.rake
  test/unit/backend_api_logic/service_extension_test.rb
  test/unit/tasks/proxy_test.rb
  test/unit/tasks/services_test.rb
Labels: APIAP

#1228 [apiap] Extract Policies to its own page
  app/controllers/api/policies_controller.rb
  app/helpers/vertical_nav_helper.rb
  app/javascript/src/Policies/actions/OriginalPolicyChain.jsx
  app/javascript/src/Policies/components/PoliciesWidget.jsx
  app/javascript/src/Policies/middleware/PolicyChain.jsx
  app/javascript/src/Policies/reducers/OriginalPolicyChain.jsx
  app/javascript/src/Policies/reducers/index.jsx
  app/javascript/src/Policies/reducers/initialState.jsx
  app/javascript/src/Policies/types/State.jsx
  app/javascript/src/Policies/types/index.jsx
  app/javascript/src/Policies/util.jsx
  app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
  app/views/api/policies/edit.html.slim
  config/abilities/provider_admin.rb
  config/locales/en.yml
  config/routes.rb
  spec/javascripts/Policies/middleware/PolicyChain.spec.jsx
  spec/javascripts/Policies/reducers/UISettings.spec.jsx
  spec/javascripts/Policies/util.spec.jsx
  test/integration/api/policies_controller_test.rb
Labels: APIAP

#1233 [Rolling updates] Make impersonation admin behave like normal admin
  app/lib/logic/rolling_updates.rb
  test/unit/logic/rolling_updates_test.rb
Labels: ruby

#1244 Proxy config affecting change events
  app/events/proxy_configs/affecting_object_changed_event.rb
  app/lib/event_store/repository.rb
  app/lib/proxy_config_affecting_changes.rb
  app/models/backend_api.rb
  app/models/proxy.rb
  app/models/proxy_config_affecting_change.rb
  app/models/proxy_rule.rb
  app/subscribers/proxy_config_event_subscriber.rb
  app/workers/proxy_config_affecting_change_worker.rb
  db/migrate/20190925152107_create_proxy_config_affecting_changes.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
  test/events/proxy_configs/affecting_object_changed_event_test.rb
  test/subscribers/proxy_config_event_subscriber_test.rb
  test/unit/proxy_rule_test.rb
  test/unit/proxy_test.rb
  test/workers/proxy_config_affecting_change_worker_test.rb
Labels: APIAP

#1255 [settings] Auth settings behaviour updated
  app/javascript/src/Settings/authentication-widget.jsx
  app/views/api/services/forms/_authentication_settings.html.slim
  app/views/api/services/forms/_integration_settings_apiap.html.slim
  app/views/api/services/forms/_oidc.html.slim
Labels: APIAP

#1235 Show exclamation mark for each product with out of date config
  app/assets/stylesheets/provider/_patternfly_ie11.scss
  app/helpers/application_helper.rb
  app/helpers/provider/admin/dashboards_helper.rb
  app/javascript/packs/vertical_nav.js
  app/javascript/src/Navigation/components/PF4NavProxy.jsx
  app/javascript/src/Navigation/components/VerticalNav.jsx
  app/models/service.rb
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  app/views/shared/provider/navigation/_vertical_nav_item.html.slim
  test/unit/helpers/provider/admin/dashboards_helper_test.rb
Labels: APIAP

#1261 MetricsController in API must behave the same way for BackendApi as for Service
  app/controllers/admin/api/backend_apis/metrics_controller.rb
  test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
  test/integration/admin/api/backend_apis/metrics_controller_test.rb
Labels: APIAP

#1262 [settings] Adapted behaviour for OIDC and MESH integration
  app/javascript/src/Settings/authentication-widget.jsx
  app/views/api/services/forms/_authentication_settings.html.slim
Labels: APIAP

#1259 Cannot destroy a BackendApi used by Services
  app/controllers/provider/admin/backend_apis_controller.rb
  app/models/backend_api.rb
  app/models/backend_api_config.rb
  app/representers/backend_api_representer.rb
  app/views/provider/admin/backend_apis/forms/_delete.html.slim
  app/workers/delete_object_hierarchy_worker.rb
  app/workers/delete_service_hierarchy_worker.rb
  config/locales/en.yml
  spec/acceptance/api/backend_api_spec.rb
  test/integration/admin/api/backend_apis_controller_test.rb
  test/integration/admin/api/services/backend_api_configs_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/models/backend_api_config_test.rb
  test/models/backend_api_test.rb
  test/workers/delete_service_hierarcy_worker_test.rb
Labels: APIAP, Priority: High, enhancement, feature, ruby

#1272 BackendApiConfig as an affecting object of Proxy config
  app/lib/proxy_config_affecting_changes.rb
  app/models/backend_api_config.rb
  app/models/proxy.rb
  test/models/backend_api_config_test.rb
  test/unit/proxy_rule_test.rb
  test/unit/proxy_test.rb
Labels: APIAP

#1267 Scope ProxyRule's acts_as_list by owner
  app/models/proxy_rule.rb
Labels: APIAP
