Repository 3scale/porta, pull requests merged in 2019-07, with the labels that each got.

#953 [Refactor] Remove unused Account::Gateway#payment_gateway_unconfigured?
  app/models/account/gateway.rb
  lib/developer_portal/app/controllers/developer_portal/admin/account/adyen12_controller.rb
  test/unit/account/gateway_test.rb
  test/unit/invoice_test.rb
Labels: Priority: Low, enhancement, good first issue, ruby

#970 [bugfix] Keycloak client must have openid scope
  app/lib/three_scale/oauth2/keycloak_client.rb
  test/unit/three_scale/oauth2/keycloak_client_test.rb
Labels: Priority: High, ruby

#990 Fixes Header on small screen setup
  app/assets/stylesheets/provider/_patternfly_ie11.scss
Labels: Priority: High

#975 Upload logo only allows images
  app/controllers/provider/admin/account/logos_controller.rb
  app/models/cms/file.rb
  app/models/profile.rb
  app/views/provider/admin/account/logos/update.js.erb
  config/initializers/paperclip.rb
  config/locales/en.yml
  features/old/site/logo.feature
  features/step_definitions/logo_steps.rb
  test/fixtures/fake_image.jpg
  test/integration/provider/admin/account/logos_controller_test.rb
  test/unit/cms/file_test.rb
  test/unit/profile_test.rb
Labels: Priority: High, enhancement, ruby, security

#1004 Revert THREESCALE-2808-PF4-React-Navbar-Components
  app/assets/stylesheets/provider/_header.scss
  app/javascript/packs/navigation.js
  app/javascript/packs/pf4BaseStyles.js
  app/javascript/src/Navigation/components/PF4NavProxy.jsx
  app/javascript/src/Navigation/components/VerticalNav.jsx
  app/javascript/src/Navigation/styles/PF4NavProxy.scss
  app/views/shared/provider/navigation/_vertical_nav.html.slim
  spec/javascripts/Navigation/VerticalNav.spec.jsx
Labels: Priority: Blocker, javascript

#1001 Yet another update of the package-lock
  package-lock.json
  package.json
Labels: javascript

#1010 [Bugfix] DeleteObjectHierarchyWorker raise URI::GID::MissingModelIdError
  app/workers/delete_object_hierarchy_worker.rb
  test/workers/delete_object_hierarchy_worker_test.rb
Labels: bug, ruby

#1013 Hide AccountPlan from Account#show view unless it has permission, like in the nav
  app/helpers/plans_helper.rb
  app/views/buyers/accounts/show.html.slim
  app/views/shared/provider/navigation/audience/_accounts.html.slim
  features/old/menu/audience_menu.feature
  features/step_definitions/menu_steps.rb
  test/unit/helpers/plans_helper_test.rb
Labels: Priority: High, ruby

#1023 create_and_publish returns the event
  app/events/base_event_store_event.rb
  test/events/applications/application_deleted_event_test.rb
  test/events/base_event_store_event_test.rb
  test/events/domains/provider_domains_changed_event_test.rb
  test/events/domains/proxy_domains_changed_event_test.rb
  test/events/oidc/proxy_changed_event_test.rb
  test/events/oidc/service_changed_event_test.rb
  test/events/services/service_deleted_event_test.rb
  test/events/services/service_token_deleted_event_test.rb
  test/events/users/user_deleted_event_test.rb
  test/workers/backend_delete_end_users_worker_test.rb
  test/workers/backend_delete_service_token_worker_test.rb
  test/workers/backend_delete_service_worker_test.rb
  test/workers/backend_delete_stats_worker_test.rb
  test/workers/create_service_token_worker_test.rb
  test/workers/process_notification_event_worker_test.rb
  test/workers/segment_delete_user_worker_test.rb
  test/workers/zync_worker_test.rb
Labels: Priority: Low, enhancement, ruby
