Repository 3scale/porta, pull requests merged in 2019-05, with the labels that each got.

#787 [prometheus] Sidekiq::Prometheus::Exporter is back
  Gemfile.base
  Gemfile.lock
  config/routes.rb
  gemfiles/prod/Gemfile.lock
Labels: Priority: High, ruby

#786 Detect dangerous migrations
  Gemfile.base
  Gemfile.lock
  config/initializers/strong_migrations.rb
  gemfiles/prod/Gemfile.lock
Labels: Priority: High, ruby

#789 Fix random test failure in test_raises_if_trying_to_upgrade_to_enterprise
  test/unit/logic/provider_upgrade_test.rb
Labels: Priority: High, bug, ruby

#802 [Gemfile] Remove ruby requirements
  Gemfile
  Gemfile.lock
  gemfiles/prod/Gemfile
  gemfiles/prod/Gemfile.lock
Labels: Priority: High, ruby

#801 Upgrade gems: stripe, rest-client
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
  test/unit/backend_client/connection_test.rb
Labels: Priority: High, ruby

#800 [gem] Upgrading webmock to 2.3.2 for ruby2.4
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
  test/unit/active_merchant/stripe_fix_test.rb
Labels: Priority: High, ruby

#799 Dashboard stream and email notifications are filtered according to the member permissions
  app/events/applications/application_plan_change_requested_event.rb
  config/abilities/provider_any.rb
  test/unit/abilities/provider_any_test.rb
Labels: Priority: High, bug, ruby

#807 Migrate create application coffeescript to Webpack pipeline
  app/assets/javascripts/provider/create_application.js.coffee
  app/javascript/packs/applications.js
  app/javascript/src/Applications/create_application.js
  app/javascript/src/Applications/plan_selector.jsx
  app/views/buyers/applications/new.html.erb
Labels: Priority: High, javascript

#814 Ruby 2.4 nightly builds
  .circleci/config.yml
  app/lib/three_scale/spam_protection/checks/timestamp.rb
  openshift/system/Dockerfile
  openshift/system/Dockerfile.on_prem
  openshift/system/contrib/scl_enable
Labels: Priority: High, ruby

#816 Test User#accessible_services when the user has access to all services
  test/unit/user_test.rb
Labels: Priority: Low, enhancement, ruby

#808 Master Member gets permissions for provider_plans
  app/controllers/master/providers/plans_controller.rb
  app/views/buyers/accounts/show.html.slim
  config/abilities/master_member.rb
  test/integration/master/providers/plans_controller_test.rb
  test/unit/abilities/master_member_test.rb
Labels: Priority: High, bug, ruby

#823 [Bugfix] [Postgres] for SELECT DISTINCT, ORDER BY expressions must appear in select list.
  test/integration/master/providers/plans_controller_test.rb
Labels: Priority: Blocker, bug, ruby

#824 [Bugfix][Oracle] Remove experimental test
  test/workers/delete_object_hierarchy_worker_test.rb
Labels: Priority: Blocker, bug, ruby

#822 Fix Oracle Schema for DeletedObjects
  db/migrate/20190527104222_fix_oracle_deleted_objects_precision.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
Labels: Priority: High, bug, ruby

#825 Remove reference to old field Services#buyer_can_see_log_requests
  app/models/service.rb
Labels: Priority: Low, enhancement, good first issue, ruby

#827 [Refactor & Bugfix] Task update corrupted or empty tenant_id
  lib/tasks/multitenant/tenants.rake
  lib/tasks/multitenant/triggers.rake
  test/unit/tasks/multitenant/tenants_test.rb
Labels: Priority: High, bug, enhancement, ruby
