Repository 3scale/porta, pull requests merged in 2019-10, with the labels that each got.

#1273 [LOW PRIORITY][Fix] Escaped HTML entities in edit API page
  app/helpers/api/services_helper.rb
  app/helpers/cinstances_helper.rb
  app/views/api/services/_delete.html.slim
  app/views/provider/admin/backend_apis/forms/_delete.html.slim
Labels: Priority: Low

#1278 Improve error message when the apicast registry url is not present + 'Start by'
  app/services/policies/policies_list_service.rb
  config/locales/en.yml
Labels: Priority: Low

#1279 Sets correct min-height to element dd
  app/assets/stylesheets/provider/_commons.scss
Labels: APIAP

#1268 APIAP only works with APIcast V2
  app/controllers/api/backend_api_configs_controller.rb
  app/controllers/api/policies_controller.rb
  app/helpers/vertical_nav_helper.rb
  app/models/service.rb
  features/old/menu/api_menu.feature
Labels: APIAP

#1284 [settings] Disabling auth options when service mesh and not oidc
  app/views/api/services/forms/_authentication_settings.html.slim
  app/views/api/services/forms/_oidc.html.slim
Labels: APIAP

#1283 Fix wrong page rendering in Service Settings page
  app/controllers/api/services_controller.rb
  app/helpers/alerts_helper.rb
  app/views/api/services/forms/_settings.html.slim
  app/views/api/services/forms/_usage_rules.html.slim
  app/views/api/services/settings_apiap.html.slim
Labels: APIAP, bug

#1276 Fixes update buttons in new Policies page
  app/javascript/src/Policies/components/PoliciesWidget.jsx
  app/views/api/policies/edit.html.slim
Labels: APIAP

#1286 Change settings update button title
  app/views/api/services/settings_apiap.html.slim
Labels: APIAP

#1277 [APIAP] Update Proxy public/staging urls from Integration -> Settings
  app/controllers/api/services_controller.rb
  app/lib/api_integration/settings_result.rb
  app/views/api/integrations/apicast/shared/_proxy_endpoints.html.slim
  app/views/api/services/forms/_integration_settings_apiap.html.slim
  test/functional/api/services_controller_test.rb
  test/integration/api/services_controller_test.rb
  test/unit/lib/api_integration/settings_result_test.rb
Labels: APIAP, Priority: Blocker

#1287 [api#ednpoint] objects status endpoint
  app/controllers/admin/api/objects_controller.rb
  config/routes.rb
  doc/active_docs/Account Management API.json
  test/integration/admin/api/objects_controller_test.rb
Labels: Priority: Blocker

#1285 Fix apicast replace_path to use remove
  app/lib/backend_api_logic/routing_policy.rb
  test/unit/backend_api_logic/routing_policy_test.rb
  test/unit/proxy_test.rb
Labels: APIAP, Priority: Blocker

#1281 Proxy config workflow
  app/controllers/api/integrations_controller.rb
  app/controllers/frontend_controller.rb
  app/helpers/api/integrations_helper.rb
  app/lib/proxy_config_affecting_changes.rb
  app/presenters/api/integrations_show_presenter.rb
  app/views/api/backend_api_configs/new.html.slim
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
  app/views/api/integrations/apicast/shared/_deployment_options.html.slim
  app/views/api/integrations/show.html.slim
  app/views/provider/admin/backend_apis/edit.html.slim
  app/views/provider/admin/backend_apis/new.html.slim
  app/views/provider/admin/dashboards/_service_navigation.html.slim
  features/old/api/settings.feature
  features/old/menu/dashboard.feature
  test/unit/proxy_test.rb
Labels: APIAP, Priority: Blocker

#1292 Create first backend api of every tenant
  app/models/account/provider_methods.rb
  lib/signup/provider_account_manager.rb
  test/integration/admin/api/backend_apis_controller_test.rb
  test/integration/api/backend_api_configs_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/unit/db/seeds_test.rb
  test/unit/service_test.rb
  test/unit/signup/account_manager_test.rb
Labels: APIAP, Priority: Blocker

#1295 Show "service access" message only when there are no accessible services
  app/views/api/services/show.html.slim
  app/views/buyers/applications/index.html.slim
Labels: APIAP

#1296 Fix Random CircleCI failure: in 'test_custom_release' - Expected '4', got '2'
  lib/system/deploy.rb
  test/fixtures/deploy_info
  test/unit/deploy/basic_info_test.rb
Labels: Priority: Blocker

#1305 [API] Backend Usage 'show/read' + Representer returns service id & backend api id
  app/controllers/admin/api/services/backend_api_configs_controller.rb
  app/representers/backend_api_config_representer.rb
  config/routes.rb
  doc/active_docs/Account Management API.json
  test/integration/admin/api/services/backend_api_configs_controller_test.rb
Labels: APIAP, Priority: High, enhancement, feature, ruby

#1299 [cuke] New Integration Settings
  features/api/services/settings.feature
  features/old/api/plans/service_plans.feature
  features/old/api/settings.feature
  features/old/menu/dashboard.feature
  features/step_definitions/custom_web_steps.rb
  features/step_definitions/rolling_updates_steps.rb
Labels: APIAP

#1303 Fix integration settings update no-op for proxy params
  app/controllers/api/services_controller.rb
  app/services/api_integration/settings_updater_service.rb
  config/locales/en.yml
  features/old/services/multiservice.feature
  test/integration/api/services_controller_test.rb
  test/unit/services/api_integration/settings_updater_service_test.rb
Labels: APIAP

#1288 Update APIAP icons in the Dashboard
  app/javascript/src/Navigation/components/ActiveMenuTitle.jsx
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/views/provider/admin/dashboards/_section_products_and_backends.html.slim
  app/views/provider/admin/dashboards/_service.html.slim
  spec/javascripts/Navigation/ContextSelector.spec.jsx
Labels: APIAP

#1314 Avoid IndexProxyRuleWorker to raise Record not found
  app/workers/index_proxy_rule_worker.rb
  test/workers/index_proxy_rule_worker_test.rb
Labels: APIAP

#1316 Fix infinite lazy initialization when the object will be destroyed
  app/lib/cms/settings.rb
  app/models/account.rb
  app/models/account/provider_methods.rb
  app/models/account/states.rb
  app/models/service.rb
  app/representers/account_representer.rb
  lib/developer_portal/app/views/shared/_footer.html.erb
  test/unit/pdf/dispatch_test.rb
  test/unit/service_test.rb
  test/workers/delete_account_hierarchy_worker_test.rb
  test/workers/delete_object_hierarchy_worker_test.rb
Labels: Priority: Blocker, bug, ruby

#1308 Avoid Empty paths for BackendApiConfig
  app/lib/backend_api_logic/routing_policy.rb
  app/lib/backend_api_logic/service_extension.rb
  app/models/backend_api_config.rb
  app/models/config_path.rb
  app/services/service_creator.rb
  app/validators/path_validator.rb
  lib/tasks/data_migration/fix_backend_config_path.rb
  lib/tasks/services.rake
  test/factories/backend_api.rb
  test/fixtures/backend_api_configs.yml
  test/integration/admin/api/services/backend_api_configs_controller_test.rb
  test/integration/api/backend_api_configs_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/models/backend_api_config_test.rb
  test/unit/backend_api_logic/routing_policy_test.rb
  test/unit/config_path_test.rb
  test/unit/proxy_rule_test.rb
  test/unit/tasks/data_migration/fix_backend_config_path_test.rb
  test/unit/tasks/services_test.rb
Labels: APIAP

#1182 PF content background, header & card look & feel
  app/assets/stylesheets/provider/_bulk_operations.scss
  app/assets/stylesheets/provider/_buttons.scss
  app/assets/stylesheets/provider/_charts.scss
  app/assets/stylesheets/provider/_colorbox.scss
  app/assets/stylesheets/provider/_colors.scss
  app/assets/stylesheets/provider/_commons.scss
  app/assets/stylesheets/provider/_dropdowns.scss
  app/assets/stylesheets/provider/_fields_definitions.scss
  app/assets/stylesheets/provider/_finance.scss
  app/assets/stylesheets/provider/_forms.scss
  app/assets/stylesheets/provider/_forum.scss
  app/assets/stylesheets/provider/_groups.scss
  app/assets/stylesheets/provider/_info_box.scss
  app/assets/stylesheets/provider/_inline_helper.scss
  app/assets/stylesheets/provider/_legacy_theme.scss
  app/assets/stylesheets/provider/_links.scss
  app/assets/stylesheets/provider/_liquid_docs.scss
  app/assets/stylesheets/provider/_logo.scss
  app/assets/stylesheets/provider/_menu.scss
  app/assets/stylesheets/provider/_metrics.scss
  app/assets/stylesheets/provider/_patternfly_tabs_fake.scss
  app/assets/stylesheets/provider/_pop_navigation.scss
  app/assets/stylesheets/provider/_section.scss
  app/assets/stylesheets/provider/_services.scss
  app/assets/stylesheets/provider/_settings_box.scss
  app/assets/stylesheets/provider/_sidetabs.scss
  app/assets/stylesheets/provider/_tables.scss
  app/assets/stylesheets/provider/admin/_account.scss
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/assets/stylesheets/provider/admin/apiconfig/services/_promote_form.scss
  app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
  app/assets/stylesheets/provider/admin/cms/_sections.scss
  app/assets/stylesheets/provider/admin/cms/_sidebar.scss
  app/assets/stylesheets/provider/admin/cms/sidebar/_filter.scss
  app/assets/stylesheets/provider/layouts/_main.scss
  app/assets/stylesheets/provider/stats/_base.scss
  app/assets/stylesheets/provider/stats/_selector.scss
  app/javascript/src/Dashboard/styles/dashboard.scss
  app/views/api/metrics/_metric.html.erb
  app/views/api/plans/_metrics.html.erb
  app/views/api/pricing_rules/_pricing_rules.html.erb
  app/views/buyers/groups/show.html.erb
  app/views/buyers/users/show.html.erb
  vendor/active-docs/app/assets/stylesheets/active-docs/application.scss
Labels: percy

#1325 Inject `owner_id` into the routing policy rules
  app/lib/backend_api_logic/routing_policy.rb
  test/unit/backend_api_logic/routing_policy_test.rb
  test/unit/proxy_test.rb
Labels: APIAP

#1324 Create a new tenant through 'master-domain/p/signup' does not create a backend api
  app/lib/logic/provider_signup.rb
  test/unit/account_test.rb
Labels: APIAP, do not review

#1343 Give Master Admin permission to see Backend API
  config/abilities/master_admin.rb
  test/unit/abilities/master_admin_test.rb
  test/unit/abilities/provider_admin_test.rb
Labels: APIAP

#1350 Fix wrong popup message when deleting method or metric
  app/views/api/metrics/edit.html.erb
  app/views/provider/admin/backend_apis/metrics/edit.html.erb
Labels: APIAP

#1321 test curl command + other UI improvements in the proxy config page
  app/assets/stylesheets/provider/_forms.scss
  app/helpers/api/integrations_helper.rb
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
  test/functional/api/integrations_controller_test.rb
  test/unit/helpers/api/integrations_helper_test.rb
Labels: APIAP

#1354 Issue proxy affecting change on backend api private endpoint update
  app/lib/proxy_config_affecting_changes.rb
  app/models/backend_api.rb
  test/models/backend_api_test.rb
Labels: APIAP

#1304 Update Wizard with steps for Product/Backend
  app/assets/stylesheets/provider/themes/wizard.scss
  app/controllers/provider/admin/onboarding/wizard/api_controller.rb
  app/controllers/provider/admin/onboarding/wizard/backend_api_controller.rb
  app/controllers/provider/admin/onboarding/wizard/base_controller.rb
  app/controllers/provider/admin/onboarding/wizard/connect_controller.rb
  app/controllers/provider/admin/onboarding/wizard/info_controller.rb
  app/controllers/provider/admin/onboarding/wizard/product_controller.rb
  app/controllers/provider/admin/onboarding/wizard/request_controller.rb
  app/javascript/packs/apiap_wizard_backend_api.js
  app/views/provider/admin/onboarding/wizard/api/_form.html.slim
  app/views/provider/admin/onboarding/wizard/backend_api/new.html.slim
  app/views/provider/admin/onboarding/wizard/connect/new.html.slim
  app/views/provider/admin/onboarding/wizard/info/explain.html.slim
  app/views/provider/admin/onboarding/wizard/product/new.html.slim
  app/views/provider/admin/onboarding/wizard/request/new.html.slim
  config/routes.rb
  features/provider/onboarding/wizard.feature
  features/step_definitions/onboarding/apiap_wizard_steps.rb
  features/step_definitions/onboarding/wizard_steps.rb.rb
Labels: APIAP

#1357 Add fix to Wizard
  app/controllers/provider/admin/onboarding/wizard/request_controller.rb
  app/forms/onboarding/request_form.rb
Labels: APIAP

#1363 Ignore empty endpoint when generating curl command
  app/helpers/api/integrations_helper.rb
  test/unit/helpers/api/integrations_helper_test.rb
Labels: bug

#1368 Redirect to show when promotion to Staging fails
  app/controllers/api/integrations_controller.rb
Labels: APIAP

#1373 Fix Policies when having twice of the same type
  app/javascript/src/Policies/components/PoliciesForm.jsx
  app/javascript/src/Policies/components/PoliciesWidget.jsx
  app/javascript/src/Policies/components/PolicyConfig.jsx
  app/javascript/src/Policies/reducers/PolicyConfig.jsx
  spec/javascripts/Policies/components/PolicyConfig.spec.jsx
Labels: APIAP, bug

#1376 Reorganization of APIcast configuration view for APIAP
  app/assets/stylesheets/provider/_settings_box.scss
  app/helpers/api/integrations_helper.rb
  app/lib/backend_api_logic/routing_policy.rb
  app/models/backend_api_config.rb
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
Labels: APIAP

#1366 Fix empty Policy Chain list in policies/edit
  app/javascript/src/Policies/middleware/PolicyChain.jsx
  spec/javascripts/Policies/middleware/PolicyChain.spec.jsx
Labels: APIAP
