Repository 3scale/porta, pull requests merged in 2019-04, with the labels that each got.

#737 Enable for on-prem the deletion of accounts scheduled for deletion
  app/workers/find_and_delete_scheduled_accounts_worker.rb
  config/jobs.rb
  test/workers/find_and_delete_accounts_scheduled_worker_test.rb
Labels: Priority: Blocker, ruby

#733 styles and copy for custom policies
  app/controllers/provider/admin/registry/policies_controller.rb
  app/javascript/src/Policies/components/CustomPolicies.jsx
  app/javascript/src/Policies/components/CustomPolicy.jsx
  app/javascript/src/Policies/components/SchemaEditor.jsx
  app/javascript/src/Policies/styles/policies.scss
  app/views/provider/admin/registry/policies/_errors.html.slim
  app/views/provider/admin/registry/policies/edit.html.slim
  app/views/provider/admin/registry/policies/index.html.slim
  app/views/provider/admin/registry/policies/new.html.slim
  package-lock.json
  spec/javascripts/Policies/components/CustomPolicies.spec.jsx
  spec/javascripts/Policies/components/CustomPolicy.spec.jsx
Labels: javascript

#443 Remove unused tech_support_email and admin_support_email
  app/controllers/admin/api/services_controller.rb
  app/models/service.rb
  app/representers/service_representer.rb
  app/views/account_messenger/expired_credit_card_notification_for_buyer.text.liquid
  app/views/cinstance_messenger/expired_trial_period_notification.text.liquid
  config/locales/en.yml
  doc/active_docs/Account Management API.json
  lib/developer_portal/lib/liquid/drops/service.rb
  test/integration/api/services_controller_test.rb
  test/integration/user-management-api/services_test.rb
Labels: Priority: High

#746 extracts json utils to utilities common folder
  app/javascript/packs/custom_policies.js
  app/javascript/packs/custom_policy.js
  app/javascript/src/Policies/components/SchemaEditor.jsx
  app/javascript/src/Policies/util.jsx
  app/javascript/src/utilities/json-utils.jsx
Labels: Priority: Low, javascript

#583 [Refactor & Bugfix] Improvements in automatic suspension and deletion of tenants
  app/lib/features/account_deletion_config.rb
  app/models/account.rb
  app/models/cinstance.rb
  app/models/contract.rb
  app/models/service.rb
  app/queries/auto_account_deletion_queries.rb
  app/workers/stale_account_worker.rb
  app/workers/suspend_inactive_accounts_worker.rb
  config/examples/features.yml
  lib/tasks/multitenant/tenants.rake
  test/unit/account_test.rb
  test/unit/cinstance_test.rb
  test/unit/features/account_deletion_config_test.rb
  test/unit/queries/auto_account_deletion_queries_test.rb
  test/unit/service_test.rb
  test/unit/tasks/multitenant/tenants_test.rb
  test/workers/stale_account_worker_test.rb
  test/workers/suspend_inactive_accounts_worker_test.rb
Labels: Priority: Blocker, bug, enhancement, ruby

#749 List of plans in AccountDeletionConfig feature accept SQL Wildcard Characters
  app/models/cinstance.rb
  config/examples/features.yml
  test/unit/cinstance_test.rb
Labels: Priority: Blocker, ruby

#604 Removes decca and refactors Permissions into React
  app/assets/stylesheets/provider/_service_access.scss
  app/javascript/packs/permissions.js
  app/javascript/src/Users/components/FeaturesFieldset.jsx
  app/javascript/src/Users/components/PermissionsForm.jsx
  app/javascript/src/Users/components/RoleRadioGroup.jsx
  app/javascript/src/Users/components/ServicesFieldset.jsx
  app/javascript/src/Users/permissions.jsx
  app/javascript/src/Users/types/index.jsx
  app/javascript/src/Users/utils/index.jsx
  app/views/provider/admin/account/users/_form.html.erb
  package-lock.json
  package.json
  spec/javascripts/Users/components/FeaturesFieldset.spec.jsx
  spec/javascripts/Users/components/PermissionsForm.spec.jsx
  spec/javascripts/Users/components/RoleRadioGroup.spec.jsx
  spec/javascripts/Users/components/ServicesFieldset.spec.jsx
  spec/javascripts/Users/permissions.spec.js
  spec/javascripts/Users/utils/utils.spec.jsx
Labels: Priority: Low, javascript

#754 Update state_changed_at from deleted_at with a SQL query because deleted_at is removed from Rails programatically
  db/migrate/20181105212016_duplicate_deleted_at_state_changed_at.rb
  openshift/system/Dockerfile
  openshift/system/Dockerfile.on_prem
Labels: Priority: Blocker, bug

#750 [WIP]THREESCALE-2254: Bugfix Service Discovery Fetch
  app/assets/javascripts/provider/admin/apiconfig/services/service_discovery.js
  app/assets/javascripts/provider/layout/provider.js
  app/assets/stylesheets/provider/_forms.scss
  app/javascript/packs/service_discovery.js
  app/views/api/services/forms/_service_discovery.html.slim
Labels: Priority: High, bug

#758 Suggest increasing unicorns in README
  INSTALL.md
Labels: Priority: Low

#769 Validate maximum length of strings in models (before reaching DB)
  app/models/access_token.rb
  app/models/cms/builtin.rb
  app/models/country.rb
  app/models/end_user_plan.rb
  app/models/feature.rb
  app/models/go_live_state.rb
  app/models/invitation.rb
  app/models/invoice.rb
  app/models/invoice_counter.rb
  app/models/message.rb
  app/models/metric.rb
  app/models/partner.rb
  app/models/payment_detail.rb
  app/models/payment_transaction.rb
  app/models/policy.rb
  app/models/profile.rb
  app/models/proxy.rb
  app/models/proxy_log.rb
  app/models/proxy_rule.rb
  app/models/service.rb
  app/models/settings.rb
  app/models/sso_authorization.rb
  app/models/system_operation.rb
  app/models/topic_category.rb
  app/models/user.rb
  app/models/user_session.rb
  test/unit/metric_test.rb
  test/unit/models_test.rb
  test/unit/proxy_rule_test.rb
  test/unit/proxy_test.rb
Labels: Priority: High, ruby

#736 Prevents Runtime error in integration/edit when APIcast not available
  app/services/policies/policies_list_service.rb
  config/examples/sandbox_proxy.yml
  config/locales/en.yml
  features/old/api/settings.feature
  features/step_definitions/apicast_steps.rb
  test/unit/services/policies/policies_list_service_test.rb
Labels: Priority: High, help wanted, ruby
