Repository 3scale/porta, pull requests merged in 2019-06, with the labels that each got.

#829 [proxy] introduce OIDC integration types [THREESCALE-2665]
  app/controllers/admin/api/services/proxies_controller.rb
  app/controllers/api/integrations_controller.rb
  app/models/proxy.rb
  app/representers/proxy_representer.rb
  app/views/api/integrations/apicast/shared/_authentication_settings.html.slim
  config/locales/en.yml
  db/migrate/20190530065503_add_proxies_oidc_issuer_type.rb
  db/schema.rb
  test/unit/proxy_test.rb
Labels: Priority: High, ruby

#844 [zync] publish events about provider domain changes [THREESCALE-2686]
  app/events/domains/provider_domains_changed_event.rb
  app/events/domains/proxy_domains_changed_event.rb
  app/events/zync_event.rb
  app/lib/event_store/repository.rb
  app/lib/missing_model.rb
  app/models/account.rb
  app/models/account/domains.rb
  app/models/proxy.rb
  app/models/service.rb
  app/representers/proxy_representer.rb
  app/subscribers/publish_zync_event_subscriber.rb
  app/workers/zync_worker.rb
  db/seeds.rb
  spec/acceptance/api/proxy_spec.rb
  test/unit/provider_test.rb
  test/unit/proxy_test.rb
Labels: Priority: High, ruby

#891 [braintree] PCI DSS SAQ A compliance
  app/controllers/provider/admin/account/payment_gateways/braintree_blue_controller.rb
  app/views/payment_gateways/_braintree_customer_form.html.erb
  app/views/provider/admin/account/payment_gateways/braintree_blue/edit.html.slim
  features/developer_portal/admin/account/billing_and_credit_card_details.feature
  features/old/finance/credit_card_details_for_provider.feature
  features/old/providers/wizard_upgrade_plan.feature
  features/old/site/payment_details.feature
  features/step_definitions/credit_card_steps.rb
  features/support/capybara.rb
  lib/developer_portal/app/controllers/developer_portal/admin/account/braintree_blue_controller.rb
  lib/payment_gateways/brain_tree_blue_crypt.rb
  test/functional/developer_portal/admin/account/braintree_blue_controller_test.rb
  test/unit/payment_gateways/brain_tree_blue_crypt_test.rb
Labels: Priority: High, javascript, ruby

#905 Fix Master Header's height
  app/assets/stylesheets/provider/_header.scss
Labels: Priority: Blocker, javascript

#919 Add some padding to Header icons
  app/assets/stylesheets/provider/_header.scss
Labels: Priority: High

#923 Fix ContextSelector position / alignment
  app/assets/stylesheets/provider/_pop_navigation.scss
Labels: Priority: High

#945 Feature/threescale 2883 reduce assets
  app/assets/patternfly/fontawesome/_animated.scss
  app/assets/patternfly/fontawesome/_bordered-pulled.scss
  app/assets/patternfly/fontawesome/_core.scss
  app/assets/patternfly/fontawesome/_fixed-width.scss
  app/assets/patternfly/fontawesome/_icons.scss
  app/assets/patternfly/fontawesome/_larger.scss
  app/assets/patternfly/fontawesome/_list.scss
  app/assets/patternfly/fontawesome/_mixins.scss
  app/assets/patternfly/fontawesome/_rotated-flipped.scss
  app/assets/patternfly/fontawesome/_screen-reader.scss
  app/assets/patternfly/fontawesome/_stacked.scss
  app/assets/patternfly/fontawesome/_variables.scss
  app/assets/patternfly/fontawesome/fontawesome.scss
  app/assets/patternfly/icons/fontawesome.css
  app/assets/patternfly/images/FuseConnector_Icons_AzureServices.png
  app/assets/patternfly/images/FuseConnector_Icons_REST.png
  app/assets/patternfly/images/activemq-core_200x150.png
  app/assets/patternfly/images/background-filter.svg
  app/assets/patternfly/images/camel-avro_200x150.png
  app/assets/patternfly/images/camel-dropbox_200x150.png
  app/assets/patternfly/images/camel-infinispan_200x150.png
  app/assets/patternfly/images/camel-saxon_200x150.png
  app/assets/patternfly/images/camel-spark_200x150.png
  app/assets/patternfly/images/camel-swagger-java_200x150.png
  app/assets/patternfly/images/g_sizing.png
  app/assets/patternfly/images/img_avatar.svg
  app/assets/patternfly/images/l_pf-reverse-164x11.png
  app/assets/patternfly/images/l_pf-reverse.svg
  app/assets/patternfly/images/logo-dropbox-old.svg
  app/assets/patternfly/images/logo-dropbox.svg
  app/assets/patternfly/images/logo-facebook.svg
  app/assets/patternfly/images/logo-github.svg
  app/assets/patternfly/images/logo-gitlab.svg
  app/assets/patternfly/images/logo-google.svg
  app/assets/patternfly/images/logo-google2.svg
  app/assets/patternfly/images/pf-logo-small.svg
  app/assets/patternfly/images/pf_logo.svg
  app/assets/patternfly/images/pf_logo_color.svg
  app/assets/patternfly/images/pf_mini_logo_white.svg
  app/assets/patternfly/images/pfbg_1200.jpg
  app/assets/patternfly/images/pfbg_2000.jpg
  app/assets/patternfly/images/pfbg_576.jpg
  app/assets/patternfly/images/pfbg_576@2x.jpg
  app/assets/patternfly/images/pfbg_768.jpg
  app/assets/patternfly/images/pfbg_768@2x.jpg
  app/assets/patternfly/images/pfbg_992.jpg
  app/assets/patternfly/images/pfbg_992@2x.jpg
  app/assets/patternfly/pficon/pficon.eot
  app/assets/patternfly/pficon/pficon.scss
  app/assets/patternfly/pficon/pficon.svg
  app/assets/patternfly/pficon/pficon.ttf
  app/assets/patternfly/pficon/pficon.woff
  app/assets/patternfly/pficon/pficon.woff2
  app/assets/stylesheets/provider/_commons.scss
  app/assets/stylesheets/provider/_footer.scss
  app/assets/stylesheets/provider/_header.scss
  app/assets/stylesheets/provider/_patternfly_ie11.scss
  app/assets/stylesheets/provider/_theme.scss
  app/assets/stylesheets/provider/_vertical_nav.scss
  app/assets/stylesheets/provider/layouts/_main.scss
Labels: Priority: High

#932 Slightly improve loading Stats screen
  app/assets/stylesheets/provider/stats/_base.scss
Labels: Priority: Low
