Repository 3scale/porta, pull requests merged in 2020-12, with the labels that each got.

#2295 Make APIAP always enabled in code level; ignore yaml config
  app/lib/logic/rolling_updates.rb
Labels: Remove non-APIAP

#2294 Remove non-APIAP code in Account Signup / Service creation
  app/services/service_creator.rb
  test/unit/db/seeds_test.rb
  test/unit/services/service_creator_test.rb
  test/unit/signup/account_manager_test.rb
Labels: Remove non-APIAP

#2274 Remove rolling update independent_mapping_rules
  app/assets/javascripts/mapping_rules.js
  app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
  app/controllers/api/proxy_rules_controller.rb
  app/helpers/vertical_nav_helper.rb
  app/lib/logic/rolling_updates.rb
  app/models/account.rb
  app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
  app/views/api/proxy_rules/index.html.slim
  app/views/shared/provider/navigation/service/_integration.html.slim
  config/examples/rolling_updates.yml
  features/old/proxy.feature
  features/provider/integration/staging_environment.feature
  features/step_definitions/api/staging_environment_steps.rb
  features/step_definitions/proxy_steps.rb
  test/integration/api/proxy_rules_controller_test.rb
Labels: Remove non-APIAP, ruby

#2275 Add XML/JSON pagination metadata
  app/lib/pagination_helper.rb
  app/lib/three_scale/api/collection.rb
  app/lib/three_scale/collection_representer.rb
  app/lib/three_scale/json_representer.rb
  test/integration/user-management-api/base_controller_test.rb
  test/test_helpers/represented_api_routing.rb
  test/unit/three_scale/api/collection_test.rb
Labels: Priority: Low, enhancement, ruby

#2296 Remove redundant method #path_to_service
  app/decorators/service_decorator.rb
  app/helpers/services_helper.rb
  app/helpers/vertical_nav_helper.rb
  app/views/api/services/show.html.slim
  app/views/provider/admin/dashboards/widgets/_service_navigations.html.slim
  app/views/shared/provider/navigation/service/_integration.html.slim
Labels: Remove non-APIAP

#2291 Remove test_state_modifier method and unused styles
  app/assets/stylesheets/provider/_settings_box.scss
  app/presenters/api/integrations_show_presenter.rb
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
  test/unit/presenters/api/integrations_show_presenter_test.rb
Labels: Remove non-APIAP

#2304 Bump Stripe to 5.28.0
  Gemfile.base
  Gemfile.lock
Labels: Priority: High, ruby, tech-debt

#2287 Remove apiap? method
  app/controllers/api/integrations_controller.rb
  app/controllers/api/services_controller.rb
  app/controllers/frontend_controller.rb
  app/presenters/api/integrations_show_presenter.rb
  app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
  app/views/api/integrations/apicast/shared/_deployment_options.html.slim
  app/views/api/integrations/show.html.slim
  app/views/api/metrics/_link_to_mapping_rules.slim
  app/views/api/metrics/index.html.slim
  app/views/api/services/settings.html.slim
  app/views/api/services/show.html.slim
  app/views/provider/admin/dashboards/widgets/_service_navigations.html.slim
  app/views/provider/admin/dashboards/widgets/_service_top_traffic.html.slim
  app/views/provider/admin/onboarding/wizard/info/explain.html.slim
  app/views/provider/admin/onboarding/wizard/request/new.html.slim
  features/old/api/plans/service_plans.feature
  features/old/api/settings.feature
  features/old/proxy.feature
  features/old/services/multiservice.feature
  features/provider/integration/edit.feature
  features/provider/onboarding/wizard.feature
  test/integration/api/integrations_controller_test.rb
  test/integration/api/services_controller_test.rb
Labels: Remove non-APIAP, ruby

#2290 Remove unused code
  app/controllers/api/integrations_controller.rb
  app/models/proxy.rb
  features/step_definitions/proxy_steps.rb
  test/integration/api/integrations_controller_test.rb
  test/unit/proxy_test.rb
Labels: Remove non-APIAP

#2284 Remove provider_can_use usages
  app/controllers/api/integrations_controller.rb
  app/controllers/api/policies_controller.rb
  app/controllers/api_docs/services_controller.rb
  app/helpers/vertical_nav_helper.rb
  app/lib/backend_api_logic/proxy_extension.rb
  app/models/backend_api.rb
  app/services/proxy_test_service.rb
  app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
  app/views/api/integrations/apicast/script_driven/_staging.html.slim
  app/views/api/plans/_metrics.html.erb
  app/views/api/services/new.html.slim
  app/views/api/services/show.html.slim
  app/views/shared/provider/navigation/service/_integration.html.slim
  features/old/menu/api_menu.feature
  features/provider/onboarding/wizard.feature
  features/step_definitions/provider_steps.rb
  features/step_definitions/proxy_steps.rb
  features/support/paths.rb
  test/integration/api/integrations_controller_test.rb
  test/integration/api/services_controller_test.rb
  test/integration/api_docs/services_controller_test.rb
  test/models/backend_api_test.rb
  test/unit/proxy_test.rb
  test/unit/services/service_discovery/import_cluster_definitions_service_test.rb
Labels: Remove non-APIAP, ruby

#2303 [DOCs] Update INSTALL.md for Mac 11.0.1 Big Sur - DEC 2020
  INSTALL.md
Labels: Priority: Low

#2305 [DOC] Generate Liquid Drops MarkDown & HTML
  doc/liquid/drops.html
  doc/liquid/drops.md
Labels: Priority: Blocker

#2306 Remove PaymentGateway integration for 'Adyen'
  .rubocop_todo.yml
  Gemfile.base
  Gemfile.lock
  Gemfile.prod.lock
  app/controllers/admin/api/credit_cards_controller.rb
  app/lib/payment/adyen12_errors_handler.rb
  app/lib/payment_gateways/adyen12_crypt.rb
  app/lib/payment_gateways/buyer_references.rb
  app/models/payment_gateway.rb
  app/models/payment_transaction.rb
  app/views/payment_gateways/_adyen12.html.erb
  config/adyen_errors.yml
  config/initializers/active_merchant.rb
  config/initializers/inflections.rb
  doc/active_docs/Account Management API.json
  doc/licenses/licenses.xml
  doc/liquid/drops.html
  doc/liquid/drops.md
  features/developer_portal/admin/account/billing_and_credit_card_details.feature
  lib/developer_portal/app/controllers/developer_portal/admin/account/adyen12_controller.rb
  lib/developer_portal/app/views/developer_portal/accounts/payment_gateways/show.html.liquid
  lib/developer_portal/config/initializers/liquid.rb
  lib/developer_portal/config/routes.rb
  lib/developer_portal/lib/liquid/drops/account.rb
  lib/developer_portal/lib/liquid/tags/adyen12_form.rb
  test/functional/developer_portal/admin/account/adyen12_controller_test.rb
  test/test_helpers/active_merchant_test_helpers.rb
  test/unit/payment/adyen12_errors_handler_test.rb
  test/unit/payment_buyer_references_test.rb
  test/unit/payment_gateway_setting_test.rb
  test/unit/payment_gateway_test.rb
  test/unit/payment_gateways/adyen12_crypt_test.rb
Labels: Priority: Blocker, ruby, tech-debt

#2298 Rename some ocurrences of Service to Product
  app/controllers/provider/admin/service_discovery/services_controller.rb
  app/javascript/src/NewService/components/FormElements/FormWrapper.jsx
  app/javascript/src/NewService/components/ServiceDiscoveryForm.jsx
  app/models/service.rb
  app/views/api/services/_delete.html.slim
  app/views/api/services/edit.html.slim
  app/views/api/services/forms/_naming.html.slim
  app/views/api/services/settings.html.slim
  app/views/api/services/usage_rules.html.slim
  features/old/services/multiservice.feature
  test/workers/delete_plain_object_worker_test.rb
Labels: Remove non-APIAP
