Repository 3scale/porta, pull requests merged in 2020-10, with the labels that each got.

#2186 Add Product and Backends index
  app/controllers/api/services_controller.rb
  app/controllers/provider/admin/backend_apis_controller.rb
  app/views/api/services/index.html.slim
  app/views/provider/admin/backend_apis/index.html.slim
  config/routes.rb
  test/integration/api/services_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
Labels: ruby

#2193 Boilerplate for Ruby-React integration in the Dashboard
  app/controllers/provider/admin/dashboards_controller.rb
  app/javascript/packs/dashboard_backends_widget.js
  app/javascript/packs/dashboard_products_widget.js
  app/javascript/src/Dashboard/components/BackendsWidget.jsx
  app/javascript/src/Dashboard/components/ProductsWidget.jsx
  app/views/provider/admin/dashboards/_backends_widget.html.slim
  app/views/provider/admin/dashboards/_products_widget.html.slim
  app/views/provider/admin/dashboards/_section_products_and_backends.html.slim
  app/views/provider/admin/dashboards/show.html.slim
Labels: javascript, ruby

#2199 Removes services from the ApiSelector (aka ContextSwitcher)
  app/decorators/application_decorator.rb
  app/decorators/backend_api_decorator.rb
  app/decorators/service_decorator.rb
  app/helpers/menu_helper.rb
  app/javascript/packs/api_selector.js
  app/javascript/packs/navigation.js
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/javascript/src/Navigation/styles/ContextSelector.scss
  app/javascript/src/utilities/useClickOutside.js
  app/views/shared/_api_selector.html.slim
  spec/javascripts/Navigation/ContextSelector.spec.jsx
  spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
Labels: javascript, ruby

#2156 Improve performance in API Services List
  app/controllers/admin/api/services_controller.rb
  db/migrate/20200921135637_add_index_to_services_account_id_and_state.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
  test/factories/simple.rb
  test/integration/admin/api/services_controller_test.rb
Labels: Priority: High, enhancement, ruby

#2201 API Endpoint Provider ProxyConfig List
  app/controllers/admin/api/account/proxy_configs_controller.rb
  config/routes.rb
  test/integration/admin/api/account/proxy_configs_controller_test.rb
Labels: Priority: Blocker, feature, ruby

#2198 Add dashboard widgets
  app/controllers/api/services_controller.rb
  app/controllers/provider/admin/backend_apis_controller.rb
  app/javascript/packs/backend_apis_index.js
  app/javascript/packs/products_index.js
  app/javascript/src/BackendApis/components/IndexPage.js
  app/javascript/src/BackendApis/styles/backends.scss
  app/javascript/src/Dashboard/components/APIDataListItem.jsx
  app/javascript/src/Dashboard/components/BackendsWidget.jsx
  app/javascript/src/Dashboard/components/ProductsWidget.jsx
  app/javascript/src/Dashboard/styles/dashboard.scss
  app/javascript/src/Products/components/IndexPage.js
  app/javascript/src/Products/components/styles/products.scss
  app/javascript/src/patternflyStyles/dashboard.css
  app/views/api/services/index.html.slim
  app/views/provider/admin/backend_apis/index.html.slim
  app/views/provider/admin/dashboards/show.html.slim
  package.json
  yarn.lock
Labels: javascript

#2204 [Hotfix] Sphinx search Service & BackendAPI
  app/indices/backend_api_index.rb
  app/indices/service_index.rb
  app/models/backend_api.rb
  app/models/service.rb
Labels: Priority: Blocker, bug, ruby

#2203 🚧 Searchbar for Products and Backends
  app/controllers/api/services_controller.rb
  app/controllers/provider/admin/backend_apis_controller.rb
  app/indices/backend_api_index.rb
  app/indices/service_index.rb
  app/javascript/src/BackendApis/components/IndexPage.js
  app/javascript/src/Products/components/IndexPage.js
  app/models/backend_api.rb
  app/models/service.rb
Labels: javascript, ruby

#2205 ActiveDocs for Proxy Configs List (Provider)
  app/controllers/admin/api/account/proxy_configs_controller.rb
  app/controllers/admin/api/services/proxy/configs_controller.rb
  doc/active_docs/Account Management API.json
Labels: Priority: Blocker, enhancement

#2194 New Dashboard widgets for 2.10 ER1
  app/controllers/api/services_controller.rb
  app/controllers/provider/admin/backend_apis_controller.rb
  app/controllers/provider/admin/dashboards_controller.rb
  app/decorators/application_decorator.rb
  app/decorators/backend_api_decorator.rb
  app/decorators/service_decorator.rb
  app/indices/backend_api_index.rb
  app/indices/service_index.rb
  app/javascript/packs/PF4Styles/dashboard.js
  app/javascript/packs/backend_apis_index.js
  app/javascript/packs/dashboard_backends_widget.js
  app/javascript/packs/dashboard_products_widget.js
  app/javascript/packs/products_index.js
  app/javascript/src/BackendApis/components/IndexPage.js
  app/javascript/src/BackendApis/styles/backends.scss
  app/javascript/src/Dashboard/components/APIDataListItem.jsx
  app/javascript/src/Dashboard/components/BackendsWidget.jsx
  app/javascript/src/Dashboard/components/ProductsWidget.jsx
  app/javascript/src/Dashboard/styles/dashboard.scss
  app/javascript/src/Form/FormFieldset.jsx
  app/javascript/src/Products/components/IndexPage.js
  app/javascript/src/Products/components/styles/products.scss
  app/javascript/src/patternflyStyles/dashboard.css
  app/models/backend_api.rb
  app/models/service.rb
  app/views/api/services/index.html.slim
  app/views/provider/admin/backend_apis/index.html.slim
  app/views/provider/admin/dashboards/_backends_widget.html.slim
  app/views/provider/admin/dashboards/_products_widget.html.slim
  app/views/provider/admin/dashboards/_section_products_and_backends.html.slim
  app/views/provider/admin/dashboards/show.html.slim
  config/routes.rb
  features/old/accounts/invitations.feature
  features/old/api/alerts.feature
  features/old/api/plans/plan.feature
  features/old/authorization/provider_plans_section.feature
  features/old/authorization/provider_stats.feature
  features/old/menu/api_menu.feature
  features/old/menu/dashboard.feature
  features/old/services/multiservice.feature
  features/old/services/switch.feature
  features/old/stats/provider_side.feature
  features/provider/applications/managing.feature
  features/provider/applications/stats.feature
  features/provider/dashboard/tabs.feature
  features/provider/dashboard/widgets.feature
  features/step_definitions/applications/applications_steps.rb
  features/step_definitions/custom_web_steps.rb
  features/step_definitions/dashboard_steps.rb
  features/support/selectors.rb
  package.json
  test/integration/api/services_controller_test.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  yarn.lock
Labels: javascript, ruby

#2215 [Bugfix] Search of Service/BackendAPI for newly created items (index immediately) + Cleanup + Tests
  app/concerns/searchable.rb
  app/models/backend_api.rb
  app/models/service.rb
  test/integration/provider/admin/backend_apis_controller_test.rb
  test/integration/service_not_deleted_test.rb
  test/unit/backend_api/search_test.rb
  test/unit/service/search_test.rb
  test/unit/tasks/services_test.rb
Labels: Priority: High, bug, cleanup, ruby

#2218 Bump Liquid to 3.0.6
  Gemfile.lock
  Gemfile.prod.lock
  lib/developer_portal/developer_portal.gemspec
Labels: Priority: Low, enhancement, ruby

#2225 [Bugfix] NoMethodError: undefined method 'multiple_applications' for nil:NilClass
  app/models/account.rb
  test/unit/account_test.rb
Labels: Priority: Low, bug, ruby

#2220 [Refactor] Service deletion async without the scenario of not having the RU APIAP
  app/subscribers/service_deletion_subscriber.rb
  app/workers/delete_object_hierarchy_worker.rb
  app/workers/delete_service_hierarchy_worker.rb
  test/subscribers/service_deletion_subscriber_test.rb
  test/workers/delete_account_hierarchy_worker_test.rb
  test/workers/delete_object_hierarchy_worker_test.rb
  test/workers/delete_service_hierarcy_worker_test.rb
Labels: Priority: Low, cleanup, ruby

#2223 Sphinx indexation rake task accepts param for specific classes to index
  lib/tasks/sphinx.rake
Labels: Priority: Blocker, ruby

#2195 👷 bump codeclimate version
  .codeclimate.yml
Labels: hacktoberfest-accepted

#2227 Fix ContextSelector title
  app/controllers/api/services_controller.rb
  app/controllers/provider/admin/backend_apis_controller.rb
  app/javascript/packs/api_selector.js
  app/javascript/src/Navigation/components/ActiveMenuTitle.jsx
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/javascript/src/Types/NavigationTypes.jsx
  app/views/layouts/provider.html.slim
  app/views/shared/_api_selector.html.slim
  features/old/services/multiservice.feature
  spec/javascripts/Navigation/ActiveMenuTitle.spec.jsx
  spec/javascripts/Navigation/ContextSelector.spec.jsx
  spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
Labels: javascript, ruby

#2232 Add "is-expanded" class in Context Switcher for easier testing
  app/javascript/src/Navigation/components/ContextSelector.jsx
  spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
Labels: javascript

#2228 Move Settings out of Masthead into Context Switcher
  app/helpers/menu_helper.rb
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/views/shared/_api_selector.html.slim
  app/views/shared/provider/_header.html.slim
  features/old/accounts/accounts.feature
  features/old/accounts/password_change.feature
  features/old/accounts/personal_details.feature
  features/old/providers/invitations.feature
  features/step_definitions/invitations_steps.rb
  features/step_definitions/navigation_steps.rb
  spec/javascripts/Navigation/ContextSelector.spec.jsx
  spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
Labels: javascript, ruby
