Repository 3scale/porta, pull requests merged in 2020-02, with the labels that each got.

#1608 [Rails5] Fix initializers for rails5
  app/lib/three_scale/filter_arguments.rb
  config/initializers/audited_hacks.rb
  config/initializers/bugsnag.rb
  config/initializers/sidekiq.rb
  lib/three_scale/sidekiq_retry_support.rb
Labels: rails-5.0

#1627 Change some tests for rails5
  test/functional/master/events/imports_controller_test.rb
  test/integration/developer_portal/invitation_signup_test.rb
  test/integration/master/events/imports_controller_test.rb
Labels: rails-5.0

#1614 [Rails 5] Remove config.allow_concurrency = false. It causes the session to be reset
  config/environments/test.rb
Labels: rails-5.0

#1625 Moving icon to submenu when expanded
  app/assets/stylesheets/provider/_vertical_nav.scss
  app/helpers/vertical_nav_helper.rb
  app/javascript/src/Navigation/components/VerticalNav.jsx
Labels: javascript

#1628 [Rails 5] [deprecation] Use 'prepend module' instead of alias_method_chain
  app/models/account/provider_methods.rb
  app/models/payment_transaction.rb
  config/initializers/autosave_fix.rb
  config/initializers/cancan_hacks.rb
  config/initializers/lazy_initialization.rb
  features/support/capybara.rb
  lib/developer_portal/lib/liquid/xss_protection.rb
  lib/three_scale/lazy_initialization.rb
Labels: rails-5.0

#1630 Fix Service Settings' null pointer exception
  app/javascript/src/Settings/authentication-widget.jsx
Labels: Priority: High, javascript

#1531 [Refactor] [Tech-debt] Signup logic for provider is sparsed
  app/controllers/partners/base_controller.rb
  app/controllers/partners/providers_controller.rb
  app/controllers/provider/signups_controller.rb
  app/lib/logic/provider_signup.rb
  app/models/account/provider_domains.rb
  features/support/test_helpers.rb
  test/functional/partners/providers_controller_test.rb
  test/integration/provider/signups_controller_test.rb
  test/test_helpers/account.rb
  test/unit/account_test.rb
  test/unit/logic/provider_signup_test.rb
Labels: Priority: Low, cleanup, ruby

#1633 [Rails 5] Mock ThreeScale:::Core::ServiceError
  test/test_helpers/backend.rb
Labels: rails-5.0

#1632 [Rails 5] Fix Tests: Pdf::Finance::InvoiceReportDataTest & NotificationMailerTest
  test/mailers/notification_mailer_test.rb
  test/unit/pdf/finance/invoice_report_data_test.rb
Labels: rails-5.0

#1641 Fix acceptance spec for plans
  app/models/application_plan.rb
Labels: rails-5.0

#1646 Fix not inflected admin/api
  test/integration/admin/api/accounts_controller_test.rb
  test/integration/admin/api/backend_apis/mapping_rules_controller_test.rb
  test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
  test/integration/admin/api/backend_apis/metrics_controller_test.rb
  test/integration/admin/api/backend_apis_controller_test.rb
  test/integration/admin/api/services/backend_usages_controller_test.rb
  test/integration/provider/admin/cms/layouts_test.rb
  test/unit/concerns/background_deletion_test.rb
Labels: rails-5.0

#1645 [Rails5] Eager load test environment
  config/environments/test.rb
Labels: rails-5.0

#1644 [Rails5] Fix change in ActionController::Parameters#slice!
  app/services/service_creator.rb
Labels: rails-5.0

#1643 [Rails5] Fix account_plan_spec.rb related to controller.stale?
  app/lib/three_scale/api/responder.rb
  test/integration/admin/api/account_plans_controller_test.rb
Labels: rails-5.0

#1642 Lock sidekiq to ~> 4.2
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: rails-5.0

#1637 [Rails 5] Fix filter arguments when argument is a Struct
  app/lib/three_scale/filter_arguments.rb
Labels: rails-5.0

#1649 private define_method in ruby 2.4
  lib/three_scale/lazy_initialization.rb
Labels: rails-5.0, ruby

#1634 [Rails 5][config] Increase database pool to 25 or use RAILS_MAX_THREADS env
  config/examples/database.yml
Labels: rails-5.0

#1557 Get rid of deprecation warning about :text format in render
  app/controllers/provider/admin/webhooks_controller.rb
  lib/developer_portal/app/controllers/developer_portal/cms/new_content_controller.rb
Labels: rails-5.0

#1631 [Rails 5][Deprecation] Remove some deprecation warnings
  app/helpers/column_sorting_helper.rb
  app/lib/three_scale/search.rb
  app/models/cms/email_template.rb
Labels: rails-5.0

#1657 [hotfix] Require threescale.rb before any app initializers
  config/application.rb
Labels: Priority: Blocker, ruby

#1609 [Rails 5] Refactor Test ExtraFieldsTest
  test/unit/extra_fields_test.rb
Labels: Priority: Blocker, cleanup, rails-5.0, ruby

#1606 [Makefile] Produce reproducible docker-compose
  Makefile
  docker-compose.yml
Labels: rails-5.0

#1679 [hotfix] Allow ActionController::Parameters for email template heades
  app/models/cms/email_template.rb
  test/unit/cms/email_template_test.rb
Labels: bug

#1684 ✅ Fix SwitchesController test
  test/integration/admin/cms/switches_controller_test.rb
Labels: ruby

#1688 Allow reset password in master provider
  app/controllers/provider/passwords_controller.rb
  test/functional/provider/passwords_controller_test.rb
  test/integration/provider/passwords_test.rb
Labels: ruby

#1685 [Bugfix] Ensure that all associations of the BackgroundDeletion config can be constantized
  app/models/account.rb
  app/models/user.rb
  test/unit/concerns/background_deletion_test.rb
Labels: Priority: Blocker, bug, ruby

#1690 Fix Deadlock destroying plans by association without updating the position within the service
  app/models/plan.rb
  test/workers/delete_plain_object_worker_test.rb
Labels: Priority: Blocker, bug, ruby

#1106 Fixes spec for ApiFilter component
  spec/javascripts/Dashboard/ApiFilter.spec.jsx
Labels: javascript

#1470 New Deployment Service for Proxy
  app/controllers/admin/api/services/proxies_controller.rb
  app/controllers/admin/api/services/proxy/policies_controller.rb
  app/controllers/api/integrations_controller.rb
  app/forms/onboarding/request_form.rb
  app/models/proxy.rb
  app/services/apicast_v1_deployment_service.rb
  app/services/proxy_deployment_service.rb
  app/workers/proxy_deployment_worker.rb
  test/functional/api/integrations_controller_test.rb
  test/functional/provider/admin/onboarding/wizard/request_controller_test.rb
  test/integration/api/integrations_controller_test.rb
  test/integration/user-management-api/services/proxies_test.rb
  test/unit/forms/onboarding/request_form_test.rb
  test/unit/proxy_test.rb
  test/unit/services/apicast_v1_deployment_service_test.rb
  test/unit/services/proxy_deployment_service_test.rb
Labels: ruby

#1694 🐛 Fix double slashes in Integration Show
  app/helpers/api/integrations_helper.rb
  test/unit/helpers/api/integrations_helper_test.rb
Labels: 2.8 ER2, Priority: High, ruby

#1708 Fix deploy to OCP with PostgreSQL
  lib/tasks/db.rake
  openshift/system/config/database.yml
Labels: 2.8 ER2

#1705 oidc auth flow warning message for both apiap and non apiap services …
  app/views/api/integrations/apicast/shared/_oidc.html.slim
  app/views/api/services/forms/_oidc.html.slim
  config/locales/en.yml
Labels: 2.8 ER2

#1658 Refactoring ProxyConfigAffectingChanges
  app/controllers/application_controller.rb
  app/lib/proxy_config_affecting_changes.rb
  app/models/backend_api.rb
  app/models/backend_api_config.rb
  app/models/proxy.rb
  app/models/proxy_rule.rb
  app/models/service.rb
  test/integration/application_controller_test.rb
  test/models/backend_api_config_test.rb
  test/models/backend_api_test.rb
  test/test_helpers/proxy_config_affecting_changes.rb
  test/unit/proxy_config_affecting_changes_test.rb
  test/unit/proxy_rule_test.rb
  test/unit/proxy_test.rb
  test/unit/service_test.rb
Labels: 2.8 ER2

#1710 APIAP small ux improvements
  app/assets/stylesheets/provider/_commons.scss
  app/controllers/admin/api/backend_apis_controller.rb
  app/views/api/backend_usages/edit.html.slim
  app/views/api/backend_usages/index.html.slim
  app/views/provider/admin/backend_apis/forms/_naming.html.slim
  config/locales/en.yml
Labels: 2.8 ER2

#1664 Adding PF4 styles to change password
  .flowconfig
  app/controllers/provider/passwords_controller.rb
  app/javascript/packs/ChangePassword.js
  app/javascript/src/ChangePassword/components/ChangePassword.jsx
  app/javascript/src/ChangePassword/components/PasswordInput.jsx
  app/javascript/src/ChangePassword/index.jsx
  app/javascript/src/LoginPage/assets/styles/loginPage.scss
  app/javascript/src/LoginPage/utils/formValidation.js
  app/javascript/src/Types/libs/libdefs.js
  app/presenters/password_presenter.rb
  app/views/provider/passwords/show.html.erb
  spec/javascripts/ChangePassword/ChangePassword.spec.jsx
  spec/javascripts/ChangePassword/__snapshots__/ChangePassword.spec.jsx.snap
Labels: 2.8 ER2

#1671 4113-audit logs
  app/models/user.rb
  db/migrate/20200211080911_add_index_to_audits_auditable_id_auditable_type_version.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
Labels: 2.8 ER2

#1712 Downgrades rack from 2.2.2 back to 2.0.9
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: 2.8 ER2

#1701 Disable Reset Password for Master account
  app/controllers/provider/passwords_controller.rb
  app/javascript/src/LoginPage/LoginPageWrapper.jsx
  app/views/provider/sessions/new.html.slim
  config/routes.rb
  features/old/accounts/password_reset.feature
  features/step_definitions/url_steps.rb
  spec/javascripts/LoginPage/LoginPageWrapper.spec.jsx
  test/integration/provider/passwords_test.rb
Labels: 2.8 ER2

#1714 [rake] Task to reset password of a User of Master tenant
  lib/tasks/password_reset.rake
Labels: 2.8 ER2

#1717 [gem] Update to mysql2 0.5.3
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: dependencies, ruby

#1720 [Bugfix] InvalidForeignKey deleting an account while persisting its payment detail
  app/models/account/payment_details.rb
  app/models/account/states.rb
  test/unit/account/payment_details_test.rb
Labels: Priority: High, bug, ruby

#1726 [memory-bloat] Do not use batch on pdf worker
  app/lib/pdf/dispatch.rb
Labels: ruby

#1723 [Bugfix] DB timeout deleting many records at once
  app/workers/delete_plain_object_worker.rb
Labels: Priority: Blocker, bug, ruby
