Repository 3scale/porta, pull requests merged in 2020-03, with the labels that each got.

#1736 Fix HttpBasicAuth security scope check in api calls
  app/lib/api_authentication/by_access_token.rb
  test/integration/by_access_token_test.rb
Labels: bug

#1734 Default EndUser related fields to null in the DB
  db/migrate/20200224095152_default_nil_fields_end_user_removal.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
Labels: Priority: Blocker, ruby

#1738 Remove EndUser and EndUserPlans [triggers]
  lib/system/database/definitions/mysql.rb
  lib/system/database/definitions/oracle.rb
  lib/system/database/definitions/postgres.rb
Labels: Priority: Blocker, ruby

#1413 Find the metric generated by an alert on BackendApi metric
  app/models/cinstance.rb
  test/unit/alert/alert_methods_test.rb
Labels: APIAP, bug

#1754 Fix HTTP BasicAuth when using ProviderKey
  app/lib/api_authentication/by_access_token.rb
  test/integration/by_access_token_test.rb
  test/integration/by_provider_key_test.rb
Labels: bug

#1757 Use consistent absolute paths
  portafly/src/App.tsx
  portafly/src/components/AppLayout.tsx
  portafly/src/components/AppNavExpandable.tsx
  portafly/src/components/AppNavGroup.tsx
  portafly/src/components/FormatDate.tsx
  portafly/src/components/LazyRoute.tsx
  portafly/src/components/NotFound.tsx
  portafly/src/components/SwitchWith404.tsx
  portafly/src/components/util/useBreadcrumb.ts
  portafly/src/index.tsx
  portafly/src/pages/Applications.tsx
  portafly/src/pages/Overview.tsx
  portafly/src/root.ts
  portafly/src/tests/App.test.tsx
  portafly/src/tests/components/AppLayout.test.tsx
  portafly/src/tests/components/AppNavExpandable.test.tsx
  portafly/src/tests/components/AppNavGroup.test.tsx
  portafly/src/tests/components/AppNavItem.test.tsx
  portafly/src/tests/components/FormatDate.test.tsx
  portafly/src/tests/components/LazyRoute.test.tsx
  portafly/src/tests/components/SwitchWith404.test.tsx
  portafly/src/tests/components/util/useA11yRoute.test.tsx
  portafly/src/tests/components/util/useBreadcrumb.test.tsx
  portafly/src/tests/components/util/useDocumentTitle.test.tsx
  portafly/tsconfig.json
  portafly/tsconfig.paths.json
Labels: javascript, portafly

#1769 [oracle] Fix sphinx delta not using correct datatypes
  config/initializers/oracle.rb
Labels: Priority: Blocker

#1761 [Bugfix & Refactor] Improve validation of URIs.
  app/models/backend_api.rb
  app/services/service_creator.rb
  app/validators/uri_validator.rb
  config/locales/en.yml
  test/unit/proxy_test.rb
  test/unit/services/service_creator_test.rb
  test/unit/validators/uri_validator_test.rb
Labels: bug, cleanup, ruby

#1744 [Bugfix] ServiceDeletedEvent never saves the entire provider object
  app/events/services/service_deleted_event.rb
  test/events/services/service_deleted_event_test.rb
Labels: bug, ruby

#1791 [oracle] Migration for all timestamps
  app/models/invoice.rb
  db/migrate/20200324130825_change_date_to_timestamp.rb
  db/oracle_schema.rb
  db/postgres_schema.rb
  db/schema.rb
Labels: Priority: Blocker, oracle, ruby

#1780 Add validation to trial period, setup fee and cost per month
  app/models/plan.rb
  test/unit/plan_test.rb
Labels: ruby

#1788 Ejecting react-scripts
  .codeclimate.yml
  portafly/.eslintignore
  portafly/config/env.js
  portafly/config/getHttpsConfig.js
  portafly/config/jest/cssTransform.js
  portafly/config/jest/fileTransform.js
  portafly/config/modules.js
  portafly/config/paths.js
  portafly/config/pnpTs.js
  portafly/config/webpack.config.js
  portafly/config/webpackDevServer.config.js
  portafly/package.json
  portafly/scripts/build.js
  portafly/scripts/start.js
  portafly/scripts/test.js
  portafly/src/react-app-env.d.ts
  portafly/yarn.lock
Labels: portafly
