Repository 3scale/porta, pull requests merged in 2020-08, with the labels that each got.

#2097 [UX specs] Update Edit product page specs
  portafly/doc/ux_specs/product/edit_product.md
Labels: portafly

#2096 [UX specs] Update Create product page specs
  portafly/doc/ux_specs/product/create_product.md
Labels: portafly

#2103 Check can? the same way for Decorators as for their ActiveRecord Models
  app/models/ability.rb
  test/unit/abilities/ability_test.rb
Labels: Priority: Blocker, bug, ruby

#2065 5640-Product_EditProduct microcopy for Product > Edit Product
  portafly/src/i18n/locales/en/product.yml
  portafly/src/i18n/locales/en/shared.yml
Labels: UI Strings, portafly

#2072 5639-Product_CreateProduct UI Strings
  portafly/src/i18n/locales/en/product.yml
  portafly/src/i18n/locales/en/shared.yml
Labels: UI Strings, portafly

#2104 Move '.decorate' Views->Controller for 'admin_buyers_user*' paths
  app/controllers/buyers/users_controller.rb
  app/views/buyers/users/edit.html.erb
  app/views/buyers/users/index.html.erb
  app/views/buyers/users/show.html.erb
  test/integration/buyers/users_controller_test.rb
Labels: Priority: Low, cleanup, ruby, tech-debt

#2109 Move '.decorate' from View to Controller for buyers/accounts/bulk/_selected_accounts
  app/controllers/buyers/accounts/bulk/base_controller.rb
  app/views/buyers/accounts/bulk/_selected_accounts.html.erb
  test/integration/buyers/accounts/bulk/change_plans_controller_test.rb
Labels: Priority: Low, cleanup, ruby, tech-debt

#2110 Move 'decorate' Views=>Controller for Buyers::AccountsController
  app/controllers/buyers/accounts_controller.rb
  app/views/buyers/accounts/_search_results.html.slim
  app/views/buyers/accounts/show.html.slim
  test/integration/buyers/accounts_controller_test.rb
Labels: Priority: Low, cleanup, ruby, tech-debt

#2111 Move '.decorate' from view to controller in api/proxy_configs/index
  app/controllers/api/proxy_configs_controller.rb
  app/decorators/proxy_config_decorator.rb
  app/views/api/proxy_configs/index.html.slim
  test/decorators/proxy_config_decorator_test.rb
  test/integration/api/proxy_configs_controller_test.rb
Labels: Priority: Low, cleanup, ruby, tech-debt

#2112 Get rid of InheritedResources for Buyers::UsersController
  app/controllers/buyers/users_controller.rb
  app/lib/fields/fields.rb
  app/views/buyers/users/edit.html.erb
  app/views/buyers/users/index.html.erb
  app/views/buyers/users/show.html.erb
  test/integration/buyers/users_controller_test.rb
Labels: Priority: Low, cleanup, ruby, tech-debt

#2092 Deliver invitations async and fix notification message
  app/controllers/buyers/invitations_controller.rb
  app/controllers/provider/admin/account/invitations_controller.rb
  app/helpers/invitations_helper.rb
  app/models/invitation.rb
  app/workers/send_user_invitation_worker.rb
  features/step_definitions/providers/invitations_steps.rb
  test/unit/invitation_test.rb
  test/workers/send_user_invitation_worker_test.rb
Labels: ruby

#2107 Remove '.decorate' from app/views/buyers/*/bulk for contracts
  app/controllers/buyers/applications/bulk/base_controller.rb
  app/controllers/buyers/service_contracts/bulk/base_controller.rb
  app/decorators/contract_decorator.rb
  app/views/buyers/applications/bulk/_selected_applications.html.erb
  app/views/buyers/service_contracts/bulk/_selected_contracts.html.erb
  features/old/applications/providers/bulk_operations/change_states.feature
  features/old/services/subscriptions/bulk_operations/change_plans.feature
  features/old/services/subscriptions/bulk_operations/change_states.feature
  test/decorators/contract_decorator_test.rb
  test/integration/buyers/applications/bulk/change_plans_controller_test.rb
  test/integration/buyers/service_contracts/bulk/change_plans_controller_test.rb
Labels: Priority: Low, cleanup, ruby, tech-debt

#2108 Decorate current_user and current_account before reaching the views.
  app/controllers/application_controller.rb
  app/controllers/provider/admin/user/base_controller.rb
  app/lib/decorator_additions.rb
  app/models/ability.rb
  app/views/provider/admin/accounts/suspended.html.slim
  app/views/provider/admin/onboarding/wizard/info/intro.html.slim
  app/views/shared/_service_access.slim
  app/views/shared/provider/_header.html.slim
Labels: Priority: Low, cleanup, ruby, tech-debt

#2130 Not displaying suspend button when tenant is deleted
  app/models/account/states.rb
  app/views/buyers/accounts/show.html.slim
  app/workers/process_notification_event_worker.rb
  test/integration/buyers/accounts_controller_test.rb
Labels: ruby

#2117 [UX specs] Backend / Overview page
  portafly/doc/ux_specs/backend/overview.md
  portafly/doc/ux_specs/index.md
Labels: portafly

#2114 [UX specs] Create Backend page
  portafly/doc/ux_specs/backend/create_backend.md
  portafly/doc/ux_specs/index.md
Labels: portafly

#2115 [UX specs] Edit Backend page
  portafly/doc/ux_specs/backend/edit_backend.md
  portafly/doc/ux_specs/index.md
Labels: portafly

#2144 [UX specs] Empty states global components
  portafly/doc/ux_specs/global_components/empty_states.md
  portafly/doc/ux_specs/index.md
Labels: portafly

#2145 [UX specs] Add backend to product page
  portafly/doc/ux_specs/backend/add_backend_to_product.md
  portafly/doc/ux_specs/index.md
Labels: portafly
