Repository 3scale/porta, pull requests merged in 2020-11, with the labels that each got.

#2237 Rename Dashboard cards "recently updated" column
  app/javascript/src/Dashboard/components/BackendsWidget.jsx
  app/javascript/src/Dashboard/components/ProductsWidget.jsx
Labels: javascript

#2234 Clean up dashboard tabs and old widgets
  app/assets/stylesheets/provider/admin/_dashboard.scss
  app/helpers/provider/admin/dashboards_helper.rb
  app/javascript/packs/api_as_product.js
  app/javascript/packs/dashboard.js
  app/javascript/packs/services_search_bar.js
  app/javascript/src/Dashboard/ajax-widget.jsx
  app/javascript/src/Dashboard/components/ApiFilter.jsx
  app/javascript/src/Dashboard/index.jsx
  app/javascript/src/Dashboard/styles/dashboard.scss
  app/javascript/src/Dashboard/tabs-widget.jsx
  app/javascript/src/Dashboard/toggle.jsx
  app/views/provider/admin/dashboards/_ajax_load.html.slim
  app/views/provider/admin/dashboards/_apiap_search_bar.html.slim
  app/views/provider/admin/dashboards/_list_backends.html.slim
  app/views/provider/admin/dashboards/_new_api_button.html.slim
  app/views/provider/admin/dashboards/_section_services.html.slim
  app/views/provider/admin/dashboards/_service.html.slim
  app/views/provider/admin/dashboards/_services_filter.html.slim
  app/views/provider/admin/dashboards/show.html.slim
  spec/javascripts/Dashboard/ApiFilter.spec.jsx
Labels: javascript

#2236 Add current API title above left nav
  app/javascript/packs/vertical_nav.js
  app/javascript/src/Navigation/components/VerticalNav.jsx
  app/javascript/src/Navigation/styles/VerticalNav.scss
  app/views/shared/provider/navigation/_vertical_nav.html.slim
  spec/javascripts/Navigation/VerticalNav.spec.jsx
Labels: javascript

#2240 💄 Fixes css overflow in VerticalNav
  app/javascript/src/Navigation/styles/VerticalNav.scss
Labels: javascript

#2245 [Refactor] Contract.permitted_for(user)
  app/models/contract.rb
  app/models/user.rb
  test/unit/contract_test.rb
Labels: Priority: Low, cleanup, enhancement, ruby

#2244 Hide services when user has no permission
  app/decorators/account_decorator.rb
  app/models/admin_section.rb
  app/models/user/permissions.rb
  app/views/provider/admin/dashboards/show.html.slim
  app/views/shared/_service_access.slim
  features/old/authorization/provider_plans_section.feature
  test/unit/user/permissions_test.rb
Labels: ruby

#2247 Remove Rake task 'destroy_orphans'
  lib/tasks/backend_api.rake
  test/unit/tasks/backend_api_test.rb
Labels: APIAP, cleanup, ruby

#2241 API Accounts/ProxyConfigs GET by host/version
  app/controllers/admin/api/account/proxy_configs_controller.rb
  app/models/proxy_config.rb
  doc/active_docs/Account Management API.json
  test/integration/admin/api/account/proxy_configs_controller_test.rb
Labels: Priority: Blocker, enhancement, ruby

#2248 👷 Update Codeclimate and Ruby Linters
  .codeclimate.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile.base
  Gemfile.lock
  Gemfile.prod.lock
Labels: ruby

#2254 Remove non-APIAP code in CurlCommandBuilder
  app/lib/apicast/curl_command_builder.rb
  app/models/proxy_config.rb
  test/unit/apicast/curl_command_builder_test.rb
  test/unit/helpers/api/integrations_helper_test.rb
Labels: Priority: Blocker, cleanup, ruby, tech-debt

#2255 [Doc][API] GET Account/ProxyConfigs: Find -> Filter
  app/controllers/admin/api/account/proxy_configs_controller.rb
  doc/active_docs/Account Management API.json
Labels: Priority: Low, UI Strings

#2257 Remove Products/Backends from Master Dashboard and Context Selector
  app/javascript/src/Navigation/components/ContextSelector.jsx
  app/views/provider/admin/dashboards/show.html.slim
  app/views/shared/_api_selector.html.slim
  features/master/menu/dashboard.feature
  features/old/menu/dashboard.feature
  features/step_definitions/header_steps.rb
  features/support/selectors.rb
  spec/javascripts/Navigation/ContextSelector.spec.jsx
  spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
Labels: javascript, ruby

#2261 Remove unused old endpoint /master/api/domain/:id
  app/controllers/master/api/domain_controller.rb
  app/lib/system/domain_info.rb
  config/routes.rb
  test/integration/master/api/domain_controller_test.rb
  test/unit/system/domain_info_test.rb
Labels: Priority: Blocker, cleanup, ruby, tech-debt

#2266 Clean proxy configs curl command builder and model scope for services
  app/lib/apicast/curl_command_builder.rb
  app/models/proxy_config.rb
Labels: Priority: High, cleanup, enhancement, ruby

#2267 Can't promote product config with Istio through UI
  app/models/proxy_config.rb
  test/unit/proxy_config_test.rb
Labels: ruby

#2281 [Bugfix] 'parsed_content' must be a public method
  app/models/proxy_config.rb
Labels: Priority: Blocker
