Repository 3scale/porta, pull requests merged in 2020-01, with the labels that each got.

#1520 Disable generate client secret button in Dev portal
  lib/developer_portal/lib/liquid/filters/rails_helpers.rb
Labels: ruby

#1521 Upgrade to ruby2 5
  .circleci/config.yml
  Dockerfile
  INSTALL.md
  app/lib/pdf/data.rb
  openshift/system/Dockerfile
  openshift/system/Dockerfile.on_prem
  openshift/system/contrib/scl_enable
Labels: ruby

#1526 Upgrade kgio gem from 2.10.0 to 2.11.3
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: ruby

#1527 Support websocket protocol in BackendApi
  app/models/backend_api.rb
  config/locales/en.yml
  test/models/backend_api_test.rb
Labels: ruby

#1545 Prevent member users from creating Services
  app/controllers/admin/api/services_controller.rb
  test/integration/admin/api/services_controller_test.rb
Labels: ruby

#1555 [Rails 5] find_templates 5th argument is optional
  lib/developer_portal/lib/liquid/template/fallback_resolver.rb
  lib/developer_portal/lib/liquid/template/resolver.rb
Labels: rails-5.0

#1554 [Rails 5] before_committed! for AfterCommitSubscriber
  app/models/web_hook/event.rb
  app/subscribers/after_commit_subscriber.rb
Labels: rails-5.0

#1556 [rails-5.0] scoped method in relation should be public
  app/models/system_operation.rb
Labels: rails-5.0

#1562 [Rails 5] silence_stream is removed from rails
  test/unit/backend/random_data_generator_test.rb
Labels: rails-5.0

#1564 [Rails 5] Add a little bit of information on invalid tenant_mode
  app/lib/three_scale.rb
Labels: rails-5.0

#1563 [Rails 5] ThreeScale::Core::AlertLimit.load_all mocked
  test/test_helpers/backend.rb
Labels: rails-5.0

#1575 [Rails 5] Use ApplicationRecord
  app/lib/three_scale/lazy_initialization.rb
Labels: rails-5.0

#1565 [Rails 5] Use Timecop to fix fraction of seconds lost in DB
  test/unit/user_test.rb
Labels: rails-5.0

#1579 [Rails 5] Fix protected_attributes_continued's evil monkey patch
  config/initializers/protected_attributes_hacks.rb
Labels: rails-5.0

#1585 [Rails 5] Update will_paginate to fix find_last(*args)
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: rails-5.0

#1582 [Rails 5] Fix ApiDocs::Service test with NotificationCenter enabled
  test/unit/api_docs/service_test.rb
Labels: rails-5.0

#1586 [Rails5] Fix Baby Squeel usage
  app/controllers/api/applications_controller.rb
  app/controllers/buyers/applications_controller.rb
  app/controllers/buyers/service_contracts_controller.rb
  app/models/contract.rb
  app/models/service.rb
  features/step_definitions/messages_steps.rb
  test/models/backend_api_config_test.rb
  test/unit/contract_test.rb
  test/unit/three_scale/search_test.rb
Labels: rails-5.0

#1587 EventStore::Event does not include BackgroundDeletion
  app/lib/event_store/event.rb
Labels: Priority: High, bug

#1592 [Rails5] Remove patch for CVE-2016-6316
  config/initializers/cve-2016-6316.rb
  test/cve/cve-2016-6316_test.rb
Labels: rails-5.0

#1604 [Rails5] Upgrade gems for rails5
  Gemfile.base
  Gemfile.lock
  gemfiles/prod/Gemfile.lock
Labels: rails-5.0

#1598 [Rails 5] Do not assert_equal nil values for ServiceContracts::ServiceContractCreatedEventTest
  test/events/service_contracts/service_contract_created_event_test.rb
Labels: rails-5.0

#1603 [WIP][Rails 5][test] Fix enqueuing with ActiveJob for DeletePlainObjectWorker
  test/workers/delete_plain_object_worker_test.rb
Labels: rails-5.0

#1599 [Rails 5] CMS::Portlet does not have attribute #description
  app/representers/cms/portlet_representer.rb
Labels: rails-5.0

#1600 [Rails 5] Race condition non requiring Stats::Service
  app/controllers/provider/admin/dashboard/service/hits_controller.rb
  app/controllers/provider/admin/dashboard/service/top_traffic_controller.rb
Labels: rails-5.0

#1583 [Rails 5] Add support for empty Arrays in params
  lib/developer_portal/app/controllers/developer_portal/signup_controller.rb
  test/functional/developer_portal/admin/plans_widget_controller_requiring_credit_card_test.rb
  test/functional/provider/admin/account/users_controller_test.rb
  test/integration/developer_portal/signup_test.rb
  test/integration/provider/admin/account/users_controller_test.rb
  test/test_helpers/rack_test_utils.rb
Labels: rails-5.0

#1602 [Rails 5] Use assert_in_delta because of DateTime in DB rounding usec to 0
  test/unit/invoice_test.rb
Labels: rails-5.0

#1576 [Rails5] [TEST] javascript cms switch
  test/integration/admin/cms/switches_controller_test.rb
Labels: rails-5.0

#1596 Fix CircleCI javascript_build errors
  .circleci/config.yml
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  karma.conf.js
  lib/developer_portal/lib/liquid/filters/rails_helpers.rb
  lib/tasks/assets.rake
  lib/tasks/webpack.rake
Labels: Priority: Blocker, javascript

#1548 Upgrade to NodeJS 10 in CircleCI
  .circleci/config.yml
  Dockerfile
  openshift/system/Dockerfile
  openshift/system/Dockerfile.on_prem
Labels: Priority: Blocker

#1616 [Rails 5] Use ActionController::Parameters for parameters comparison
  app/lib/api_support/params.rb
Labels: rails-5.0

#1612 [Rails 5] ProviderInvitationMailerTest Use assert_difference with block
  test/unit/mailers/provider_invitation_mailer_test.rb
Labels: rails-5.0

#1611 [Rails 5] ActionController::Parameters will not have #to_a
  app/presenters/dashboard_widget_presenter.rb
Labels: rails-5.0

#1610 [Rails 5] FieldsDefinition only_choices_for_text
  app/models/fields_definition.rb
Labels: rails-5.0

#1617 [Rails5] - Extract some tests changes
  test/functional/buyers/applications_controller_test.rb
  test/integration/api/backend_usages_controller_test.rb
  test/integration/buyers/accounts_controller_test.rb
  test/integration/master/providers/switches_controller_test.rb
  test/test_helpers/authentication.rb
  test/test_helpers/backend.rb
  test/unit/account_webhook_test.rb
  test/unit/application_plan_test.rb
  test/unit/contract_test.rb
  test/unit/invitation_test.rb
  test/unit/liquid/drops/plan_change_test.rb
  test/unit/mailers/account_mailer_test.rb
  test/unit/mailers/topic_mailer_test.rb
  test/unit/models_test.rb
  test/unit/proxy_rule_test.rb
  test/workers/create_service_token_worker_test.rb
  test/workers/destroy_all_deleted_objects_worker_test.rb
  test/workers/reverse_provider_key_worker_test.rb
  test/workers/web_hook_worker_test.rb
Labels: rails-5.0

#1594 Support OAS3 in Admin Portal (ActiveDocs)
  .flowconfig
  app/helpers/admin/api_docs_helper.rb
  app/javascript/packs/service_active_docs.js
  app/javascript/src/ActiveDocs/components/ActiveDocsSpec.jsx
  app/javascript/src/Types/libs/libdefs.js
  app/views/admin/api_docs/base/swagger.html.erb
  config/locales/en.yml
  doc/dependency_decisions.yml
  package-lock.json
  package.json
  spec/javascripts/ActiveDocs/ActiveDocsSpec.jsx
  spec/javascripts/ActiveDocs/__snapshots__/Spec.spec.jsx.snap
Labels: Priority: High, javascript

#1621 ActiveRecord::Relation#merge(nil) raises an error
  app/lib/logic/provider_settings.rb
Labels: rails-5.0

#1620 [Rails5] Fix ApplicationKey::without scope
  app/models/application_key.rb
  test/unit/application_keys_test.rb
Labels: rails-5.0

#1559 [CVE] Rails SQLi also check for ActionController::Parameters
  config/initializers/rails_sqli.rb
  test/unit/rails_sqli_test.rb
Labels: rails-5.0

#1622 AuthenticationProvider::AVAILABLE is an HashWithIndifferentAccess
  app/models/authentication_provider.rb
Labels: rails-5.0

#1623 [Rails5] Apply some fixes
  app/controllers/admin/api/services/proxy/policies_controller.rb
  app/lib/three_scale/api/responder.rb
  app/workers/billing_worker.rb
Labels: rails-5.0

#1466 Add Captcha to password reset form in Dev Portal
  lib/developer_portal/app/controllers/developer_portal/admin/account/passwords_controller.rb
  lib/developer_portal/app/views/developer_portal/password/new.html.liquid
  lib/developer_portal/lib/liquid/forms/base.rb
  lib/developer_portal/lib/liquid/forms/password_reset.rb
  lib/developer_portal/lib/liquid/forms/signup.rb
  lib/developer_portal/lib/liquid/forms/spam_protected.rb
  test/integration/developer_portal/password_reset_test.rb
  test/unit/liquid/forms_test.rb
  test/unit/liquid/tags/form_test.rb
Labels: Priority: High, ruby

#1595 Support OAS3 in Dev portal
  app/javascript/packs/active_docs.js
  app/javascript/src/ActiveDocs/swagger-ui-3-patch.scss
  app/lib/logic/provider_signup.rb
  features/old/liquid/active_docs_v1.feature
  features/old/liquid/active_docs_v2.feature
  features/old/liquid/active_docs_v3.feature
  features/old/providers/active_docs_v2.feature
  features/old/providers/active_docs_v3.feature
  features/provider/active_docs.feature
  features/services/active_docs.feature
  features/step_definitions/active_docs_steps.rb
  features/step_definitions/api_docs_step.rb
  features/step_definitions/web_steps.rb
  lib/developer_portal/app/views/developer_portal/docs.html.liquid
  lib/developer_portal/lib/liquid/filters/rails_helpers.rb
  package-lock.json
  package.json
Labels: javascript

#1618 [Rails5] Fix Line Item wrong type
  app/lib/finance/billing.rb
  config/locales/en.yml
Labels: rails-5.0
