Repository 3scale/porta, pull requests merged in 2021-07, with the labels that each got.

#2495 THREESCALE-7134 Removing v1_compatible
  app/forms/onboarding/request_form.rb
  app/models/proxy.rb
  app/services/proxy_deployment_service.rb
  test/integration/user-management-api/services/proxies_test.rb
  test/unit/proxy_test.rb
  test/unit/services/proxy_deployment_service_test.rb
Labels: Priority: Blocker, Remove non-APIAP

#2511 [THREESCALE-7134] Removal of the proxy logs high level
  app/controllers/api/proxy_logs_controller.rb
  app/views/api/proxy_logs/index.html.erb
  config/routes.rb
Labels: Remove non-APIAP

#2517 [THREESCALE-7134] Removing the nginx proxy
  app/lib/logic/nginx_proxy.rb
  app/models/account.rb
  app/services/proxy_deployment_service.rb
  test/unit/logic/nginx_proxy_test.rb
  test/unit/services/proxy_deployment_service_test.rb
Labels: Remove non-APIAP

#2523 [THREESCALE-7134] Remove show method from the nginxes controller
  app/controllers/admin/api/nginxes_controller.rb
  config/routes.rb
  test/functional/admin/api/nginxes_controller_test.rb
  test/integration/user-management-api/nginx_test.rb
Labels: Remove non-APIAP

#2519 [THREESCALE-7134] Removes the apicast zip generator
  app/lib/apicast/zip_generator.rb
  test/unit/apicast/zip_generator_test.rb
Labels: Remove non-APIAP

#2507 Remove apiap from file names
  app/javascript/packs/wizard_backend_api.js
  app/views/provider/admin/onboarding/wizard/backend_api/new.html.slim
  features/step_definitions/onboarding/wizard_steps.rb
  features/step_definitions/onboarding/wizard_steps.rb.rb
Labels: ruby

#2500 removing deployment service class
  app/services/apicast_v1_deployment_service.rb
  app/workers/proxy_deployment_worker.rb
  test/unit/proxy_test.rb
  test/unit/services/apicast_v1_deployment_service_test.rb
Labels: Remove non-APIAP

#2508 [THREESCALE-7134] Removing SandboxProviderConfGenerator class since it is used only in ApicastV1DeploymentService class
  app/lib/apicast/sandbox_provider_conf_generator.rb
  test/unit/apicast/sandbox_provider_conf_generator_test.rb
Labels: Remove non-APIAP

#2538 [THREESCALE-7134] Remove apicast sandbox
  app/lib/apicast/sandbox.rb
  test/unit/apicast/sandbox_test.rb
Labels: Remove non-APIAP

#2539 [THREESCALE-7134] Remove apicast conf generator
  app/lib/apicast/sandbox_conf_generator.rb
Labels: Remove non-APIAP

#2536 [THREESCALE-7134] Remove code reference for the proxy_logs model
  app/models/account/provider_methods.rb
  app/models/proxy_log.rb
  lib/system/database/definitions/mysql.rb
  lib/system/database/definitions/oracle.rb
  lib/system/database/definitions/postgres.rb
  test/factories/proxy.rb
Labels: Remove non-APIAP

#2513 [THREESCALE-7134] Removing ProviderLuaGenerator class
  app/lib/apicast/provider_lua_generator.rb
  test/unit/apicast/provider_lua_generator_test.rb
Labels: Priority: Blocker, Remove non-APIAP

#2492 THREESCALE-7134 Removing Apicast V1 class
  app/lib/logic/rolling_updates.rb
  app/models/proxy.rb
  features/services/mapping_rules.feature
  lib/tasks/proxy.rake
  test/models/backend_api_test.rb
  test/unit/proxy_test.rb
  test/unit/service_test.rb
  test/unit/services/service_discovery/import_cluster_definitions_service_test.rb
  test/unit/tasks/proxy_test.rb
Labels: Remove non-APIAP

#2540 [THREESCALE-7134] Remove apicast sandbox proxy
  app/lib/apicast/sandbox_proxy.rb
  test/unit/apicast/sandbox_proxy_test.rb
Labels: Remove non-APIAP

#2541 [THREESCALE-7134] Remove apicast conf generator and provider nginx generator
  app/lib/apicast/conf_generator.rb
  app/lib/apicast/provider_nginx_generator.rb
  test/unit/apicast/provider_nginx_generator_test.rb
Labels: Remove non-APIAP

#2542 [THREESCALE-7134] Remove apicast lua generators
  app/lib/apicast/generators.rb
  app/lib/apicast/lua_authorize_generator.rb
  app/lib/apicast/lua_authorized_callback_generator.rb
  app/lib/apicast/lua_generator.rb
  app/lib/apicast/lua_get_token_generator.rb
  app/lib/apicast/lua_threescale_utils_generator.rb
  test/unit/apicast/lua_authorize_generator_test.rb
  test/unit/apicast/lua_authorized_callback_generator_test.rb
  test/unit/apicast/lua_generator_test.rb
  test/unit/apicast/lua_get_token_generator_test.rb
  test/unit/apicast/lua_threescale_utils_generator_test.rb
Labels: Remove non-APIAP

#2545 [THREESCALE-7134] Removes User source class
  app/lib/apicast/user_source.rb
  test/unit/apicast/user_source_test.rb
Labels: Remove non-APIAP

#2549 Removes proxy example test and helpers
  .gitignore
  .rubocop_todo.yml
  test/integration/proxy_example_test.rb
  test/proxy_helpers/sentiment/analyzer.rb
  test/proxy_helpers/sentiment/config.ru
  test/proxy_helpers/sentiment/data/.gitkeep
  test/proxy_helpers/sentiment/data/AFINN-111.txt
  test/proxy_helpers/sentiment/data/working_AFINN-111.txt
  test/proxy_helpers/sentiment/sentiment_api.rb
  test/proxy_helpers/sentiment/tmp/pids/thin.pid
Labels: Remove non-APIAP

#2547 Removes apicast abstract generator
  app/lib/apicast/abstract_generator.rb
  test/unit/apicast/abstract_generator_test.rb
Labels: Remove non-APIAP

#2546 Removes apicast templates
  app/lib/apicast/templates/lua/_auth_params.lua.erb
  app/lib/apicast/templates/lua/_extract_usage.lua.erb
  app/lib/apicast/templates/lua/_proxy_rule.lua.erb
  app/lib/apicast/templates/lua/_service.lua.erb
  app/lib/apicast/templates/lua_authorize.lua.erb
  app/lib/apicast/templates/lua_authorized_callback.lua.erb
  app/lib/apicast/templates/lua_get_token.lua.erb
  app/lib/apicast/templates/nginx/_backend.conf.erb
  app/lib/apicast/templates/nginx/_common_backend_endpoints.conf.erb
  app/lib/apicast/templates/nginx/_oauth_backend_endpoints.conf.erb
  app/lib/apicast/templates/nginx/_server.conf.erb
  app/lib/apicast/templates/nginx/_service.conf.erb
  app/lib/apicast/templates/nginx_proxy_template.conf.erb
  app/lib/apicast/templates/provider_lua.lua.erb
  app/lib/apicast/templates/sandbox/_provider.conf.erb
  app/lib/apicast/templates/sandbox/_service.conf.erb
  app/lib/apicast/templates/threescale_utils.lua.erb
Labels: Remove non-APIAP

#2537 [THREESCALE-7134] Remove proxy conf columns code part
  app/models/account.rb
  app/models/account/provider_methods.rb
Labels: Remove non-APIAP

#2551 [THREESCALE-7134] Removes provider config generator
  app/lib/apicast/provider_config_generator.rb
Labels: Remove non-APIAP

#2514 Disabling ApiDocs Proxy should be an active setting
  app/assets/javascripts/swagger-ui/threescale.coffee.erb
  app/assets/javascripts/swagger-ui2/api_docs_proxy.coffee.erb
  app/views/admin/api_docs/base/swagger.html.erb
  app/views/provider/admin/api_docs/show-v2.html.erb
  app/views/provider/admin/api_docs/show.html.erb
  lib/developer_portal/app/views/shared/_swagger.html.erb
  lib/developer_portal/app/views/shared/_swagger_2_0.html.erb
  lib/developer_portal/lib/liquid/filters/rails_helpers.rb
  vendor/active-docs/app/assets/javascripts/active-docs/classes/resources_controller.js.erb
  vendor/active-docs/app/assets/javascripts/active-docs/form_handler.js.erb
Labels: Priority: Blocker, javascript

#2483 Using ruby 2.6
  .circleci/config.yml
  Dockerfile
  openshift/system/Dockerfile
Labels: Priority: Blocker, enhancement, ruby, tech-debt
