Repository 3scale/porta, pull requests merged in 2021-11, with the labels that each got.

#2687 Removing MessageBus
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/api/integrations_controller.rb
  app/lib/three_scale/message_bus_config.rb
  app/workers/zync_worker.rb
  config/application.rb
  config/examples/zync.yml
  config/initializers/message_bus.rb
  doc/licenses/licenses.xml
  test/unit/three_scale/message_bus_config_test.rb
  test/workers/zync_worker_test.rb
Labels: ruby, Priority: Blocker

#2695 Fixes deprecation of association reload
  test/integration/user-management-api/signup_test.rb
  test/unit/cms/section_test.rb
Labels: rails-5.1

#2693 Fixes deprecation in constructor of ActiveRecord exceptions
  test/workers/persist_event_worker_test.rb
Labels: rails-5.1

#2697 Fixes leftover deprecation of association reload
  test/unit/application_keys_test.rb
  test/unit/referrer_filters_test.rb
Labels: rails-5.1

#2692 [THREESCALE-5010] sphinx 5.3 does not set default value
  config/docker/thinking_sphinx.yml
  config/thinking_sphinx.yml
Labels: rails-5.1

#2701 Fixes profile test which saves profile withou account
  app/models/profile.rb
Labels: rails-5.1

#2732 [THREESCALE-7884] Fix service top applications endpoint
  app/controllers/stats/data/services_controller.rb
  test/integration/stats/data/service_controller_test.rb
Labels: Priority: High
