Repository 3scale/porta, pull requests merged in 2021-01, with the labels that each got.

#2318 Remove RU (Rolling Update) stripe_elements
  app/lib/logic/rolling_updates.rb
  app/views/payment_gateways/_stripe.html.erb
  app/views/payment_gateways/_stripe_elements.html.erb
  config/docker/rolling_updates.yml
  config/examples/rolling_updates.yml
  features/old/finance/billing_address_and_cc_details_order.feature
  lib/developer_portal/lib/liquid/tags/stripe_form.rb
  openshift/system/config/rolling_updates.yml
  test/unit/liquid/tags/stripe_form_test.rb
Labels: Priority: Low, cleanup, enhancement, ruby, tech-debt

#2333 [Refactor] Call logger once inside PaymentMethod#purchase!
  app/models/payment_transaction.rb
Labels: Priority: Low, cleanup, ruby

#2334 Refactor stripe into react
  .flowconfig
  app/helpers/payment_details_helper.rb
  app/javascript/packs/StripeForm.js
  app/javascript/packs/load_stripe.js
  app/javascript/src/PaymentGateways/components/StripeCardForm.jsx
  app/javascript/src/PaymentGateways/components/StripeFormWrapper.jsx
  app/javascript/src/PaymentGateways/index.js
  app/javascript/src/PaymentGateways/styles/stripe.scss
  app/views/payment_gateways/_stripe.html.erb
  app/views/payment_gateways/_stripe_billing_address.html.erb
  lib/developer_portal/app/views/developer_portal/main_layout.html.liquid
  lib/developer_portal/lib/liquid/filters/rails_helpers.rb
  package.json
  spec/javascripts/PaymentGateways/StripeFormWrapper.spec.jsx
  yarn.lock
Labels: javascript

#2288 Remove integration edit route
  app/assets/javascripts/provider/admin/apiconfig/services/integration.js.coffee
  app/assets/javascripts/provider/admin/apiconfig/services/integration/oidc.js
  app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
  app/controllers/api/integrations_controller.rb
  app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
  app/views/api/integrations/apicast/script_driven/_production.html.slim
  app/views/api/integrations/apicast/script_driven/_staging.html.slim
  app/views/api/integrations/apicast/shared/_authentication_settings.html.slim
  app/views/api/integrations/apicast/shared/_client.html.slim
  app/views/api/integrations/apicast/shared/_client_feedback.html.slim
  app/views/api/integrations/apicast/shared/_curl.html.slim
  app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
  app/views/api/integrations/apicast/shared/_oidc.html.slim
  app/views/api/integrations/edit.html.slim
  app/views/api/integrations/edit.js.erb
  app/views/api/integrations/service_mesh/_form.html.slim
  app/views/api/metrics/_link_to_mapping_rules.slim
  config/locales/en.yml
  config/routes.rb
  features/old/proxy.feature
  features/step_definitions/proxy_steps.rb
  test/integration/api/integrations_controller_test.rb
  test/unit/logic/rolling_updates_test.rb
  vendor/assets/stylesheets/highlight/styles/rainbow.css
Labels: Remove non-APIAP
