Repository 3scale/porta, pull requests merged in 2021-03, with the labels that each got.

#2391 Revert "Bump nokogiri from 1.10.10 to 1.11.0"
  Gemfile.lock
  app/lib/three_scale/json_representer.rb
Labels: dependencies, ruby, tech-debt

#2389 SCSS lint: remove SelectorFormat rule
  .scss-lint.yml
  app/assets/stylesheets/provider/_commons.scss
  app/assets/stylesheets/provider/_patternfly_tabs_fake.scss
  app/assets/stylesheets/provider/_pop_navigation.scss
  app/assets/stylesheets/provider/_vertical_nav.scss
  app/assets/stylesheets/provider/layouts/_main.scss
  app/javascript/src/LoginPage/assets/styles/loginPage.scss
  app/javascript/src/PaymentGateways/stripe/styles/stripe.scss
Labels: Stale

#2404 [gem] Official mimemagic instead of github fork
  Gemfile.base
  Gemfile.lock
  Gemfile.prod.lock
  doc/licenses/licenses.xml
Labels: dependencies, ruby
