Repository 3scale/porta, pull requests merged in 2021-05, with the labels that each got.

#2415 [2.11] Implement inline errors to the Add Backend form
  app/controllers/api/backend_usages_controller.rb
  app/javascript/packs/add_backend_usage.js
  app/javascript/src/BackendApis/components/AddBackendForm.jsx
  app/javascript/src/BackendApis/components/BackendSelect.jsx
  app/javascript/src/BackendApis/components/BackendSelect.scss
  app/javascript/src/BackendApis/components/PathInput.jsx
  app/javascript/src/Common/components/SelectWithModal.jsx
  app/views/api/backend_usages/new.html.slim
  spec/javascripts/BackendApis/components/AddBackendForm.spec.jsx
  test/integration/api/backend_usages_controller_test.rb
Labels: javascript, ruby

#2430 [gemfile] One Gemfile, remove Gemfile.prod
  .circleci/config.yml
  Gemfile
  Gemfile.base
  Gemfile.prod
  Gemfile.prod.lock
  Makefile
Labels: dependencies, ruby

#2437 🐛 Fix CSRFToken import
  app/javascript/src/NewApplication/components/NewApplicationForm.jsx
Labels: javascript

#2442 Removes hidden element from Service overview
  app/views/api/services/show.html.slim
Labels: Remove non-APIAP

#2443 Clean up APIAP traces in Integration Controller
  app/controllers/api/integrations_controller.rb
Labels: Remove non-APIAP

#2445 Clean up Backend API model
  app/models/backend_api.rb
Labels: Remove non-APIAP

#2446 Clean up APIAP traces in integrations show page
  app/presenters/api/integrations_show_presenter.rb
  app/views/api/integrations/show.html.slim
  test/integration/api/integrations_controller_test.rb
Labels: Remove non-APIAP

#2456 Display "Show all" button only when items > 20
  app/assets/stylesheets/provider/_dropdowns.scss
  app/javascript/src/Common/components/SelectWithModal.jsx
  app/javascript/src/Common/components/SelectWithModal.scss
  spec/javascripts/BackendApis/components/BackendSelect.spec.jsx
  spec/javascripts/BackendApis/components/__snapshots__/BackendSelect.spec.jsx.snap
  spec/javascripts/Common/components/SelectWithModal.spec.jsx
Labels: javascript

#2462 [feature] K8s management tasks
  Gemfile
  Gemfile.lock
  app/workers/create_default_proxy_worker.rb
  app/workers/restore_apicast_master_token_worker.rb
  config/initializers/active_job_uniqueness.rb
  lib/tasks/access_tokens.rake
  lib/tasks/k8s.rake
  test/test_helper.rb
  test/unit/tasks/access_tokens_task_test.rb
  test/workers/restore_apicast_master_access_token_worker_test.rb
Labels: Priority: Blocker, feature, ruby

#2427 Fixed THREESCALE-6428 - Add APIAP Routing policy just before APICast policy
  app/lib/backend_api_logic/routing_policy.rb
  test/unit/backend_api_logic/routing_policy_test.rb
Labels: Stale

#2463 [fix] Ignore error reporting on misused liquid macro `do_not_send`
  config/initializers/bugsnag.rb
Labels: bug, ruby

#2460 Fix OAS3 mapping error
  app/lib/three_scale/open_api/url_resolver.rb
  test/unit/three_scale/open_api/url_resolver_test.rb
Labels: bug, ruby
